Instawork/hyperview

README.md
docs/reference_view.md

Fixing some typos reported externally.

Fix some typos in README and docs

---

src/index.js

Added an action to let the app ask the user to rate it.

Add "ask-rating" behavior action

---

src/index.js
src/services/namespaces/index.js

Adds `sms` behavior action type. Example: `<behavior action="sms" number="(123) 456-789" />`

Add "sms" custom action

---

examples/navigation/index.xml
examples/navigation/reload.xml
src/index.js

The "reload" behavior is equivalent to "Reload this page" in a web browser: the current screen is re-requested from the backend. Eventually, we can add support for custom loading screens while the reload is happening. For now, the basic support is enough for rapid development.

Add reload behavior

---

website/blog/2019-02-10-When-XML-Beats-JSON-2.md

Part two of the series looks at the built-in extensibility of XML.

New blog post: XML extensibility

---

src/services/stylesheets/index.js

[Task](https://app.asana.com/0/923014529014430/1001436423171946)
tl;dr
Use `resizeMode` in `image` styles

feat: add resizeMode to image stylesheet

---

src/index.js

[Task](https://app.asana.com/0/923014529014430/1106456911336592)
In dev mode logs the updated serialized xml to console.

feat: add xml debugging

---

README.md
demo/package.json
demo/yarn.lock

Add missing command to forward simulator traffic to demo xml service

Docs: Demo on android simulator

---

src/components/hv-web-view/index.js
src/components/hv-web-view/stories/basic.xml
src/components/hv-web-view/stories/index.js
src/components/hv-web-view/types.js
src/services/components/index.js
src/types.js
storybook/stories.gen.js
storybook/templates.gen.js

Add `HvWebView` component, map it to `web-view` xml element

Feature: HvWebView component

---

docs/reference_behavior_share.md
docs/reference_custom_behaviors.md
docs/reference_web.md
website/sidebars.json

https://app.asana.com/0/923014529014430/1114001676407598/f
Updated the docs to reflect the new custom behavior system.

Update custom behaviors doc

---

examples/ui_elements/text.xml
src/services/render/index.js

Render CDATA nodes

---

website/blog/2019-04-21-0.12-Released.md

Update with all the new features/changes since the last update.

Blog post: April update

---

docs/reference_behavior_attributes.md
examples/navigation/deep-links.xml
examples/navigation/index.xml
src/core/hyper-ref/index.js
src/core/hyper-ref/types.js
src/index.js
src/services/index.js
src/services/navigation/index.js
src/types.js

Extract navigation specific code into its own module with flow types, and implement deep link support

Navigation module + `deep-link` action

---

docs/reference_behavior_attributes.md
examples/navigation/deep-links.xml
examples/navigation/index.xml
src/components/hv-image/index.js
src/components/hv-image/stories/basic.xml
src/components/hv-image/stories/index.js
src/components/hv-image/types.js
src/core/hyper-ref/index.js
src/core/hyper-ref/types.js
src/index.js
src/services/components/index.js
src/services/index.js
src/services/navigation/index.js
src/services/render/index.js
src/types.js
storybook/stories.gen.js
storybook/templates.gen.js

Extract `HvImage` component into its own module.
This is a sub-PR of #50, props to @divyanshu013 for leading the original work.
https://app.asana.com/0/0/933653114164338/f

HvImage: Refactor

---

src/components/hv-list/index.js

Usage:
```xml
<list scroll-orientation="horizontal" shows-scroll-indicator="false">
...
</list>
```
Added [task](https://app.asana.com/0/923014529014430/1123898731905276/f) to document it

Add support for horizontal scrolling

---

package.json
yarn.lock

Relates to Instawork/xmldom/pull/1
https://app.asana.com/0/244065166232575/1129162278755512/f

Swap xmldom with our own fork

---

README.md
package.json
src/components/hv-list/index.js
src/components/hv-section-list/index.js
src/index.js
storybook/helpers.js
yarn.lock

Relates to Instawork/xmldom/pull/1 and Instawork/xmldom/pull/2
https://app.asana.com/0/244065166232575/1129162278755512/f

Swap xmldom with xmldom-instawork

---

demo/package.json
demo/screens/HyperviewScreen.js
demo/yarn.lock
examples/ui_elements/forms/date_field.xml
examples/ui_elements/forms/index.xml
examples/ui_elements/forms/picker.xml
package.json
src/components/hv-date-field/index.js
src/components/hv-date-field/styles.js
src/components/hv-date-field/types.js
src/index.js
src/services/components/index.js
src/types.js
yarn.lock

[TAD](https://instawork.atlassian.net/wiki/spaces/EN/pages/901677061/Date+field+element)
Implements the `<date-field>` element for selecting dates. This works similar to the `<picker>` field:
- renders a field (view with text) on the screen. The view and text can be styled.
- tapping the field focuses it and brings up the date selector:
- on iOS, we show a bottom sheet with the spinning date picker
- on Android, we show the system date picking modal
- Selected dates are shown in the field, rendered in the given format.
- The date formatting (for the field) is handled via dependency injection from the client. In the demo app, we use the `moment` library to demonstrate the formatting.
- The date formatting function is passed to date fields from the root screen via a React context.
iOS:

Implement date-field element

---

docs/reference_behavior_attributes.md

Docs for the new trigger - `on-event` and new behavior action `dispatch-event`
Related PR #81

Docs: add dispatch-event and on-event

---

README.md
package.json
src/components/hv-web-view/index.js
yarn.lock

Add webview from react-native-webview instead of react-native

Add webview from react-native-webview

---

src/services/index.js

Fix typo in testID prop, and add accessibilityLabel prop.
Ref:
- [testID](https://facebook.github.io/react-native/docs/0.59/view#testid)
- [accessibilityLabel](https://facebook.github.io/react-native/docs/0.59/view#accessibilitylabel)
Before:
After:

Fix: testID / accessibilityLabel props

---

src/index.js

Parser accepts URL as a single argument.
Relates to https://app.asana.com/0/0/1146909686118217/f

Add before/after hooks to XML parser

---

src/index.js

Fix: Add missing parser hooks

---

src/index.js

Fix: returned parsed XML

---

docs/reference_datefield.md
website/sidebars.json

[Asana](https://app.asana.com/0/378088913887644/1153389465437105)
Add missing docs for `date-field`.

Docs: date-field

---

src/index.js

Relates to https://github.com/Instawork/mobile/pull/2700

Export namespaces

---

demo/screens/HyperviewScreen.js

- make it easier to point the demo at a backend server

Fix: Include "Accept" header in demo XML requests

---

src/services/stylesheets/index.js

Add missing text style property

Support underlined text

---

src/index.js

Reverts Instawork/hyperview#135

Revert "mark deprecated method as UNSAFE_"

---

src/services/dom/index.test.js

Fix broken test

---

docs/reference_web.md
examples/ui_elements/web-view.xml
schema/hyperview.xsd
src/components/hv-web-view/index.js

- Add `html` attribute as an alternative to `url`
- Add example
- Add schema definition
- Update doc
Relates to https://app.asana.com/0/1173541402094433/1173541402094440/f

Update webview element

---

src/index.js

Follow up for #147 - pass method argument in `fetchElement`

Fix POST requests

---

examples/ui_elements/web_views/html.xml
examples/ui_elements/web_views/index.xml
examples/ui_elements/web_views/injected_javascript.xml
examples/ui_elements/web_views/url.xml

<web-view>: Add examples (3/3)

---

src/core/components/load-error/index.js
src/core/components/load-error/styles.js
src/core/components/load-error/types.js
src/core/components/loading/index.js
src/core/components/loading/styles.js
src/core/components/loading/types.js
src/index.js

Move loading and load error components into their own modules, and remove index.js unused imports.

Extract loading/load error components

---

docs/reference_web.md
examples/ui_elements/web_views/dispatch_event.xml
examples/ui_elements/web_views/dispatch_event_append.xml
examples/ui_elements/web_views/html.xml
examples/ui_elements/web_views/index.xml
examples/ui_elements/web_views/injected_javascript.xml
src/components/hv-web-view/index.js

Allow dispatching Hyperview events from a webview

Webview: Dispatch Hyperview event

---

src/components/hv-picker-field/index.js

After selecting an item from a picker field, update the DOM so that its value is correctly serialized along with other form fields.
Should fix following issue: https://app.asana.com/0/491474088351836/1177334335698804/f
Tested with demo app by amending template so that:
- a submit button that "POST" is present
- verified that generated HTTP request does not contains correct selection before fix, and does contain correct selection after fix
<details>
<summary>Template diff</summary>
```patch
diff --git a/examples/ui_elements/forms/picker.xml b/examples/ui_elements/forms/picker.xml
index 9337e35..a30c083 100644
--- a/examples/ui_elements/forms/picker.xml
+++ b/examples/ui_elements/forms/picker.xml
@@ -11,15 +11,16 @@
paddingLeft="24"
paddingRight="24"
paddingTop="24" />
-      <style …
```

Fix: Picker field on Android

---

schema/amplitude.xsd

See https://github.com/Instawork/mobile/blob/master/core-mobile/src/services/hyperview-behaviors/amplitude.js#L13 for implementation

Schema: support user-properties on amplitude behavior

---

docs/reference_behavior_attributes.md
schema/hyperview.xsd
src/behaviors/hv-open-settings/index.js
src/services/behaviors/index.js

Add `open-settings` behavior, which links the user into the Settings app

Open settings behavior

---

schema/hyperview.xsd

https://github.com/Instawork/mobile/pull/3277
Relates to this pr, where a new behavior was added.

Update: add branch to schema

---

schema/hyperview.xsd

Fix: changing branch to branch-share

---

schema/branch.xsd
schema/hyperview.xsd

Adding branch attributes to schema

---

docs/reference_behavior_attributes.md
examples/advanced_behaviors/copy_to_clipboard/index.xml
examples/advanced_behaviors/index.xml
schema/hyperview.xsd
src/behaviors/hv-copy-to-clipboard/index.js
src/services/behaviors/index.js

[Asana](https://app.asana.com/0/378088913887644/1198199975357167/f)
- Copy to clipboard functionality implemented as a behavior. 
- Updated docs
Note: Although this component has been moved to a community library, there is an [issue](https://github.com/react-native-clipboard/clipboard/issues/71) which makes it unusable. So I've used the component from `react-native` itself for now.

Copy to clipboard behavior

---

src/index.js

[Asana](https://app.asana.com/0/923014529014430/1199167820695871/f)
Functionality needed for the `<s3-file-upload>` element implemented in https://github.com/Instawork/mobile/pull/3417

Make modules available for renderElement and Events

---

docs/reference_selectmultiple.md

Fix typo in docs

---

schema/intercom.xsd

Add support `mode` and `message` attributes for Intercom

Intercom: Extend schema for mode and message

---

schema/hyperview.xsd

Ref: https://reactnative.dev/docs/layout-props#display

Add `display` style prop to schema

---

schema/hyperview.xsd
src/services/stylesheets/index.js

Add support for number of lines for text

Style update: Add support for number of lines

---

docs/reference_style.md
src/services/stylesheets/index.js

Enabled support for `zIndex` attribute in styles.

Update: Support zindex attribute in styles

---

src/components/hv-picker-field/index.js

Reverts Instawork/hyperview#208
Found regression: https://app.asana.com/0/1198212378325207/1199962384959603/f

Revert "Fix: Picker field changes immediately"

---

schema/hyperview.xsd
schema/nfc.xsd

Update Xsd for the new behavior NFC

Hyperview xsd: Update for new behavior for NFC

---

demo/package.json
demo/yarn.lock

Update dependencies of demo app.

Update demo app

---

src/index.js
src/services/events/index.js

These slow down the simulator and are not really useful.

Remove XML debugging log lines

---

.eslintignore
src/VisibilityDetectingView.js
src/core/hyper-ref/index.js
src/index.js

- 8ba6a43 Lint `src/index.js` (linting errors in 87446a5)
- a2308fe Lint `src/VisibilityDetectingView.js` (linting errors in 29ad64a)

Lint previously ignored files

---

src/components/hv-date-field/types.js
src/components/hv-list/index.js
src/components/hv-section-list/index.js
src/core/hyper-ref/index.js
src/core/hyper-ref/types.js
src/index.js
src/services/dom/parser.js
src/services/dom/types.js
src/services/index.js
src/services/navigation/index.js
src/services/render/index.js
src/types.js

Reverts Instawork/hyperview#250
These changes introduce a significant amount of flow errors in our project. I'll keep working on this in a separate branch until I can mitigate these errors.

Revert "Add missing flow type annotations"

---

src/index.js

to fix below error when debug by `yarn sync`:

fix error when destructure body from NodeList

---

examples/ui_elements/forms/text_input.xml
examples/ui_elements/forms/textarea.xml
schema/hyperview.xsd
src/components/hv-text-area/index.js
src/components/hv-text-field/index.js

#276 This pull request is used for solving this issue. If you have any other suggestions, please let me know. Thank you

update editable attribute for text-field

---

src/components/hv-image/index.js
src/components/hv-text/index.js
src/components/hv-view/index.js
src/core/hyper-ref/index.js
src/services/index.js

Propagate test props to wrapping `TouchableOpacity` so that they are detectable in iOS.
https://app.asana.com/0/847356694390130/1200271591067682/f

Fix: iOS test props for press behaviors

---

src/components/hv-view/index.js
src/components/hv-view/types.js

#302, I was not too sure if I should put this as an attribute or just add it in props because I don't know if this is considered as a bug for ios keyboardscrollview. I will it for you to make the decision. Please let me know if I should take anything else into consideration, thank you!

Add automaticallyAdjustContentInsets for view

---

examples/ui_elements/keyboard_avoiding_view.xml

Updated the keyboard avoiding view example to show keyboard awareness in scroll views.
https://user-images.githubusercontent.com/2883006/119646026-4e8b4f80-be3c-11eb-8e2f-ef5be32b530d.mp4

Update: also showcase keyboard awareness in scroll view

---

examples/behaviors/_once_1.xml
examples/behaviors/_once_2.xml
examples/behaviors/index.xml
examples/behaviors/once.xml
src/core/hyper-ref/index.js
src/index.js

Addresses #283. `ran-once="true"` should be set on the same element as `once="true"`.
Added example showing the fix:
https://user-images.githubusercontent.com/1034502/121265518-c8c0c880-c86d-11eb-874c-dada75816116.mov

bug fix: set ran-once flag on the triggering behavior element

---

package.json
src/components/hv-list/index.js
src/components/hv-list/index.test.js

Patch was released on NPM, re-integrate it in master

Re-integrate patch 0.39.1

---

schema/hyperview.xsd

Ref: https://reactnative.dev/docs/layout-props#zindex

Add `zIndex` style to schema

---

src/components/hv-date-field/index.js

add attribute 'locale' to date-picker to support locale as below

fix: date-picker supports locale

---

schema/calendar.xsd
schema/hyperview.xsd

Relates to Instawork/mobile/pull/3820

Add calendar behavior schema

---

schema/calendar.xsd
schema/hyperview.xsd

Fix: Calendar schema

---

schema/hyperview.xsd

Adds the `session-recording` action to allow for custom behavior

feat: add session-recording action for fullstory

---

test/helpers.js

Expose XML parser to Hyperview test helpers public API.

feat(test-helpers): Expose XML parser

---

schema/hyperview.xsd

Relates to Instawork/mobile/pull/3898

maintenance(schema): Add custom triggers

---

.prettierignore

When using a JetBrains IDE, prettier fails and blocks the release process:
```
Checking formatting...
[warn] .idea/workspace.xml
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
error Command failed with exit code 1.
```

Exclude .idea/ folder form prettier analysis

---

docs/reference_behavior_attributes.md
docs/reference_switch.md
examples/behaviors/change.xml
schema/hyperview.xsd
src/components/hv-switch/index.js
src/services/dom/helpers.js

`<switch>` component now supports behaviours on `change` trigger
https://user-images.githubusercontent.com/18195461/147067363-5875b63a-5e62-41f9-81d7-bbea3eed83cb.mp4

Adding support for "change" trigger on switch component

---

README.md

This got me stuck for a bit, so I thought it would make sense to call out what the working directory should be.
Clearly, it says it in prose, but I didn't notice it for quite a while.

Call out working directory for demo

---

demo/package.json
demo/yarn.lock

Follow up for #385: update the Hyperview version reference in the demo app.

fix: Demo app Hyperview version

---

demo/package.json
demo/yarn.lock
package.json

- Update Hyperview package reference in demo app
- Update `postversion` script to automatically update demo app

chore(demo): update Hyperview to v0.50.0

---

website/build-schema.sh

Publish new schema

---

docs/reference_sectionlist.md
examples/ui_elements/sectionlist/index.xml
examples/ui_elements/sectionlist/non_sticky_titles.xml
schema/core.xsd
src/components/hv-section-list/index.js

Add attribute to configure sticky behavior on `section-list` elements.
https://user-images.githubusercontent.com/309515/169395470-b24b66b5-22c8-4aa7-b6f9-ff125d65c259.mp4

feat(section-list): Configurable sticky headers

---

schema/core.xsd
schema/hyperview.xsd

Reverts Instawork/hyperview#438
We're seeing some incompatibility while verifying existing docs.

Revert "refactor(schema): Make extending behavior schema possible"

---

examples/ui_elements/text.xml

Update styles to better surface different use cases

chore: Update <text> demo screen

---

src/components/hv-switch/index.js
src/components/hv-switch/style-sheet/index.js
src/components/hv-switch/style-sheet/index.web.js

Wrap RN only imports to prevent build failures

fix: `hv-switch` imports

---

.eleventy.js
examples/_includes/directory_list.xml.njk

Add filter that allows sorting collections of templates in alphabetical order.

feat(11ty): Sort template collections

---

README.md
docs/guide_installation.md

Files paths have changed for physical devices

fix(installation): change instructions for physical

---

docs/reference_style.md

Fixing misleading docs pointed out in #494.

Add better explanation for styling options

---

schema/core.xsd
src/services/stylesheets/index.js

Add support for style props that are specific to rendering text-field component on web.
See https://stackoverflow.com/a/62431191/237637

feat: add support for rn-web specific style props

---

docs/reference_style.md
schema/core.xsd
src/services/stylesheets/index.js

There is an issue #370 about just that, and I needed it, so here we go. 😁

pass aspectRatio to React Native

---

docs/guide_installation.md

In section 4. the examples links are broken

Updated links for examples

---

examples/ui_elements/list/index.xml
examples/ui_elements/sectionlist/_infinite_scroll_page2.xml
examples/ui_elements/sectionlist/index.xml
examples/ui_elements/web_views/index.xml

Replacing redundant keys in examples with unique values

fix(list): example key values

---

examples/advanced_behaviors/index.xml.njk
examples/advanced_behaviors/text-field.xml
schema/core.xsd

Also add an example to showcase this ability.
https://user-images.githubusercontent.com/309515/225356416-07a3fff0-c093-4874-bbc3-40524b0bec87.mp4

chore: Update `text-field` schema to support multiple behaviors

---

src/core/components/load-element-error/index.js
src/core/components/load-element-error/styles.js
src/core/components/load-element-error/types.js
src/index.js

PR https://github.com/Instawork/hyperview/pull/504 changed partial document error state which removed reload button, adding the reload button back.
Edit: updated screenshots based on feedback
| error state 1 | error state 2 |
| --- | --- |
| ![Simulator Screenshot - iPhone 13 - 2023-04-19 at 23 15 57](https://user-images.githubusercontent.com/28518512/233454036-204a1dac-d1e4-4677-a280-1cc3b1f75ea9.png) | ![Simulator Screenshot - iPhone 13 - 2023-04-19 at 23 30 27](https://user-images.githubusercontent.com/28518512/233454043-f0e531c8-ac86-4a79-bffc-743abc21af4d.png) |

fix: partial document error state

---

.eslintrc
src/services/error/index.test.ts
src/services/error/index.ts

- Created new HvBaseError class
- Created tests for base error
Borrowed heavily from https://github.com/Instawork/mobile/blob/master/core-mobile/src/services/errors/index.test.js

feat(error) - adding an HvBaseError into Hyperview

---

src/services/error/index.test.ts

Unit test was failing due to a relative import path

fix(error) - fix for import path in unit test

---

src/contexts/index.js
src/core/components/hv-navigator/index.tsx
src/core/components/hv-screen/types.ts
src/services/dom/parser.d.ts
src/services/dom/parser.js

Fixing the issues with integration branch

feat(navigation) - integration patch

---

src/core/components/hv-screen/index.js
src/core/hyper-ref/index.js
src/services/navigation/index.js
src/types.js

Adding support to pass target values into navigation actions
https://app.asana.com/0/0/1204660853298351/f

feat(navigation) - Add target support

---

package.json

Moved the @react-navigation/native dependency into peer and dev
https://app.asana.com/0/0/1204801986148220/f

chore(navigator) - moving dependencies

---

examples/advanced_behaviors/alert/behavior.xml.njk
examples/advanced_behaviors/alert/multiple_behaviors.xml.njk
examples/advanced_behaviors/alert/options.xml.njk
examples/advanced_behaviors/copy_to_clipboard/index.xml.njk
examples/advanced_behaviors/custom_share.xml.njk
examples/advanced_behaviors/multiple_same.xml.njk

fix advanced behavior examples

---

src/index.tsx
src/services/events/index.d.ts
src/services/index.d.ts
src/services/render/index.d.ts

Including the static functions and associated typescript declaration files to export the original static functions and exports
Asana: https://app.asana.com/0/0/1204865667381527/f

fix(navigator) - adding exports from original Hyperview

---

src/services/dom.d.ts
src/services/dom/parser.d.ts
src/services/render/index.d.ts

A few nullable values were declared using incorrect syntax.
Asana: https://app.asana.com/0/0/1204908001962683/f

fix(navigation) - Corrected syntax in declaration files

---

package.json
scripts/sync/index.js
src/core/components/hv-root/index.tsx
src/index.js
tsconfig.json

- Created new src/index.js as a Javascript barrel file with correct exports
- Moved previous src/index.tsx into new src/core/components/hv-root location
- Updated sync script to use index.js instead of index.tsx naming
- Updated build script to include *.ts/x files
Asana: https://app.asana.com/0/0/1204911832369856/f

fix(navigation) - Create a barrel file to support required exports

---

src/contexts/navigation.ts
src/contexts/navigator.tsx
src/core/components/hv-navigator/index.tsx
src/core/components/hv-navigator/types.ts
src/core/components/hv-route/index.tsx
src/core/components/hv-route/types.ts
src/core/components/hv-screen/types.ts

- Replaced composite types with direct definitions
- Removed cross-module imports
- Removed index-level type definitions
Asana: https://app.asana.com/0/0/1204911832369860/f

chore(navigation) - Type cleanup

---

src/core/components/hv-navigator/index.tsx
src/core/components/hv-navigator/types.ts
src/core/components/hv-route/index.tsx

- Updated HvNavigator to receive HvRoute through a getter prop
Asana: https://app.asana.com/0/0/1204845198486199/f

fix(navigation) - Remove cyclic dependency between HvRoute and HvNavigator

---

scripts/sync/index.js
src/contexts/navigation.ts
src/contexts/navigator.tsx
src/core/components/hv-navigator/index.tsx
src/core/components/hv-navigator/types.ts

- fixing extra semicolon in sync script
- moving types into the contexts which own them

chore(navigation) - cleanup

---

src/core/components/hv-route/index.tsx
src/core/components/hv-route/types.ts

- Removed two property types which weren't necessary as the data was available in the same context
- Moved the try/catch to the main render to handle all exceptions correctly
Asana: https://app.asana.com/0/0/1204845198486201/f

chore(navigation) - clean up prop types

---

src/services/navigator/helpers.test.ts

fix(navigation) - updated for new xmldom module name

---

src/core/components/hv-route/index.tsx
src/core/components/hv-route/types.ts

Reduced complexity of determining the url

chore(cleanup) - improving url logic

---

src/contexts/navigation.ts
src/core/components/hv-root/index.tsx
src/core/components/hv-route/index.tsx
src/core/components/hv-route/types.ts
src/core/components/hv-screen/index.js
src/core/components/hv-screen/types.ts

Add `onError` optional prop to main component, and call it on caught errors.
https://app.asana.com/0/1204323441804469/1205174837597406/f

feat: `onError` hook

---

src/core/components/hv-route/index.tsx

https://github.com/Instawork/hyperview/pull/619/files#r1280820616

fix(`onError`): Also passing prop to `HvScreen` in `HvRoute`

---

src/core/components/hv-route/index.tsx
src/services/navigator/helpers.ts
src/services/navigator/index.ts
src/services/navigator/types.ts

- Moving the route search into helpers
- Moving the local types into types.ts

chore (navigation) - Cleanup of navigator helpers

---

demo/package.json
demo/yarn.lock
package.json
schema/core.xsd
src/contexts/navigation.ts
src/core/components/hv-navigator/index.tsx
src/core/components/hv-root/index.tsx
src/core/components/hv-route/index.tsx
src/core/components/hv-route/types.ts
src/core/components/hv-screen/index.js
src/core/components/hv-screen/types.ts
src/services/navigator/helpers.test.ts
src/services/navigator/helpers.ts
src/services/navigator/index.ts
src/types.ts

- Merged master in and resolved conflicts
- Fixed a few minor type differences in the src/types file

chore(update) - merging latest changes from master

---

examples/navigation/reload.xml.njk
src/core/components/hv-screen/index.js
src/core/hyper-ref/index.js

Added support for show/hide elements.
See additional notes: https://app.asana.com/0/1204323441804469/1205320418809826/f
| ---- | ---- |
| ![before](https://github.com/Instawork/hyperview/assets/127122858/6369cf16-d61e-4c29-bb46-cd1291430b19) | ![after](https://github.com/Instawork/hyperview/assets/127122858/37ebeb7d-4fc4-42dc-9f96-1786cd56787d) |
Asana: https://app.asana.com/0/1204008699308084/1205320418809819/f

bug(reload) - adding support for show-during-load and hide-during-load

---

src/core/components/hv-navigator/index.tsx

No need to pass separate props object into the components

chore(cleanup) - passing props

---

src/core/components/hv-screen/index.js

There are a lot of errors on Sentry with useless messages: https://instawork.sentry.io/issues/3576375783/?query=is%3Aunresolved+no+error+message&referrer=issue-stream&statsPeriod=14d&stream_index=0
Adding in a basic message to provide context on the error.

chore(error) - improved error messaging

---

docs/reference_item.md
examples/_includes/styles.xml.njk
examples/case_studies/contacts/index.xml.njk
examples/case_studies/contacts/list.xml.njk
examples/ui_elements/list/sticky_items/index.xml.njk
schema/core.xsd
src/components/hv-list/index.js
src/components/hv-view/index.js

Port sticky mechanism present on scrollviews, to `<list>` element.

feat(`<list>`): sticky `<item>`

---

docs/reference_list.md
docs/reference_sectionlist.md
docs/reference_view.md
examples/case_studies/contacts/list.xml.njk
examples/ui_elements/list/dismiss_keyboard_on_drag/index.xml.njk
examples/ui_elements/scroll_view/index.xml.njk
examples/ui_elements/sectionlist/dismiss_keyboard_on_drag/index.xml.njk
schema/core.xsd
src/components/hv-list/index.js
src/components/hv-section-list/index.js
src/components/hv-view/index.js
src/components/hv-view/types.js
src/services/keyboard/index.ts

Add attribute to `view`, `list` and `sectionlist` elements, which condition whether the keyboard should be dismissed upon user interacting with the scroll view.
https://github.com/Instawork/hyperview/assets/309515/8c4dbcc0-064a-473c-a1d9-e37d79b19b3f

feat(scrollable-views): `dismiss-keyboard-on-drag`

---

src/services/navigator/helpers.ts
src/services/navigator/types.ts

Using constants for consistency

chore(navigation) - cleanup attribute retrieval

---

docs/reference_index.md

It seems to me as some forgotten after the editing "artifact."
OT: I found this system through the Hepermedia systems book and like what I see.

Fix <option> description.

---

package.json
src/VisibilityDetectingView.tsx
src/components/hv-date-field/field-label/types.ts
src/services/dom/parser.ts
yarn.lock

I solved a few of the errors by:
1. Using a newer version of the xmldom package which fixes the module name
2. correcting some signatures

chore(TypeScript) - fixing some of the errors

---

src/core/components/navigator-tab/index.tsx

Fix for issue where a tab navigation is auto closing any stack modals.
Asana: https://app.asana.com/0/1204008699308084/1205572796301526/f

chore(bug) - fix navigation

---

.eslintrc

Run prettier on `.eslintrc` file, and sort rules alphabetically

chore(ts): prettify `.eslintrc`

---

src/services/dom/errors.d.ts
src/services/navigator/helpers.test.ts
src/services/navigator/helpers.ts
tsconfig.json

TS should now capture every file of the project.
This PR also fixes new errors resulting from that config update.

chore(ts): remove `files` restriction in TS config

---

src/contexts/navigation.ts
src/core/components/hv-route/types.ts
src/core/components/hv-screen/types.ts
src/types.ts

Use correct type for fetch prop, and centralize its definition.

refactor: Fetch type

---

package.json

Change .js to .ts in the `main` key of package.json

fix: package main path

---

src/core/components/navigator-stack/types.ts
src/core/components/navigator-tab/types.tsx

Resolving CI issues found after merging master with TS migration into integration branch

chore(navigation): cleanup after merging master

---

package.json
test/schema/README.md
test/schema/navigator/partial/1.xml
test/schema/navigator/partial/2.xml
test/schema/navigator/partial/3.xml
test/schema/navigator/partial/4.xml

Add new directory `test/schema/` that contains raw xml files that are validated with the `test:validate-xml` command.

chore: test schema changes

---

src/core/components/hv-route/index.tsx

Converting the callback injection from function to property.
Asana: https://app.asana.com/0/1204008699308084/1205888765821734/f

chore: clean up hv-route callback injection

---

demo/src/constants.ts
demo/src/gesture-handler/index.ts
demo/src/helpers.ts
demo/src/types.ts
src/VisibilityDetectingView.tsx
src/behaviors/hv-hide/index.ts
src/behaviors/hv-select-all/index.ts
src/behaviors/hv-set-value/index.ts
src/behaviors/hv-show/index.ts
src/behaviors/hv-toggle/index.ts
src/behaviors/hv-unselect-all/index.ts
src/services/navigation/index.ts
src/services/navigator/helpers.test.ts

Found several places which were missing copyrights. I think I got them all.
Asana: https://app.asana.com/0/1204008699308084/1205996503347223/f

chore: Adding copyrights where missing

---

src/core/components/hv-navigator/index.tsx

Deep links which trigger modals were not working. The core reason is the navigation code creates a dynamic stack navigator for every modal. This change was not reflected in the DOM so as the deep link handling cleaned out undefined screens, it could not match the dynamic navigator with one in the DOM.
Changes: update the DOM to reflect the added navigator and child route.
Asana: https://app.asana.com/0/1204008699308084/1206050332658089/f

fix: deep link modals

---

src/components/hv-list/index.tsx
src/contexts/back-behaviors.test.ts
src/contexts/back-behaviors.tsx
src/core/components/hv-root/index.tsx
src/core/components/hv-root/types.ts
src/core/components/hv-route/index.tsx
src/core/components/hv-screen/types.ts
src/core/hyper-ref/index.tsx
src/services/navigator/types.ts
src/types.ts

Includes:
- #789
- #790
- #791
- #793
Resolves https://github.com/Instawork/hyperview/issues/776
QA Plan:
- https://github.com/Instawork/mobile/pull/5824

Hyperview pre-release integration

---

schema/core.xsd

Adding "back" into core.xsd trigger definition

chore: update core.xsd with 'back' trigger

---

docs/example_tabs.md

Updated <screen> to include a <body>
Asana: https://app.asana.com/0/1205761271270033/1206290261007818/f

chore: fix documentation HXML

---

docs/reference_behavior_attributes.md
docs/reference_doc.md
docs/reference_index.md
docs/reference_nav_route.md
docs/reference_navigator.md
website/sidebars.json

Adding documentation around `<navigator>`, `<nav-route>` and `trigger="back"`
Asana: https://app.asana.com/0/1204008699308084/1205367406163854/f

chore: update hyperview documentation

---

.prettierignore
demo/src/HandleBack.ts
demo/src/HyperviewScreen.tsx
demo/src/Navigator.tsx
demo/src/gesture-handler/index.ts
demo/src/helpers.ts

Re-enabling prettier formatting in demo and resaving files. No changes made.
Asana: https://app.asana.com/0/1204008699308084/1206525468973411/f

chore: prettify demo code

---

docs/guide_html.md

This code snippet was missing a type

chore: Cleaning up documentation

---

.circleci/config.yml
examples/_includes/styles.xml.njk
examples/advanced_behaviors/set_value/index.xml.njk
examples/case_studies/contacts/index.xml.njk
examples/navigation/new.xml.njk
examples/navigation/push.xml.njk
examples/ui_elements/forms/date_field/index.xml.njk
examples/ui_elements/forms/picker/index.xml.njk
examples/ui_elements/forms/select_multiple/index.xml.njk
examples/ui_elements/forms/select_single/index.xml.njk
examples/ui_elements/forms/switch/index.xml.njk
examples/ui_elements/forms/text_input/index.xml.njk
examples/ui_elements/list/dismiss_keyboard_on_drag/index.xml.njk
examples/ui_elements/scroll_view/index.xml.njk
examples/ui_elements/sectionlist/dismiss_keyboard_on_drag/index.xml.njk
examples/ui_elements/text/escaped.xml.njk
examples/ui_elements/text/nested.xml.njk
examples/ui_elements/text/preformatted.xml.njk
examples/ui_elements/web_views/dispatch_event/index.xml.njk
package.json
scripts/format-njk.sh
scripts/format-xml.sh

Update CI to use [djhtml](https://github.com/rtts/djhtml) to indent our Nunjucks files.

chore: indent Nunjucks files

---

src/core/hyper-ref/index.tsx

Prevent `trigger="refresh"` adding scroll indicator if `shows-scroll-indicator="false"`

---

src/core/components/hv-route/index.tsx
src/services/navigator/helpers.ts

Includes:
- #810
- #811
QA Plan:
- Confirm normal navigation in both mobile apps
- Switching between tabs multiple times should not crash
- Navigating including pushing new screens and opening modals should not require more than one click
- Confirm normal deep link functionality in biz app
- including selecting the correct tab
QA testing in https://github.com/Instawork/mobile/pull/5875

chore: validate Hyperview fixes

---

examples/_includes/styles.xml.njk

image component can't accept a color style value

fix(style): Fix style issue

---

__mocks__/react-native-webview.ts
package.json
yarn.lock

Includes:
- https://github.com/Instawork/hyperview/commit/2d6720b259c49ef6b718962e802c8b9ba9133e43 Updated package references 
- https://github.com/Instawork/hyperview/commit/a29b221bed79a48d287a51722ea4a65ae111a635 run `yarn`
- https://github.com/Instawork/hyperview/pull/825/commits/42123d1402ef294fefc123ef3c64b9135addc35b Added a mock to allow tests to pass
Asana: https://app.asana.com/0/1204008699308084/1206627190414969/f
Testing completed in mobile: https://github.com/Instawork/mobile/pull/5890

chore: update react-native-webview

---

demo/package.json
demo/yarn.lock
package.json
yarn.lock

- [update package references](https://github.com/Instawork/hyperview/commit/7399f3375eb3a8ec650882338b34c5352fc60ebc)
- [run `yarn`](https://github.com/Instawork/hyperview/commit/2b0e6bb9bf0d31e47dd016a406ada49c98184d96)
- [update demo package](https://github.com/Instawork/hyperview/commit/df4ed06c7043b5f615cc0241e95a04a026ca457c)
- [run `yarn` on demo](https://github.com/Instawork/hyperview/commit/46ad79ed91ebda76eed17f7f70250c512e9f531a)
Asana: https://app.asana.com/0/0/1206718044236454/f
QA testing from mobile integration: https://github.com/Instawork/mobile/pull/5918
https://github.com/Instawork/hyperview/assets/127122858/dd8ed369-3b0b-4def-afaf-ce2155feb3b3

chore: update @react-native-community-datetimepicker

---

docs/guide_navigation.md
website/sidebars.json

- Adding the new guide to the sidebar in preparation for publish.
- Cleaned up unnecessary footnote references

chore (guide): add navigation guide to sidebar

---

website/blog/2024-05-14-Hyperview-Navigation.md

Creating a blog entry to provide links to resources around navigation.
Asana: https://app.asana.com/0/1204008699308084/1207305126869733/f

chore: add blog entry for Hyperview Navigation

---

schema/core.xsd
src/components/hv-web-view/index.tsx

Add allows-inline-media-playback prop to hyperview webview

feat(web-view): add `allows-inline-media-playback` prop

---

docs/reference_web.md
examples/ui_elements/web_views/show_loading_indicator/index.xml.njk

relates to : https://github.com/Instawork/hyperview/pull/872/files

Update WebView docs to reflect added show-loading-indicator attr

---

website/blog/2024-06-06-Hyperview-LogProvider.md

Providing a blog entry for the new logger functionality.

chore (blog): add a blog for logger

---

src/core/components/hv-screen/index.js
src/core/components/load-element-error/styles.ts

This reverts commit 4016ff2e2813700914450112ee7344eb529675b0.

Revert "fix (error component): error component is covering tabor (#871)"

---

src/services/render/index.tsx

Spreading the key-prop leads to annoying warnings in development. This PR explicitly sets the property.
Relevant react PR: https://github.com/facebook/react/pull/25697

fix(warning): explicitly set key instead prop spreading

---

demo/src/Components/HyperviewSvg.tsx

Chore (hyperview svg): add support for web version

---

docs/reference_behavior_share.md
src/behaviors/hv-share/index.ts
src/behaviors/hv-share/types.ts

share shoudl work with either URL or message
asana ticket: https://app.asana.com/0/1207348487265909/1207728676008502/f

fix: share behavior with only URL

---

examples/_includes/templates/base.xml.njk
examples/behaviors/basic/triggers/visible-once/index.xml.njk
examples/behaviors/basic/triggers/visible/index.xml.njk
examples/ui/styling/flex/index.xml.njk

asana: https://app.asana.com/0/1204008699308084/1207946003266059/f

hv-overhaul: misc fixes

---

.gitignore
.npmignore
.prettierignore
demo/.gitignore
demo/package.json

replacing it with demo/hyperview/

chore (demo app): Remove _examples_site/ folder from .ignore files

---

.circleci/config.yml

add deploy workflow to circleci

chore (demo app): add deploy workflow to circleci

---

demo/package.json
package.json
yarn.lock

- Remove `@faker-js/faker` from Hyperview dev deps
- Move `faker-js/faker` from demo deps to demo dev deps

chore: clean up `@faker-js/faker` package

---

demo/backend/advanced/community/elements/bottom-sheet/index.xml.njk
demo/schema/bottom-sheet.xsd
demo/schema/hyperview.xsd
demo/src/Components/BottomSheet/BottomSheet.tsx
demo/src/Components/BottomSheet/Overlay.tsx
demo/src/Components/BottomSheet/index.ts
demo/src/Components/BottomSheet/styles.ts
demo/src/Components/BottomSheet/types.ts
demo/src/Components/index.ts

Add simple bottom sheet component to demo app
https://github.com/user-attachments/assets/4ae24f26-20eb-4cd4-aa13-1014b1bdd282

feat(demo): Add BottomSheet component

---

demo/package.json
demo/webpack.config.js
demo/webpack.config.ts
demo/yarn.lock

An upcoming component will require tweaks to the web pack config. Migrating it to TS first to help future maintenance.

refactor(demo): migrate webpack config to TS

---

demo/.eleventyignore
demo/app.config.ts
demo/backend/advanced/community/elements/map/index.xml.njk
demo/backend/advanced/community/elements/map/styles.xml.njk
demo/package.json
demo/schema/hyperview.xsd
demo/schema/map.xsd
demo/src/Components/Map/Map.tsx
demo/src/Components/Map/MapMarker.tsx
demo/src/Components/Map/index.ts
demo/src/Components/Map/index.web.tsx
demo/src/Components/Map/types.ts
demo/src/Components/index.ts
demo/webpack.config.js
demo/webpack.config.ts
demo/yarn.lock

Import Instawork's Map / MapMarker components into the demo app.
See commits breakdown for details.
| iOS | Android | Web |
|---|---|---|
| ![Simulator Screenshot - iPhone 16 Pro - 2024-10-23 at 08 15 07](https://github.com/user-attachments/assets/4b01def0-d3f3-47a0-9baf-5fa22435237a) | <img width="543" alt="Screenshot 2024-10-23 at 8 17 32 AM" src="https://github.com/user-attachments/assets/d7c8ed22-55ab-4047-98ad-ad4c1413f3f3"> | <img width="706" alt="Screenshot 2024-10-23 at 10 14 33 AM" src="https://github.com/user-attachments/assets/98997ac9-ee4d-42fc-b243-ba1cfdea489a"> |

feat(demo): Map/MapMarker components

---

demo/.eleventyignore
demo/backend/advanced/community/elements/progress-bar/index.xml.njk
demo/backend/advanced/community/elements/progress-bar/progress-bar-0.xml.njk
demo/backend/advanced/community/elements/progress-bar/progress-bar-100.xml.njk
demo/backend/advanced/community/elements/progress-bar/progress-bar-25.xml.njk
demo/backend/advanced/community/elements/progress-bar/progress-bar-50.xml.njk
demo/backend/advanced/community/elements/progress-bar/progress-bar-75.xml.njk
demo/backend/advanced/community/elements/progress-bar/progress-bar.xml.njk
demo/backend/advanced/community/elements/progress-bar/styles.xml.njk
demo/schema/hyperview.xsd
demo/schema/progress-bar.xsd
demo/src/Components/ProgressBar/ProgressBar.tsx
demo/src/Components/ProgressBar/index.ts
demo/src/Components/index.ts

Import/tweak Instawork progress bar component
| iOS | Android | Web |
|--|--|--|
| ![iOS](https://github.com/user-attachments/assets/0c6c5525-28d7-41dc-b0f1-c39b78289d9f) | ![android](https://github.com/user-attachments/assets/2c51002f-01e4-485d-b596-a17bb654b6b6) | ![web](https://github.com/user-attachments/assets/bee5f78c-8d33-49ae-8ba6-f56572b48671) |

feat(demo): ProgressBar component

---

demo/backend/advanced/community/behaviors/add-styles/index.xml.njk
demo/schema/hyperview.xsd
demo/src/Behaviors/add-styles.ts
demo/src/Behaviors/index.ts

Add Instawork custom behavior used to inject styles in the current screen stylesheet
https://github.com/user-attachments/assets/b830c747-45d1-45f3-9456-c218f2549152

feat(demo): `add-styles` behavior action

---

website/blog/2024-11-14-What-s-new-in-Hyperview-0.68.md

Add blog post that highlights changes in 0.86

chore: 0.86 release blog post

---

demo/.eleventy.js
demo/package.json
demo/yarn.lock

Update 11ty to latest, and configure server to watch/rebuild changes live.

chore: update 11ty to 3.0 (latest)

---

demo/src/Components/Map/MapMarker.tsx

Web and mobile env need to import from a different package to properly render. It appears our component was only working correctly for web until this fix.
|----|----|
| <img width="1358" alt="Screenshot 2025-01-15 at 5 35 24 PM" src="https://github.com/user-attachments/assets/0b63db21-d1fd-473b-85c7-0e5b23b7acc5" /> | <img width="1356" alt="Screenshot 2025-01-15 at 5 33 22 PM" src="https://github.com/user-attachments/assets/0d6cf564-17f1-4d36-aaf4-d4d02a6afc06" /> |

fix(demo): conditionally render map-marker for web

---

demo/backend/advanced/case-studies/content.xml.njk
demo/backend/advanced/community/content.xml.njk
demo/backend/behaviors/advanced/content.xml.njk
demo/backend/behaviors/basic/content.xml.njk
demo/backend/navigation/behaviors/content.xml.njk
demo/backend/navigation/navigator/content.xml.njk
demo/backend/ui/styling/content.xml.njk
demo/backend/ui/ui-elements/content.xml.njk

Set the `list_href` variable for each of these screens, to restore pull to refresh functionality
https://github.com/user-attachments/assets/dd31e52b-8e42-4da1-aa1d-8ba80b0d79eb
https://app.asana.com/0/1205761271270033/1209017355656027/f

fix(demo): pull to refresh on main lists

---

demo/backend/behaviors/basic/actions/select-all/_indicator/index.xml.njk
demo/backend/behaviors/basic/actions/unselect-all/_indicator/index.xml.njk

Resolving spinner alignment on "select all" and "unselect all" demos
| -- | -- |
| ![before](https://github.com/user-attachments/assets/a5ebb5fb-70bb-4448-aecf-b9ab939d19a1) | ![after](https://github.com/user-attachments/assets/65f83827-4689-4dea-86c9-7a149c59e409) |
[Asana](https://app.asana.com/0/1205761271270033/1209182447962496/f)

chore(demo): fix alignment on select-all

---

demo/backend/behaviors/basic/actions/append/_nested/index.xml.njk
demo/backend/behaviors/basic/actions/prepend/_prepend-nested/index.xml.njk

Removing the lorem ipsom example from append and prepend.
[Asana](https://app.asana.com/0/1205761271270033/1209182447962493/f)

chore(demo): append/prepend - remove unwanted text

---

demo/backend/_includes/templates/styles.xml.njk
demo/backend/ui/ui-elements/web-view/dispatch-event/append.xml
demo/backend/ui/ui-elements/web-view/dispatch-event/index.xml.njk
demo/backend/ui/ui-elements/web-view/html/index.xml.njk
demo/backend/ui/ui-elements/web-view/injected-js/index.xml.njk
demo/backend/ui/ui-elements/web-view/loading/index.xml.njk
demo/backend/ui/ui-elements/web-view/url/index.xml.njk

Fix a few visual bugs/issues with webview examples
https://app.asana.com/0/1205761271270033/1209182447962492/f
https://github.com/user-attachments/assets/27b7f8e4-a7ed-45fa-bdd6-cd6da74b27d0

fix(demo): webview UI tweaks

---

demo/backend/_includes/templates/styles.xml.njk
demo/backend/behaviors/advanced/scroll/list/_list-content.xml.njk
demo/backend/behaviors/advanced/scroll/list/index.xml.njk
demo/backend/behaviors/advanced/scroll/section-list/_section-list-content.xml.njk
demo/backend/behaviors/advanced/scroll/section-list/index.xml.njk
demo/backend/behaviors/advanced/set-value/index.xml.njk

Various fixes to restore functionality and UI bugs.
https://app.asana.com/0/1204008699308084/1209182447962501/f
https://github.com/user-attachments/assets/c3f2d0d1-72db-445c-bc23-ed48dd596892

fix(demo): Behavior > Advanced > Scroll

---

src/components/hv-section-list/index.tsx

Apply same fix as done in #793.
See demo fixed in #1038

fix(section-list): scroll to target

---

src/core/components/hv-screen/index.js

Resolving two locations which weren't renamed in https://github.com/Instawork/hyperview/pull/1042

fix(loading screen): rename remove method

---

demo/backend/navigation/behaviors/actions/push/index.xml.njk

Remove delays in the push examples
[Asana](https://app.asana.com/0/1205761271270033/1209182447962508/f)

fix(demo): `navigation/push` examples issues

---

demo/backend/behaviors/advanced/dispatch/index.xml.njk
demo/backend/behaviors/advanced/dispatch/source-screen.xml.njk

Adjust text and behaviors to make the example more clear.
https://app.asana.com/0/1204008699308084/1209182447962500/f

fix(demo): Behaviors > Advanced > Dispatch Event

---

demo/backend/navigation/navigator/stack/modal-1.xml.njk
demo/backend/navigation/navigator/stack/screen.xml.njk

Update button name from "Push" to "New"
Use a close button instead of a back button
| Stack | Modal |
| -- | -- |
| ![screen](https://github.com/user-attachments/assets/fa54d203-62f4-4ec3-8df2-5c40adfd521d) | ![modal](https://github.com/user-attachments/assets/5b40486a-1cfe-47ce-928a-fcd409a76b0b) |
[Asana](https://app.asana.com/0/1205761271270033/1209182447962510/f)

fix(demo): navigation/stack examples issues

---

demo/backend/advanced/case-studies/contacts/_contacts.xml.njk
demo/backend/advanced/case-studies/contacts/_list.xml.njk
demo/backend/advanced/case-studies/contacts/index.xml.js
demo/backend/advanced/case-studies/contacts/index.xml.njk

Fix incorrect include paths, and make template without permalink private
https://app.asana.com/0/1205761271270033/1209182447962511/f
https://github.com/user-attachments/assets/a7b9e471-67ff-42f5-ba05-a6124abf5405

fix(demo): Contacts case study

---

demo/backend/navigation/behaviors/actions/modal/index.xml.njk
demo/backend/navigation/behaviors/actions/modal/modal-1.xml.njk
demo/backend/navigation/behaviors/actions/modal/push-1.xml.njk
demo/backend/navigation/behaviors/actions/modal/push-2.xml.njk
demo/backend/navigation/navigator/stack/modal-1.xml.njk
demo/backend/navigation/navigator/stack/modal-2.xml.njk
demo/backend/navigation/navigator/stack/push-1.xml.njk
demo/backend/navigation/navigator/stack/push-2.xml.njk

- remove delays
- fix language for modal and push screens (globally)
- adding example modal and push screens to resolve infinite loop and top button type
https://github.com/user-attachments/assets/3c6f5404-7683-4e51-9f8d-bfdfce3f3007
[Asana](https://app.asana.com/0/1205761271270033/1209182447962504/f)

fix(demo): navigation/modal examples issues

---

demo/backend/behaviors/basic/actions/show/index.xml.njk
demo/backend/behaviors/basic/actions/show/spinner/_styles.xml.njk

Fix alignment of spinner.
| -- | -- |
| ![before](https://github.com/user-attachments/assets/17273136-9deb-4b41-8f0a-8185895664e4) | ![after](https://github.com/user-attachments/assets/2d5b9986-10ea-4a48-95b4-8305b245742f) |
[Asana](https://app.asana.com/0/1205761271270033/1209398835826109)

fix(demo): show behavior spinner alignment

---

demo/package.json
demo/yarn.lock

Without this package, the app will not compile correctly.

fix(demo): explicitly install @tsconfig/react-native

---

demo/README.md

Updating docs to indicate the current maximum `node` version.
[Asana](https://app.asana.com/0/1204008699308084/1209425378622141)

chore(readme): update docs with node version

---

demo/package.json

This is a current workaround for #1090

fix(demo): set node version in package.json

---

docs/reference_form.md

See comment: https://github.com/Instawork/hyperview/issues/1086#issuecomment-2688326787.

fix(docs): add missing action attribute

---

demo/src/Components/BottomSheet/BottomSheet.tsx

https://app.asana.com/0/1204008699308084/1209597751462372
Before: 
https://github.com/user-attachments/assets/c729714f-e318-490c-b873-14ec8949cb89
After: 
https://github.com/user-attachments/assets/805cb5e2-b8bf-4804-b4ec-e760fa446ce2

Speed up bottom sheet animation

---

demo/backend/advanced/community/elements/bottom-sheet/index.xml.njk
demo/src/Components/BottomSheet/BottomSheet.tsx
demo/src/Components/BottomSheet/styles.ts

update bottom sheet designs

---

schema/core.xsd

The logic to support this was added previously.

chore(web-view): Add definition for new attribute

---

demo/backend/advanced/community/elements/bottom-sheet/_scrolling/index.xml.njk
demo/backend/advanced/community/elements/bottom-sheet/_users/index.xml.njk
demo/backend/advanced/community/elements/bottom-sheet/_users/styles.xml.njk
demo/src/Components/BottomSheet/BottomSheet.tsx

https://app.asana.com/0/1204008699308084/1209345465762699
iOS:
| -- | -- |
| ![before](https://github.com/user-attachments/assets/3b17eea9-2bd1-4610-aa28-d809905ab763) | ![after](https://github.com/user-attachments/assets/f267b039-1eaa-499c-ad76-1df1a743ed2b) |
Android: 
| -- | -- |
| ![before](https://github.com/user-attachments/assets/67ad8c35-71d6-4002-b992-a338d1f2f840) | ![after](https://github.com/user-attachments/assets/e6cec848-72a8-483b-8690-4303434105f7) |

Fix(bottom-sheet): Bottom sheet with scroll view - bottom of the list not reachable

---

src/core/components/hv-doc/context.ts
src/core/components/hv-doc/index.tsx
src/core/components/hv-doc/types.ts
src/core/components/hv-route/index.tsx
src/core/components/hv-route/types.ts
src/core/components/hv-screen/index.js
src/core/components/hv-screen/types.ts

Created a new `hv-doc` component. Lift the state and this.doc out of both `hv-route` and `hv-screen` into instances of `hv-doc`.
[Asana](https://app.asana.com/0/1204008699308084/1209669995625339/f)

chore(hv-doc): create component and lift state

---

docs/example_navigation.md

Improving explanation of navigation configuration.
[Asana](https://app.asana.com/0/1204008699308084/1209500497806764/f)

chore(docs): clarify navigation setup

---

src/core/components/hv-route/index.tsx

Memoize the doc clone in `hv-doc` implementation. Relates to https://github.com/Instawork/hyperview/pull/1131
[Asana](https://app.asana.com/0/1204008699308084/1209815225223632/f)

chore(hv-doc): memoize doc cloning

---

src/contexts/back-behaviors.tsx
src/contexts/element-cache.tsx

Adding a few missing conversions.

chore(performance): memoize context values (additional)

---

src/core/components/hv-doc/context.ts
src/core/components/hv-doc/index.tsx
src/core/components/hv-doc/types.ts
src/core/components/hv-route/index.tsx
src/core/components/hv-route/types.ts
src/core/components/hv-screen/index.js
src/core/components/hv-screen/types.ts

Lifting and centralizing the onUpdate handling from `hv-route` and `hv-screen`.
[Asana](https://app.asana.com/0/1204008699308084/1209864080706785/f)

chore(hv-doc): lift onUpdate function into hv-doc

---

README.md
package.json
yarn.lock

Update peer & dev dependencies to match latest used in demo app.

chore: fix peer/dev dependencies

---

.cursor/rules/documentation.mdc

Created a rule to help enforce documentation for components and behaviors
- provided @Doc references to the online Hyperview documentation
- Created some basic rules around how documents are structured and named
[Asana](https://app.asana.com/1/47184964732898/project/1204008699308084/task/1209951481204334?focus=true)

chore(cursor): create rule for documentation

---

src/core/components/hv-route/index.tsx

Removing an unneeded extra element in the route component hierarchy.

chore: simplify route hierarchy

---

src/core/components/hv-doc/context.ts
src/core/components/hv-doc/index.tsx
src/core/components/hv-doc/types.ts
src/core/components/hv-root/index.tsx
src/core/components/hv-route/index.tsx
src/core/components/hv-route/types.ts
src/core/components/hv-screen/index.js
src/core/components/hv-screen/types.ts
src/types.ts

Integration of the following:
- https://github.com/Instawork/hyperview/pull/1156
- https://github.com/Instawork/hyperview/pull/1158
- https://github.com/Instawork/hyperview/pull/1160
- https://github.com/Instawork/hyperview/pull/1163
- https://github.com/Instawork/hyperview/pull/1166
QA to be performed in https://github.com/Instawork/mobile/pull/7407
[Asana](https://app.asana.com/1/47184964732898/project/1204008699308084/task/1209875001265860?focus=true)

chore(hv-doc): reduce redundant code

---

src/core/components/hv-element/index.tsx

chore(hv-element): safety null check

---

src/elements/hv-text/index.tsx

Convert `hv-text` to Functional Component. Confirm no degradation in render count.
[Asana](https://app.asana.com/1/47184964732898/project/1204008699308084/task/1210601789543021?focus=true)

chore(text): convert to Functional Component

---

src/elements/hv-select-multiple/index.tsx

Convert `hv-select-multiple` to Functional Component. Confirm no degradation in render count.
[Asana](https://app.asana.com/1/47184964732898/project/1204008699308084/task/1210601789543017?focus=true)

chore(select-multiple): convert to Functional Component

---

src/elements/hv-section-list/index.tsx
src/elements/hv-section-list/types.ts

Converting `hv-section-list` to functional component.
[Asana](https://app.asana.com/1/47184964732898/project/1204008699308084/task/1210601791104907?focus=true)

chore(hv-section-list): convert to FC

---

src/elements/hv-doc/hv-doc.tsx
src/elements/hv-doc/types.ts
src/elements/hv-image/index.tsx
src/elements/hv-navigator/index.tsx
src/elements/hv-text/index.tsx

To improve render performance, replace instances of sub-components with direct implementation in the return value.
[Asana](https://app.asana.com/1/47184964732898/project/1204008699308084/task/1210645183157618?focus=true)

chore: remove sub-components

---

demo/backend/_includes/templates/header.xml.njk
demo/backend/advanced/community/elements/bottom-tabbar/tab-bar.xml.njk
demo/backend/advanced/community/elements/nav-back/screen.xml.njk
demo/backend/advanced/community/elements/scroll-opacity/index.xml.njk

Add the safe-area wrapper on a couple of demo screens.

fix(demo): missing safe area on some screens

---

__mocks__/react-native-gesture-handler.ts
__mocks__/react-native-safe-area-context.ts
src/hyperview.test.tsx
test/helpers/fetch.ts

Providing testing around the `replace` and `reload` actions including regression tests for fixes made in
- https://github.com/Instawork/hyperview/pull/1068
- https://github.com/Instawork/hyperview/pull/1231
- https://github.com/Instawork/hyperview/pull/1225
[Asana](https://app.asana.com/1/47184964732898/project/1204008699308084/task/1210728994298056?focus=true)

chore(loading): add testing for reload behavior issue

---

website/blog/2025-08-01-Out-with-the-old.md

Creating a new blog entry to encapsulate some of our recent improvements.
[Asana](https://app.asana.com/1/47184964732898/project/1204008699308084/task/1210801072249428?focus=true)
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1210801072249428

chore: create new blog entry

---

schema/core.xsd

Re-add fields to schema after these were added in #1249 but reverted in #1250

chore: add RN fields to text-field schema

---

src/components/keyboard-aware-scroll-view/types.ts
src/components/loading/loading.tsx
src/components/navigator-stack/helpers.test.ts
src/components/navigator-stack/helpers.ts
src/components/navigator-stack/router.tsx
src/components/navigator-stack/types.ts
src/contexts/back-behaviors/context.tsx
src/contexts/back-behaviors/types.ts
src/contexts/hyperview/context.tsx
src/elements/hv-doc/context.tsx
src/elements/hv-doc/hv-doc.tsx
src/elements/hv-doc/types.ts
src/elements/hv-image/index.tsx
src/elements/hv-route/types.ts
src/elements/hv-screen/types.ts

Fix imports to use "type" for types
[Asana](https://app.asana.com/1/47184964732898/task/1211524780184715)
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1211524780184715

chore(types): clarify type imports
