.babelrc, .gitignore, examples/advanced_behaviors/alert.xml, examples/advanced_behaviors/alert/behavior.xml, examples/advanced_behaviors/alert/index.xml, examples/advanced_behaviors/alert/multiple_behaviors.xml, examples/advanced_behaviors/alert/options.xml, examples/advanced_behaviors/index.xml, src/index.js, src/services/namespaces/index.js
[TAD](https://instawork.atlassian.net/wiki/spaces/EN/pages/794001412/Proposal+Alert+element)
Added support for "alert" behaviors. These behaviors describe the alert options as `<alert:option>` elements, that can then contain behaviors that trigger when the user presses the option:
```xml
<view style="Button">
<behavior
trigger="press"
action="alert"
alert:title="Alert title"
alert:message="Alert message"
>
<alert:option alert:label="Push" trigger="press" href="/index.xml" action="push" />
<alert:option alert:label="Back" trigger="press" href="#" action="back" />
<alert:option alert:label="Cancel" />
</behavior>
<text style="Button__Label">Navigation options</text>
</view>
```
=> Add support for system alerts

src/index.js, src/services/render/index.js, src/types.js
Asana: https://app.asana.com/0/518926233438259/1106456911336594/f
To help with debugging, we show a console warning if Hyperview encounters an unsupported tag or action. Rendering and triggers will skip the unsupported tags and actions as before.
As part of the change, I also added more explicit guards in the render code to check for comment nodes, text nodes, and element nodes.
=> Warn when encountering unsupported tags or behaviors in XML

src/index.js
https://app.asana.com/0/518926233438259/1106456911336593/f
When parsing a screen, show errors if the XML does not parse correctly. In addition, show errors if the XML is missing `<doc>`, `<screen>`, or `<body>` tags. These errors show the default error screen that allows the screen to be reloaded, allowing faster iteration.
=> Show helpful XML parse errors

.gitignore, docs/reference_behavior.md
The "behavior attributes" link was broken at https://hyperview.org/docs/reference_behavior#behavior-attributes
This PR fixes it.
=> Fix link to reference_behavior_attributes

README.md, demo/yarn.lock, package.json
With this PR we can develop hyperview features in watch mode. Changes in src should directly get reflected in the demo app with the `build:demo` command running. This also saves us from the "duplicate modules" error which happens if we're using `yarn link`.
Also updated readme.
=> infra: add hyperview watch mode for demo app

demo/package.json, demo/yarn.lock
Current setup assumes that expo-cli is installed globally. Provide it as a dependency of the demo app instead.
=> Fix: Add expo-cli to demo app

package.json, scripts/build-demo/index.js, yarn.lock
`yarn build:demo` now copies the content of `src/` into the demo app hyperview dependency module, and runs a watcher. This enables the developer to see the actual source code instead of the minified version when attaching to debugger
=> Infra: iterate on the build:demo command

README.md, demo/package.json, demo/yarn.lock, scripts/build-demo/index.js
- Demo app: revert back to using the latest version of hyperview on NPM (prevents running into `@providesModule naming collision` issue)
- `build:demo` command: Simplify output, remove unecessary initial sync (already handled by chokidar watcher)
- Improve README for clarity
https://app.asana.com/0/923014529014430/1114001676407597/f
=> Infra: improve build:demo command

README.md, package.json, scripts/sync/index.js
Rename `build-demo` script to `sync`, and add ability to specify the path where to perform sync.
=> Tools: `yarn build:demo` -> `yarn sync [path]`

scripts/sync/index.js
Specify full destination directory path with trailing slash to rsync command to ensure files are copied to the correct location.
=> Fix: Sync script

src/index.js
Replace `startsWith` string function call (unsupported on some Android versions) with simple "char at index 0" comparison.
https://app.asana.com/0/244065166232575/1116714831280745/f
=> Fix: Handle `href` starting with `#` correctly on Android

src/behaviors/hv-share/index.js, src/behaviors/hv-share/types.js
Allow both title and url to be optional - but leave message as non-optional. It appears that [the flow type definition](https://github.com/facebook/react-native/blob/67e7f16944530aa0d1a4d375b0de5efd5c432865/Libraries/Share/Share.js#L20-L22) for RN `Share.share` is incorrect, as the backing [objective-c class is trying to read both `message` and `url` keys](https://github.com/facebook/react-native/blob/67e7f16944530aa0d1a4d375b0de5efd5c432865/Libraries/ActionSheetIOS/RCTActionSheetManager.m#L128-L132) of the `content` object.
Fixes https://app.asana.com/0/244065166232575/1116739059560742/f
=> Fix: Share behavior

src/services/render/index.js
Add warnings when trying to render an element that is either missing its `namespaceURI` or `localName` props.
Relates to https://github.com/Instawork/instawork/pull/5433
=> More warnings when parsing fails

src/services/render/index.js
This allows using white-spaces to format source code without affecting rendering and brings Hyperview parsing behavior closer to [HTML whitespace spec](https://www.w3.org/TR/REC-html40/struct/text.html#h-9.1).
For example:
```xml
<text>
Velit voluptas et alias atque provident sapiente consequuntur deserunt.
Dolorem et non error dolorem voluptate amet accusantium. Corporis rerum
sed labore quae sed qui quis quasi. Illo pariatur sint qui. Quasi quaerat id molestias.
Necessitatibus et ipsa quia asperiores laborum neque. Quisquam dolorem consequatur illum.
Ut magni iusto explicabo blanditiis quasi laborum incidunt earum. Eius ut in rerum ipsam.
Officiis dolores suscipit consequatur placeat commodi eum. Vel possimus placeat aut eos
tempore saepe. Esse assumenda eum illo sed aut earum quia …
```
=> Feature: collapse multiple whitespaces within text nodes.

src/index.js
This allows to use the root Hyperview component in a context that is not aware of react-navigation. For now, the implementation consist in defaulting the `params` property to an object so that code accessing keys without checking existance first does not crash. This should be better addressed with added typing when refactoring the component in https://app.asana.com/0/923014529014430/933532962114370/f.
=> Make navigation prop optional

src/index.js
Fix a crash where `delay` attribute would not longer work as `later` helper was not correctly imported
=> Fix: later is not defined

docs/reference_style.md, examples/styling/button.xml, examples/styling/index.xml, examples/styling/shadows.xml, src/services/stylesheets/index.js
Add support for shadow attributes to the `<style>` element. It works with modifiers so that shadow can change on pushed buttons:
```
<style id="Button--Shadow"
shadowColor="black"
shadowOffsetX="0"
shadowOffsetY="4"
shadowOpacity="0.5"
shadowRadius="4"
>
<modifier pressed="true">
<style shadowOffsetY="1" shadowRadius="1" />
</modifier>
</style>
```
Screenshot:
All available style attributes:
=> Add shadow support to Hyperview

src/index.js, src/services/index.js, src/services/navigation/index.js, src/services/url/index.js, src/services/url/index.test.js
Correctly generate URL when form method is `GET` and url already contains query params. Also extract URL code into a separate/tested module.
=> Fix: Form with GET methods and pre-existing query string params bug

docs/reference_style.md, examples/styling/button.xml, examples/styling/elevation.xml, examples/styling/index.xml, src/services/stylesheets/index.js
In a previous PR I added shadow support for iOS. This is not supported on Android, so instead I exposed the elevation style property. Also:
- updated examples to include elevation
- updated docs on website
=> Add elevation support to Hyperview

demo/app.json, demo/package.json, demo/yarn.lock, package.json
Now that our apps are using RN 0.59, I'm increasing the minimum peer deps for hyperview, and I'm upgrading the demo app to Expo 33.
The motivation is to require versions of React that support the new Context API, which we want to start using for features including the forthcoming date picker.
For QA: I tested every single screen in the demo app for correct functionality.
=> Bump React dependencies for Hyperview and demo app

src/behaviors/hv-share/index.js
[Bug](https://app.asana.com/0/378088913887644/1132648377334187/f)
`url` is not supported on Android. Thus, we concatenate the url portion to the message on android. 
See: https://facebook.github.io/react-native/docs/share
Android9
iPhone
https://drive.google.com/file/d/1bnN49DJHtxv_boNW-r80mzhPHRXDu0XM/view?usp=sharing
=> Fixed share content on android

website/blog/2019-08-01-Events-in-Hyperview.md
I wrote a blog to introduce the team to using events. Any feedback or suggestions?
Relates to #81
=> Blog: element dependency with events

examples/behaviors/hide.xml, examples/behaviors/index.xml, examples/behaviors/show.xml, src/behaviors/hv-hide/index.js, src/behaviors/hv-show/index.js, src/services/behaviors/index.js
Similar to #90 , this PR adds `hide` and `show` actions that will hide or show elements on a screen. Unlike `toggle`, it will only perform one or the other.
The new actions also works with conventional behavior attributes like delay, show-during-load, hide-during-load. Note that showing/hiding indicators will only work if delay is non-zero.
=> Implement "show" and "hide" actions

src/services/url/index.js, src/services/url/index.test.js
I discovered a quirk of the `url-parse` library: the default url parser does not preserve duplicate query params: https://github.com/unshiftio/url-parse/issues/163
This breaks URL passing in our app. In this case, the fix is to tell the library not to parse the query string. Added a regression test.
=> Preserve multiple query params when constructing URLs

demo/app.json, demo/package.json, demo/yarn.lock, docs/reference_behavior_attributes.md, docs/reference_form.md, examples/navigation/close.xml, examples/navigation/new.xml, examples/navigation/push.xml, examples/navigation/reload.xml, examples/styling/button.xml, src/core/hyper-ref/index.js, src/index.js, src/services/index.js, src/services/navigation/index.js, src/services/url/index.js, src/services/url/types.js
Implemented some missing features needed for the HV gigs list experiment. These are mostly to support interactions with the gigs filter modal:
1. Navigation actions will now serialize form data. If a navigation behavior triggers from within a `<form>`, the form data will be included as query params. Use case: apply filters to a screen via a modal:
```xml
<form>
<date-field name="min-date" value="2019-05-06" />
<text action="close" href="/gigs">Save</text>
</form>
```
When the user taps save, the modal will close and the previous screen will reload with contents from `/gigs?min-date=2019-05-06`.
2. The `reload` action can take an `href` attribute. This will cause the screen to reload with the response from the given href, rather than from the original URL of the screen. Use case: clear the …
=> Navigation tweaks: support form data for navigation and reloads

examples/advanced_behaviors/index.xml, examples/advanced_behaviors/set_value/index.xml, src/behaviors/hv-hide/index.js, src/behaviors/hv-set-value/index.js, src/behaviors/hv-show/index.js, src/behaviors/hv-toggle/index.js, src/components/hv-date-field/index.js, src/components/hv-date-field/stories/basic.xml, src/components/hv-date-field/stories/index.js, src/components/hv-picker-field/index.js, src/components/hv-select-single/index.js, src/components/hv-switch/index.js, src/components/hv-switch/stories/basic.xml, src/components/hv-switch/stories/index.js, src/components/hv-text-area/index.js, src/components/hv-text-field/index.js, src/core/hyper-ref/index.js, src/services/behaviors/index.js, storybook/stories.gen.js, storybook/templates.gen.js
[Asana task](https://app.asana.com/0/923014529014430/1143376661956577/f)
Proof of concept of a new `set-value` action that allows settings form input values via a behavior. Example syntax:
`<behavior action="set-value" target="myDateField" value="new value" />`
When this behavior triggers, it will set the text field with id `myDateField` to `new value`.
I've implemented support for this behavior in `<text-field>`, `<text-area>`, `<picker-field>`, `<date-field>`, and `<select-single>`. Need to add `<select-multiple>` and `<switch>`.
**NOTE**: In order to get this feature working, I needed to update the component state in `componentDidUpdate` by reading the attributes in the `element` prop. This is against our eslint rules which I slienced for now. To properly address this issue, the input …
=> Implement set-value behavior for form inputs

docs/reference_behavior_attributes.md
@danielleknudson noticed our docs were missing some new behavior actions:
- `show`
- `hide`
- `toggle`
- `set-value`
I've update the behavior attributes page to explain these, with examples and links to the repo.
=> Update docs with new behavior actions

src/index.js, src/services/navigation/index.js
Default `href` to `#` when attribute not set, so that navigation service does not try to load a different URL.
https://app.asana.com/0/244065166232575/1153051694506464/f
=> Fix: action="close" / action="back" behavior causing incorrect reload

examples/ui_elements/forms/date_field.xml, src/components/hv-date-field/index.js
[Asana task](https://app.asana.com/0/406825428187110/1153389465437105/f)
Expose a `mode` attribute for `date-field` element which passes on the options to `DatePickerAndroid.open` method.
| Default (calendar) mode | Spinner mode |
| - | - |
| ![Screenshot_1576577574](https://user-images.githubusercontent.com/6682655/70987181-66a65d80-20e5-11ea-8bea-824776f7c21f.png) | ![Screenshot_1576577577](https://user-images.githubusercontent.com/6682655/70987204-6efe9880-20e5-11ea-87d7-970d65923162.png) |
=> Feature: Add spinner mode in date-field

src/index.js
Fix import style for `ANCHOR_ID_SEPARATOR`.
Relates to #109, fixes https://app.asana.com/0/491474088351836/1155782377506746/f
=> Follow up fix for #109

src/core/hyper-ref/index.js, src/index.js, src/services/events/index.js
Extract out event dispatcher/listener code into a dedicated service, and expose it as part of the public API.
Relates to https://app.asana.com/0/244065166232575/1158603120086761/f
=> Expose events API

docs/reference_view.md, src/components/hv-view/index.js, src/components/hv-view/types.js
Set `scrollToInputAdditionalOffset` prop of [`react-native-keyboard-aware-scrollview`](https://github.com/wix/react-native-keyboard-aware-scrollview). We were previously setting the prop `extraScrollHeight`, which is a prop of the module [`react-native-keyboard-aware-scroll-view`](https://github.com/APSL/react-native-keyboard-aware-scroll-view#readme)
Also allow overriding the default value of `120` with the prop `scroll-to-input-offset`
https://app.asana.com/0/987416201877098/1158164359079221/f
=> Fix: keyboard avoiding view prop

src/components/hv-list/index.js, src/components/hv-section-list/index.js
Prevent list from rendering duplicated items by filtering item that match parent list/section
Given following markup:
```xml
<section-list>
<section>
<section-title>
<text style="h6">Section 1</text>
</section-title>
<item>
<text style="b3">Item 1-1</text>
<list>
<item style="mx-24"><text style="b3">Item 1-1-1</text></item>
<item style="mx-24"><text style="b3">Item 1-1-2</text></item>
<item style="mx-24"><text style="b3">Item 1-1-3</text></item>
</list>
</item>
<item><text style="b3">Item 1-2</text></item>
<item><text style="b3">Item 1-3</text></item>
</section>
<section>
<section-title>
<text style="h6">Section 2</text>
</section-title>
<item><text style="b3">Item 2-1</text></item>
</section>
</section-list>
```
|--------|------|
| <img width="117" alt="Screen Shot …
=> Fix: Nested lists

src/components/hv-list/index.js, src/components/hv-section-list/index.js
Reverts Instawork/hyperview#131
This seemed to cause issues in a couple of places where a view wraps items, i.e.
```xml
<list>
<view>
<item>foo</item>
<item>bar</item>
</view>
</list>
```
[the spec](https://hyperview.org/docs/reference_list) doesn't mention anything on this topic, and it's unclear whether wrapping view should be a supported feature - if so we might need to find a different way to fix the original issue.
cc @adamstep for input
=> Revert "Fix: Nested lists"

src/index.js
required for React Native Upgrade to 0.61.x
=> mark deprecated method as UNSAFE_

examples/advanced_behaviors/alert/behavior.xml, examples/advanced_behaviors/set_value/index.xml, examples/case_studies/_rating_save.xml, examples/case_studies/business_rating.xml, examples/case_studies/feedback_widget.xml, examples/case_studies/photos/index.xml, examples/case_studies/rating_modal.xml, examples/ui_elements/forms/date_field.xml, examples/ui_elements/forms/picker.xml, examples/ui_elements/forms/switch.xml, examples/ui_elements/forms/text_input.xml, examples/ui_elements/forms/textarea.xml, package.json, schema/alert.xsd, schema/amplitude.xsd, schema/hyperview.xsd, schema/intercom.xsd, schema/phone.xsd, schema/redux.xsd, schema/share.xsd, schema/sms.xsd
Adding an XML schema for Hyperview that can be used for validation, docs generation, IDE tools, etc.
- The schema files live under the `schema/` directory. `hyperview.xsd` is the main schema, and it imports other schemas for the various namespaces we use.
- I added a command `yarn test:validate-xml` that validates the schema against the XML files under `examples/`.
- I fixed up the examples that contained easy-to-fix issues like wrong namespaces, missing attributes, etc.
However, some examples cannot be validated due to an issue in the Hyperview spec. The schema revealed a conflict between two features:
- Many elements like `<option>` use the attribute `value` to hold the input value.
- The `set-value` behavior uses the attribute `value` to update any input element.
This means that an …
=> Hyperview XML Schema

docs/reference_behavior_attributes.md, examples/advanced_behaviors/set_value/index.xml, schema/hyperview.xsd, src/behaviors/hv-set-value/index.js
The attribute `value` had two interpretations on some elements: it could represent the current value of an input element, or the value to set with a `set-value` behavior.
This ambiguity could lead to bugs, and it prevented us from having a complete XML schema. To resolve the ambiguity, I renamed the attribute used by the behavior to `new-value`.
I will release a new minor version with this fix, and then update our backend to use `new-value` instead of `value` with this or newer versions of the client.
=> Rename ambiguous "value" attribute in "set-value" behavior

examples/styling/text.xml, schema/hyperview.xsd
https://app.asana.com/0/1173541402094433/1173541402094452/f
This PR makes improvements to the schema by adding stricter/more complete types for attributes:
- `trigger` is now an enum of allowed strings
- `event-name` is now an NCName (string with no colons or whitespace)
- `show-during-load` and `hide-during-load` are now space-separated NCNames
- colors support `hsl` and `hsla`.
=> Use stricter attribute checks in Schema

demo/screens/HyperviewScreen.js, docs/reference_behavior_attributes.md, package.json, src/index.js, src/services/dom/errors.js, src/services/dom/index.js, src/services/dom/index.test.js, src/services/dom/types.js, test/setup.js
Goals of this code change:
- centralize code that loads remote content, currently spread out between `load` and `fetchElement`
- use async/await style instead of chained promise to ease readability and avoid variable mutations
- in a future PR, have a better handling for error responses that can containt non-xml content type (i.e. Django errors responses are text/html)
- more tests and flow coverage (src/index.js is explicitely ignored by linters as it contains too many issues)
Regarding the naming of the service, I choose `dom` even if right now it has little to do with DOM manipulation. The reasoning is to have a common place for abstractions of the `xmldom` module, and the goal would be to eventually move most of the DOM helpers currently living in [src/services/index.js (currently …
=> Extract XML fetching code in its own service

docs/reference_text.md, examples/ui_elements/text.xml, schema/hyperview.xsd, src/services/index.js
This is to be used on `<text>` elements and allow user selection on long press.
Relates to https://app.asana.com/0/518926233438259/1155044724972251/f
=> Allow selectable="true" attribute

package.json, src/components/hv-web-view/index.js, yarn.lock
- Update `react-native-webview` to `9.4.0`
- Set `onMessage` to no-op to preserve `injectedJavaScript` functionality (as [not-so-well documented here](https://github.com/react-native-community/react-native-webview/issues/1311))
=> Update react-native-webview to latest

schema/hyperview.xsd
Some improvements to the Hyperview schema. I discovered these while running validation against the unit tests in our backend:
- Allow attributes from other namespaces on the `<doc>` element. This is needed to support `xsi:schemaLocation` and other XML-related attributes.
- Allow any elements from other namespaces in the `<view>` element. This is needed to support embedded `<svg>` and custom elements.
- Add `transparent` as a supported named color.
- Support `verb` as a behavior attribute.
=> Hyperview schema: allow custom elements

docs/example_basic_form.md, docs/example_instawork.md, docs/reference_form.md, schema/hyperview.xsd, src/services/dom/index.test.js, src/services/dom/types.js
Only accept `get` and `post` verbs from XML markup, and update every examples.
=> Lowercase HTTP verbs

src/components/hv-web-view/index.js
Apply `StyleSheet.absoluteFillObject` to loading indicator, so that it occupies the whole screen.
=> Webview: apply correct style to loading indicator

src/index.js, src/services/navigation/index.js
Add `doc` instance property to `HyperviewScreen`, and update it at the same time as `state.doc`. When accessing the DOM for read/write operation, use `doc` / use `state.doc` when rendering. Also simplify `Navigation` constructor.
=> Fix: Doc state

website/build-schema.sh, website/package.json
Asana task: https://app.asana.com/0/1173541402094433/1173541402094466/f
Changes to the website deploy script will also publish the Hyperview schema files. The deployment process will change the local references to "https://hyperview.org/schema/".
=> Publish Hyperview schema

src/core/components/load-error/index.js
Apply conversion suggested [here](https://stackoverflow.com/a/33140101/237637) to resolve an issue with `btoa()` and UTF8 chars.
|--------|------|
| <img width="584" alt="Screen Shot 2020-06-02 at 1 35 51 PM" src="https://user-images.githubusercontent.com/309515/83567358-54bf4800-a4d6-11ea-8d68-3707b35ad9af.png"> | <img width="584" alt="Screen Shot 2020-06-02 at 1 35 31 PM" src="https://user-images.githubusercontent.com/309515/83567366-56890b80-a4d6-11ea-9f0f-7e55fa5511c1.png"> |
=> Fix encoding issue with btoa

schema/hyperview.xsd
Based on validating against our backend responses, I found several missing pieces of the schema:
- `<body>` can now contain `<behavior>` children
- `margin` styles can be numbers or `auto`
- `event-name` supports underscores, hypens, slashes, and periods.
- Element IDs need to support slashes for now, so we can't use `xs:ID`, `xs:IDREF`, or `xs:IDREFS`. Updated the schema to use tokens for ids.
- added border-radius styles for specific corners or edges
- added support for border styles
- `<header>` can appear more flexibly, not just at the top of `<body>`. This is needed to support wrapping the entire screen in a `<form>`.
- `<image>` can now contain `<behavior>` elements, before it didn't contain children.
- Added support for `type`, `underlineColorAndroid`, and `clearButtonMode` on text …
=> Hyperview schema: add missing support

src/core/components/load-error/index.js, src/core/components/load-error/styles.js
Instead of opening HTML error content in a new screen, simply render it in a webview directly on the error screen.
Relates to #165, closes #169
| __DEV__ + HTML Server error | Other |
|-----------------------|-------|
| <img width="584" alt="Screen Shot 2020-06-03 at 2 46 30 PM" src="https://user-images.githubusercontent.com/309515/83693323-ba7d0400-a5aa-11ea-82cd-57e19a229ea5.png"> | <img width="584" alt="Screen Shot 2020-06-03 at 2 46 18 PM" src="https://user-images.githubusercontent.com/309515/83693344-c8cb2000-a5aa-11ea-837e-f5e1e2f1c439.png"> |
=> Simpler HTML error rendering

src/behaviors/hv-hide/index.js, src/behaviors/hv-set-value/index.js, src/behaviors/hv-show/index.js, src/behaviors/hv-toggle/index.js, src/index.js, src/services/index.js, src/services/types.js, src/services/xml/index.js, src/services/xml/index.test.js
Based on our XML schema, we have three "list" attributes: `style`, `show-during-load`, and `hide-during-load`. According to the XML schema spec, the items in this string list show be tokenized by any whitespace. However, our implementation was only splitting on spaces, not on characters like newlines.
This hasn't been a problem in the past because our backend strips out all newlines in the response XML to reduce the response to one line. However, we now want the option of responses with newlines, so that we can pinpoint schema errors to a specific line. If the newline occurs in a list attribute, the HXML will not be interpreted correctly. For example:
```xml
<text style="h3\n   font-weight-bold">test</text>
```
The current code will interpret the styles as `h3\n` and `font-weight-bold`, …
=> Split list attributes on all whitespace

demo/package.json, demo/yarn.lock, src/components/hv-date-field/index.js
Generate dates in local timezone instead of UTC, so that formatting remains consistent. Also update demo app Hyperview version.
https://app.asana.com/0/244065166232575/1182609012386243/f
Tested by manually setting local TZ to IST.
|-------|-------|
| ![date-picker-before mov](https://user-images.githubusercontent.com/309515/86170601-39912980-bad0-11ea-8140-f4c4cf5ff513.gif) | ![date-picker-after mov](https://user-images.githubusercontent.com/309515/86170616-3e55dd80-bad0-11ea-90c6-72c31814c420.gif) |
=> Fix date picker

src/index.js
Allows re-use of internal method to create stylesheets from external Hyperview components
=> Expose `createStyleProp` to public API

src/components/hv-picker-field/index.js, src/services/index.js, src/services/index.test.js
Asana: https://app.asana.com/0/923014529014430/1190686856226427/f
On iOS, we do some custom rendering for the `<picker-field>` input. The input was rendered as a `View` component with the appropriate `id`, `testID`, and `accessibilityLabel` props.
On Android, we were using the native `Picker` directly and weren't propagating props. I created a method `createTestProps` to just set the test-related props on the Android component.
=> Set test props for <picker-field> on Android

demo/navigation/AppNavigator.js, demo/package.json, demo/yarn.lock, src/index.js
We want to switch to the [community library for DatePicker](https://github.com/react-native-datetimepicker/datetimepicker) in Hyperview to address rendering issues with the deprecated `DatePickeriOS` component.
- To support this new library in the demo app, we need to upgrade the Expo SDK from 37 to 39.
- The new version of Expo was showing console errors about some code in React Navigation, so I upgraded to 4.x
- This required some new dependencies and an app container wrapper around the navigators.
- Also switched to `UNSAFE_componentWillReceiveProps` in Hyperview to prevent console warnings.
Testing:
- Tested all screens and interactions in the demo and found no regressions.
=> Upgrade Expo and React Navigation in demo app

docs/reference_view.md, examples/ui_elements/index.xml, examples/ui_elements/keyboard_avoiding_view.xml, schema/hyperview.xsd, src/components/hv-view/index.js, src/components/hv-view/types.js
[Asana](https://app.asana.com/0/491474088351836/1198503649002413/f)
The keyboard is hiding the footer section only on iOS as described in the asana ticket.
We have `KeyboardAwareScrollView` but that can't be used for fixed footers since they need to be outside the scroll view. 
**Changes**:
Allow specifying `avoid-keyboard` attribute on a view. That will wrap the contents in a `KeyboardAvoidingView` for iOS only. Android has built-in support for this functionality.
**Usage**
`<view avoid-keyboard="true">
{% include 'worker/quiz/questionnaire/footer.xml' %}
</view>`
1. iOS 
2. Android
3. Example Demo
=> Added support for keyboard avoiding view

__mocks__/@react-native-community/datetimepicker.js, demo/package.json, demo/yarn.lock, examples/ui_elements/forms/date_field.xml, package.json, src/components/hv-date-field/index.js, yarn.lock
[Asana](https://app.asana.com/0/923014529014430/1198498895658493/f)
The `<date-field>` component was using the deprecated `DatePickeriOS` and `DatePickerAndroid` components from core. These don't render correctly on iOS 14. To fix the issue, I'm switching to the [community version](https://github.com/react-native-datetimepicker/datetimepicker) of this component.
Changes:
- `DateTimePicker` now has a unified component API for iOS and Android. I removed the old async callback for Android.
- New `renderPickerModalAndroid` shares code with iOS but adds focus handling and a callback that handles dismiss action.
- Updated to the prop changes documented [here](https://github.com/react-native-datetimepicker/datetimepicker#migration-from-the-older-components).
=> Switch to new date picker component

package.json, src/components/hv-date-field/index.js, src/components/hv-date-field/types.js, yarn.lock
Asana: https://app.asana.com/0/923014529014430/1144293982403313/f
As part of the cleanup to remove local state from input components (See #199 and #200), I'm removing local state from `<date-field>`. We no longer keep `focused`, `value`, and `pickerValue` in the state, instead those values are read from the DOM element. When we need to update the values, we call `onUpdate` with a cloned version of the element, which will re-render the component.
Note: There is still some local state to represent whether certain elements are currently pressed. I'll move those to functional components with React hooks in a subsequent PR.
Testing:
=> Remove some local state from <date-field>

src/components/hv-picker-field/index.js
[Asana](https://app.asana.com/0/923014529014430/1199397741510365/f)
Apply placeholder text color on Android picker
=> Fix: Apply placeholder text color on Android

docs/reference_items.md, docs/reference_list.md, docs/reference_section.md, schema/hyperview.xsd
Allow `<items/>` and `<behavior/>` tags to be direct childs of `<section>` tag (match `<list>` tag schema)
=> Fix: `<section>` schema

src/components/hv-picker-field/index.js
[Asana](https://app.asana.com/0/923014529014430/1189353069436699/f)
[Video ios](https://drive.google.com/file/d/1TY_FnjlGPmcp2ubiBzqKr963S81rgtus/view?usp=sharing)
[Video android](https://drive.google.com/file/d/1IQ-0xBK7Xvr8Dyb5vuklchutH6dXUROk/view?usp=sharing)
The picker field from updating its state immediately. This change will stop that from happening
=> Fix: Picker field changes immediately

src/services/index.js
since there has conflict between properties testID and accessibilityLabel, they can not be set together.
need to specify a dedicated one depending on current rendering platform
=> translate id to different props depending on Platform.OS

src/components/hv-view/index.js
- Requirement:
add defensive check before registerInputHandler in view component.
- Issue:
Since hyperview uses KeyboardAwareScrollView in 'react-native-keyboard-aware-scrollview', if inputRefs contain null, it would cause some random problems in some certain scenarioes as below:
1. ['Add defensive checks before calling isFocused #44',](https://github.com/wix/react-native-keyboard-aware-scrollview/pull/44#issuecomment-789619704)
2. #232 
- For references:
[Caveats with callback refs](https://reactjs.org/docs/refs-and-the-dom.html#caveats-with-callback-refs)
=> Add defensive check before registerInputHandler in view component.

src/components/hv-date-field/types.js, src/components/hv-list/index.js, src/components/hv-section-list/index.js, src/core/hyper-ref/index.js, src/core/hyper-ref/types.js, src/index.js, src/services/dom/parser.js, src/services/dom/types.js, src/services/index.js, src/services/navigation/index.js, src/services/render/index.js, src/types.js
With this change, all JS files in the project have now flow type annotations.
PR was broken down into digestible commits, it's recommended to review them individually:
- Reading stylesheet content on potentially undefined objects d1b80de
- Uniform type `number` for `delay` option a4e3d3c
- Uniform option `showIndicatorIds` 4a442fb
- Common HTTP verb/method definition bacdae8
- Type annotation fixes in navigation service 6e5a069
- Remove unused code 4a5a7d8 / 0d14ad0
- Add props/state types for Hyperview component 313b7fd
- Add missing annotations to src/index.js a9449e1
- Fix code to comply to types 3e37772
TODO:
=> Add missing flow type annotations

src/index.js, src/services/navigation/index.js
**Please note the only difference with #258 is that, #258 add some demo to verify the revises.**
please see which one to merge according to needs. and close the other one.
there are 2 revises in this PR:
1. Revise the variable `routeKeys` to global, or else it will be a local variable in every instance of Class HyperScreen.  
The issue is when run `this.navigation.navigate()` to an intermediate page, it will always navigate back to the first page(component) in the navigation stack (in demo, it will be the examples/index.xml), and replace the first page with its own content.
2. Revise in the `navigation/index.js` to fix below issue: 
When navigate to a new page (not in navigation stack yet), it will alse navigate back to the first page(component) in the navigation stack (in demo, it will …
=> fix: refine flow when action=navigate

src/index.js
This PR addresses #267 . Hyperview clients can pass in a React component as an `errorScreen` prop to the `Hyperview` component. This component will be displayed if a screen fails to load due to bad XML parsing or network problems.
Example for `demo/screens/HyperviewScreen.js`:
```js
function ErrorScreen(props) {
return (
<View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
<Text style={{fontSize: 24, fontWeight: 'bold', color: 'red'}}>Custom Error Screen</Text>
<Text style={{color: 'blue'}}>{props.error.name}</Text>
<Text>{props.error.message}</Text>
</View>
);
};
export default class HyperviewScreen extends React.PureComponent {
// code ommited...
render() {
const navigation = this.props.navigation;
const entrypointUrl = navigation.state.params.url;
return ( …
```
=> Support custom error screen

demo/components/HandleBack.js, demo/screens/HyperviewScreen.js, examples/case_studies/custom_android_back.xml, examples/case_studies/index.xml
* Created a wrapper component to handle Android back button press.
* Custom handler: Go to the first screen in the stack when android back button is pressed on the example screen. Otherwise, let react-navigation's default back handling happen.
https://user-images.githubusercontent.com/2883006/118247019-50f6bc80-b4c0-11eb-983d-aa959450e6ab.mp4
=> Demo: Custom back handler for android hardware back button

src/core/components/loading/index.js
React Native 0.63 does not have a default color for `ActivityIndicator` on Android. See [related PR](https://github.com/facebook/react-native/pull/30057).
=> Fix activity indicator in Android

src/index.js
hi @adamstep , this PR fix below error:
`this.state.url` will be null in some case during development, so add a protection. 
pls check, thanks.
=> filter null before remove routeKey

src/index.js
Fix bug introduced in https://github.com/Instawork/hyperview/pull/273 that prevents the error screen reload functionality from working. `reload()` takes an optional href arg, but in the error screen scenario, we want to make sure not to include any args (to reload the screen).
=> Fix error screen reload

package.json
Following `Getting started` guide I stuck on demo-project refusing to load because of cors missing allow header:
This PR sets cors to `*` for `http-server` so that the demo-app can be accessed without spending any extra time on investigating why it's not loading.
=> Set cors to `*` demo `test:xmlserver` command

examples/case_studies/cascader.xml, examples/case_studies/index.xml
Example of implementing a two-level menu using two `<select-single>` elements.
This first `<select-single>` triggers behavior on `select` and `deselect` to show subsets of `<option>` elements in the second `<select-single>`.
https://user-images.githubusercontent.com/1034502/119771524-b3619c80-be72-11eb-9505-3918f04f60e2.mov
=> Case study: two-level menu with <select-single>

src/components/hv-list/index.js, src/components/hv-list/index.test.js, src/types.js, test/helpers.js
Render list items that are direct children of the `<list>` element, or nested under a `<items>` children node.
=> `<list>` fix: Prevent rendering items from nested `<list>`

src/components/hv-list/index.js, src/components/hv-list/index.test.js
Follow up for #312.
One scenario with paginated lists was not accounted correctly. A paginated list could typically look like this:
```xml
<list>
<item>1</item>
<item>2</item>
<items>
<item>3</item>
<item>4</item>
<items>
<item>5</item>
<item>6</item>
<items>
...
</items>
</items>
</items>
</list>
```
Previous implementation did not account for recursive nesting aspect of `<items>`, and would only retrieve the items under the `<items>` directly nested under the main `<list>`.
This fixes it by recursively checking that the parent list is the same as our current element.
=> Fix paginated lists

.npmignore, src/services/dom/helpers.js, test/helpers.js
Add renderer for stories from XML markup, and expose it to published NPM package. Supports defining optional dependent Hyperview components.
**without dependent components:**
```js
import * as TestHelpers from 'hyperview/test/helpers';
import { storiesOf } from '@storybook/react-native';
import MyComponent from './MyComponent';
storiesOf('MyComponent', module)
.add('Example story', () =>
TestHelpers.render(
MyComponent,
'<my-component foo="bar" bar="baz" />',
),
);
```
**with dependent components:**
```js
import * as TestHelpers from 'hyperview/test/helpers';
import { storiesOf } from '@storybook/react-native';
import MyComponent from './MyComponent';
import Foo from './Foo';
import Bar from './Bar';
storiesOf('MyComponent', module)
.add('Example story', () =>
TestHelpers.render( …
```
=> Storybook render helper

CHANGELOG.md, package.json, schema/hyperview.xsd
- add `resizeMode` enumeration type
- add `resizeMode` attribute to `<image>` and `<style>` elements
Verified locally via `be_valid_hyperview` expectation in a python unit test
=> feat(schema): add "resizeMode" support

src/services/render/index.js
Setting the `key` prop ensures the component will be re-instantiated on re-render, if the matching tree element key does not match. This change permits to control this React behavior from our XML templates.
Relates to https://app.asana.com/0/1173738217633521/1200975979949916/f and https://github.com/Instawork/instawork/pull/14057
=> fix(render): Set `key` prop when matching attribute is present

website/siteConfig.js
The current favicon [`img/hv.png`](https://hyperview.org/img/hv.png) does not exist, it should be [`img/hv.svg`](https://hyperview.org/img/hv.svg).
=> Fix broken favicon image

docs/reference_behavior_attributes.md, docs/reference_textarea.md, docs/reference_textfield.md, examples/behaviors/blur.xml, examples/behaviors/change.xml, examples/behaviors/index.xml, schema/hyperview.xsd, src/components/hv-text-area/index.js, src/components/hv-text-field/index.js
In addition to the `blur` and `focus` triggers, add support for `change` so we can for instance, update a part of the UI when the user types in a text field or text area.
Partial implementation of https://github.com/Instawork/hyperview/issues/298 but doesn't handle the dirty/clean states.
=> Add support for "change" trigger on text-area and text-field

docs/reference_text.md, examples/ui_elements/text.xml, schema/hyperview.xsd, src/services/index.js
This will allow `<text>` elements to scale down automatically to fit given style constraints.
=> feat(text): allow adjustsFontSizeToFit attribute on <text> elements 

src/components/hv-picker-field/index.js
There's a history of issues with `<picker-field>` due to different implementations on iOS vs Android:
- https://github.com/Instawork/hyperview/pull/173
- https://github.com/Instawork/hyperview/pull/208
- https://github.com/Instawork/hyperview/pull/224
On Android, changes to values from the picker should apply immediately, there is no "Cancel".
On iOS, changes should not apply immediately because we've implemented our own modal.
Previous attempts to fix the issue have not been platform-aware. By checking the platform, we can use the right approach to fix issues on both platforms.
=> Fix picker-field cancel on iOS

src/services/dom/parser.js
Before throwing a `Errors.ServerError`, which results in rendering a webview with the error content when in dev mode, or a generic error message, verify if the content-type is `application/xml`. When it is the case, render the XML document like any other screens.
=> feat: Render XML server errors

src/components/hv-spinner/index.js, src/components/hv-web-view/index.js, src/core/components/loading/index.js
Undoing the change in https://github.com/Instawork/hyperview/pull/275 since we wrote a patch in the client app instead.
[Ref 1](https://github.com/Instawork/hyperview/pull/324#issuecomment-878450708)
Context:
React Native 0.63 does not have a default color for ActivityIndicator on Android. See [reference](https://github.com/facebook/react-native/pull/30057) for creating a patch on the client app.
=> Fix: undo hardcoded activity indicator color

src/services/dom/index.test.js, src/services/dom/parser.js, src/services/dom/types.js
Add additional content type in `Accept` header, to allow distinguishing full document vs fragment requests.
=> feat: improve `Accept` header

src/components/hv-view/index.js, src/services/components/index.test.js
Lists can use the `<items>` element to wrap several items when paginating. This tag does not get rendered and is only used so that generated responses are valid XML. Because it is not registered as a component, it triggers a warning when inserted into the DOM. Add it as an alias for the `view` element to get rid of the warning.
=> fix: warning about `<items>` not registered

package.json
`@react-native-community/datetimepicker` dependency has native hooks and need to be installed as a peer dependency.
Setting it to `>= 3.0.3` in peer dependencies, as the new demo app installs v4.0.0
=> fix: @react-native-community/datetimepicker dependency type

docs/reference_view.md, examples/ui_elements/scroll_view.xml, package.json, schema/hyperview.xsd, src/components/hv-view/index.js, src/components/hv-view/types.js
Add support for sticky header in scroll view, addresses #380.
https://user-images.githubusercontent.com/28518512/152913944-aeda5741-4120-4cb5-aa2a-73168cd5eb90.mp4
https://user-images.githubusercontent.com/28518512/152913998-9e4a6039-ce6c-4c1b-846f-83583402e836.mp4
Note: Flow wasn't happy with `Array.from(`, so had to fix ignore them, lmk if there is a better way to handle this.
=> feat(scroll-view): add sticky attribute

docs/reference_text.md, examples/ui_elements/text.xml, schema/hyperview.xsd, src/components/hv-text/index.js, src/services/render/index.js, src/types.js
Add alias to `<text>` to allow rendering of preformatted text.
TODO once approach is validated:
Relates to #62.
=> feat: Preformatted text

demo/package.json, demo/yarn.lock, package.json, src/components/hv-picker-field/index.js, yarn.lock
Replace with `@react-native-picker/picker` library.
| iOS | Android |
|---|---|
|  ![Simulator Screen Shot - iPhone 13 - 2022-03-15 at 16 24 57](https://user-images.githubusercontent.com/309515/158492147-f012cf35-bc50-4aa5-b7b6-65fd0ab6c7b9.png) | <img width="559" alt="Screen Shot 2022-03-15 at 5 08 26 PM" src="https://user-images.githubusercontent.com/309515/158492098-68c44a6c-facd-46a6-81da-2d3e8ae7bd45.png"> |
=> chore: Remove deprecated use of react-native `Picker`

src/components/hv-list/index.js, src/components/hv-section-list/index.js, src/contexts/index.js, src/index.js
Allow passing props to define loading, load error and list refresh control components.
Implementation notes:
- each component is passed as optional props of `HyperScreen`
- `refreshControl` prop is exposed to `HvList` and `HvSectionList` via a React context
Follow up for #330
Resolves #286
=> feat: Custom loading components

src/components/hv-view/index.js, src/components/hv-view/types.js
Apply [suggested bug fix](https://github.com/facebook/react-native/issues/26610#issuecomment-539843444) for scrollbars sometimes not rendering pinned on the side of the view
=> fix: Bug with scrollbars on iOS 13+

docs/reference_view.md, schema/hyperview.xsd, src/components/hv-view/index.js, src/components/hv-view/types.js
Add support for `content-container-style` attribute, that allows setting the property [`contentContainerStyle`](https://reactnative.dev/docs/scrollview#contentcontainerstyle) of RN `ScrollView`
=> feat(hv-view): `content-container-style` attribute

src/components/hv-list/index.js, src/components/hv-section-list/index.js
#412 introduced a bug with Android, where refresh control would not render correctly nor be properly removed once refreshing done. From my testing, it seems that nesting the `RefreshControl` under another component when setting `refreshControl` prop is causing this issue. Removing that extra nesting solves the issue.
=> fix: Refresh control on Android

package.json
The single quotes seem to prevent npm to properly interpolate the `$npm_package_version` variable (see https://github.com/Instawork/hyperview/commit/2c183da67ea11564f1a70e27a6127ca8dd29ab85). Using escaped double quotes instead (tested locally).
=> fix: Commit message on demo package update

docs/reference_option.md, docs/reference_selectsingle.md
Fixing the XML `<select-single>` end tag from the examples at https://hyperview.org/docs/reference_selectsingle and https://hyperview.org/docs/reference_option
=> chore(doc):Fix invalid XML in examples

schema/hyperview.xsd
This is an Instawork specific behavior, removing it from the core schema.
=> fix: Remove `ask-rating` from schema

src/core/hyper-ref/index.js
This change allow QA team to access nested elements via Appium, and then allow us to use this elements with their ids into automation scripts.
Setting accessible={false} is necessary for UI inspector to find child elements of TouchableOpacity, see: 
- https://github.com/facebook/react-native/issues/6560
- https://github.com/facebook/react-native/pull/6561
=> fix: set accessible to false in TouchableOpacity

docs/reference_behavior_attributes.md, docs/reference_index.md, examples/behaviors/index.xml, examples/behaviors/select_all.xml, examples/behaviors/unselect_all.xml, schema/hyperview.xsd, src/behaviors/hv-select-all/index.js, src/behaviors/hv-unselect-all/index.js, src/behaviors/index.js, src/components/hv-select-multiple/index.js, src/components/hv-select-single/index.js, src/types.js
Create `"select-all"` and `"unselect-all"` behavior actions.
https://user-images.githubusercontent.com/91907891/174645840-738bc378-fcfa-4fca-844f-e6576357a141.mp4
https://user-images.githubusercontent.com/91907891/174645831-6efcfd84-c78a-460c-b213-4b24588f0125.mp4
*NB*: while `"select-all"` is only supported by [`<select-multiple>`](https://hyperview.org/docs/reference_selectmultiple), `"unselect-all"` is supported by both [`<select-multiple>`](https://hyperview.org/docs/reference_selectmultiple) and [`<select-single>`](https://hyperview.org/docs/reference_selectsingle).
=> feat:Create select-all/unselect-all behavior actions

src/index.js, src/types.js
Add flag to `updateRoot` function to condition whether or not the stylesheets need to be updated.
Relates to #411
=> feat: `updateRoot` also updates styles

schema/core.xsd
`<items>` is an alias of `<view>` that allows returning list partials.
=> fix(schema): Allow `<section>` to be a child of `<items>`

src/services/dom/helpers.js, src/services/render/index.js
When `<text>` element are nested, collapse spaces instead of trimming them to ensure correct rendering.
|-------|-------|
| ![Simulator Screen Shot - iPhone 13 mini - 2022-07-07 at 21 24 49](https://user-images.githubusercontent.com/309515/177918108-eb8eee86-993a-4fc7-a7fa-bdcdd665d340.png) | ![Simulator Screen Shot - iPhone 13 mini - 2022-07-07 at 21 38 55](https://user-images.githubusercontent.com/309515/177918128-f3779807-723b-4836-9f01-ea2bc93dcb74.png) |
=> fix: Nested text spaces

src/services/dom/helpers.js, src/services/render/index.js
Reverts Instawork/hyperview#444
This change has a few issues:
- the warning isn't properly filtering out text nodes with empty strings (i.e. line breaks in the markup) and multiple warnings are being logged every time a screen renders
- the space handling is working fine for the given example (nested texts), but does not work as expected when there are multiple siblings `<text>` element nested under a common `<text>`.
I'm working on an alternative implementation to re-introduce this fix.
=> Revert "fix: Nested text spaces"

schema/core.xsd, schema/hyperview.xsd
Make `behavior` type named, so that schema extensions can redefine it.
Same change as #438
Requires https://github.com/Instawork/instawork/pull/18568 before merging
=> refactor(schema): Make extending behavior schema possible

src/components/hv-option/index.js, src/core/hyper-ref/index.js
Wrap every press handler with helper that stop event propagation/prevent defaults. This does not affect UX on mobile, but allows for web interactions to perform as expected (so that the links added by behaviors are not "followed" by the browser).
=> chore(web): Event handlers stop propagation/prevent defaults

src/core/components/date-time-picker/index.web.js, src/core/components/keyboard-aware-scroll-view/index.web.js, src/core/components/web-view/index.web.js
Implement variants of `date-time-picker`, `keyboard-aware-scroll-view` and `web-view` for Hyperview web.
=> fix: Implement native only components for web

examples/_includes/base.xml.njk, examples/_includes/directory_list.xml.njk, examples/_includes/scrollview.xml.njk, examples/index.xml.njk, examples/list.xml.njk, examples/navigation/back.xml.njk, examples/navigation/index.xml.njk, examples/navigation/list.xml.njk, examples/styling/button.xml.njk, examples/styling/elevation.xml.njk, examples/styling/flex.xml.njk, examples/styling/index.xml.njk, examples/styling/list.xml.njk, examples/styling/shadows.xml.njk, examples/styling/text.xml.njk
- Remove scrollview container from base layout, and create a separate scrollview layout. Create `container` block, and update related screens that need to extend it. (Solves RN warning about nested scrollable views)
- Update `directory_list.xml.njk` to not extend a base template and instead just render the list. Screens entry point now extend the default base template. In parallel, each screen that rely on a directory list now creates a separate `list.xml` template that extends `directory_list.xml.njk`. (Solves list pull to refresh mechanism)
https://user-images.githubusercontent.com/309515/179424708-80457e0c-18ab-4fa2-9fa8-813ba9188724.mp4
=> fix(examples): List layouts

.eleventy.js, demo/App.js, demo/src/HyperviewScreen.js, demo/src/gesture-handler/index.js, scripts/sync/index.js
- Wrap gesture-handler module dependency behind web-ready module.
- Pass `cors` option to fetch
- Configure eleventy to send correct CORS headers
**Testing instructions:**
```sh
cd hyperview/
rm -rf node_modules/ demo/node_modules/
watchman watch-del-all
rm -rf $TMPDIR/haste-map-* $TMPDIR/metro-cache
yarn
yarn sync demo lib
yarn test:xmlserver
```
in another terminal:
```sh
cd hyperview/demo
yarn start --clear --web
```
https://user-images.githubusercontent.com/309515/179417526-f568d63a-b899-49cb-8dcb-b88379a9a291.mov
=> feat(demo/web): Configure demo app to work on web

examples/_includes/loading_screen.xml.njk, src/index.js, src/services/navigation/index.js
Restore functionality of custom loading screens, which got broken in #69.
Implementation notes:
The dictionary that keeps track of loading screen was improperly moved to the `navigation` instance, which is re-created on each screen. Move this back to a global variable so new pushed screens can access it.
https://user-images.githubusercontent.com/309515/180581726-9c5ebd87-7f19-4321-98f3-ac68c363c3fb.mp4
=> fix: Custom loading screen

src/core/hyper-ref/index.js
Break up the `HyperRef.render` method into smaller, more manageable chunks.
Note to reviewers: it'll be easier to take a look first at individual commits to understand the thought process behind this refactor.
Verified that demo app continues to work as expected
https://user-images.githubusercontent.com/309515/180355495-92c85252-9cd4-4b87-9f0b-7a7674a28695.mp4
https://user-images.githubusercontent.com/309515/180359323-7310790a-a9dd-4411-b44e-d5c9238586eb.mp4
=> refactor: `HyperRef` component

examples/behaviors/_replace_link_fragment.xml, examples/behaviors/long_press.xml, examples/behaviors/press.xml, examples/behaviors/press_in.xml, examples/behaviors/press_out.xml, examples/ui_elements/text/nested.xml, src/core/hyper-ref/index.js
When rendering `hyper-ref` component within a text element, use `Text` component instead of `TouchableOpacity`.
Note: I tried using more modern `Pressable` component as a replacement of `TouchableOpacity`, but it did not allow keeping inline layout on nested `<text>`.
Solves #307
https://user-images.githubusercontent.com/309515/180471486-f5ba11fa-d502-4eed-8cb9-b1d59e0a5d9b.mp4
https://user-images.githubusercontent.com/309515/183530120-271e4c5d-dac2-4953-a000-f73dd5dd2f3d.mov
=> fix: Inline links

docs/reference_behavior_attributes.md, examples/advanced_behaviors/copy_to_clipboard/index.xml, schema/core.xsd, src/behaviors/hv-copy-to-clipboard/index.js
`value` is an attribute that is currently used by many other elements, sometimes with different meanings/types (i.e. `hv-switch` defines it as a complex type). Because this overlaps with non-behavior attributes, it clashes when we try to validate the markup.
Rename the attribute to be specific to the behavior, and add the attribute to schema.
Relates to #195
=> fix(copy-to-clipboard): Make attribute name specific to usage

schema/core.xsd
`key` attribute is used by React when rendering component in the context of loop. We need to allow it on every elements for XML validation to pass.
=> chore(schema): Allow `key` attribute

schema/core.xsd
Prior to this change, `text` would have to be defined before `behavior`. This change allows the following markup to be valid:
```xml
<text>
<behavior action="show" target="pressed" />
<text id="press">
Press
</text>
<behavior action="hide" target="press" />
<text hide="true" id="pressed">Pressed!</text>
</text>
```
=> fix(schema): Allow nested texts with behaviors in any order

src/components/hv-view/index.js
Revert back to using React API in place of JSX (introduced in a9b34852ac2a16cda6db7959a54b17b2ab9fca17), so that we're able to spread children object like it use to. This solves issues with warnings abou t missing keys when rendering list of elements.
=> fix: Rendering children of `hv-view`

demo/package.json, demo/webpack.config.js, demo/yarn.lock
- run command `expo customize:web` to generate `webpack.config.js`
- add configuration to transpile hyperview library when bundling demo app
This helps running the demo app on web while running the command `yarn sync` to allow debugging of core library.
=> fix(demo/web): Transpile `hyperview` lib

src/components/hv-option/index.js, src/core/hyper-ref/index.js
Rework change introduced in #453, that was meant to fix navigation on web but ended up causing issues on mobile web. The need with the fix was intended to work around the event propagation happening on `select-*` components, wherein selecting an option would lead to navigating to the linked `href` (instead of simply performing the selection). Calling `preventDefault` globally did not interfer with web click events, but prevent mobile web touch events from being received by their target element. The fix here makes calling the `preventDefault` optional, and removes the call to `stopPropagation` (which does not have a perceived effect on event handling in Hyperview/RN web). We explicitly set `preventDefault` on the `hv-option` component, where a press event is not meant to trigger a …
=> fix: Navigating on mobile-web

examples/ui_elements/list/infinite_scroll.xml, src/core/hyper-ref/index.js
While working on changing how we render our loading state in lists (so that we would not render the loading state/animation until it's actually made visible), I discovered the following bug:
[Per spec](https://hyperview.org/docs/reference_behavior_attributes#update-actions), when `target` is not set, the target will be the source of the behavior, that is, the parent container. However, this did not work correctly, an the changes made to `examples/ui_elements/list/infinite_scroll.xml` include a repro case of the issue. The root cause is still a bit unclear, but most likely related to how we mutate the Hyperview DOM while preserving a separate copy in the React state.
I found that by changing the behavior handler creator to not receive the current DOM element, and instead pass the element …
=> fix: Incorrect `element` reference

src/services/render/index.js
Note: this is a temporary work around to prevent crashes. Proper fix should be addressed in the form of refactors of faulty components.
This issue occurs as we have numerous places in the code base that expects an element to be returned, even when not present. e.g. with the following markup:
```xml
<section-list>
<section>
<item><text>Foo</text></item>
<item><text>Bar</text></item>
</section>
</section-list>
```
in the example above, we're missing the `<section-title>` element, but [this code](https://github.com/Instawork/hyperview/blob/master/src/components/hv-section-list/index.js#L105-L107) assumes it does. Upon trying to render it, the app crashes as we're trying to access properties on an `undefined` object. There's a variety of other places in the code that attempt to access …
=> fix: Prevent crashes on invalid markup

schema/core.xsd
- Switch element schema does not allow any children as per current schema. It is useful to have behavior tags inside switch element to trigger a behavior if the switch value is changed.
- This change allows elements of type `behavior` to be inside `switch` element.
=> fix(core-schema): update switch element to allow behaviors as children

src/core/hyper-ref/index.js, src/index.js, src/services/dom/index.test.js, src/services/dom/parser.js, src/services/dom/types.js, src/types.js
1. Add support for `X-Response-Stale-Reason` header, this header is set when content fetched is stale, typically served from a cache.
2. Implement new trigger `load-stale-error`, so that the UI can be modified when the content served is stale.
=> feat(header): support stale reason header and stale error trigger

schema/core.xsd, src/core/hyper-ref/index.js, src/core/hyper-ref/types.js
`load` behavior are triggered by default on the next event loop. Apparent reason for this, is to wait until the first render occurred to trigger behavior that may try mutate existing elements.
While this works for most cases, there's some situation when we want to trigger custom behaviors before the render cycle occurred. This code change introduce a new boolean attribute `immediate`, which controls this.
The behaviors API need some work in general (i.e. "delay", "once" are not consistently supported for every triggers), so for the time being, we're keeping this new attribute as undocumented, as we're not certain how the behavior spec will evolve in the future.
=> feat: `immediate` load behavior

src/core/components/load-element-error/index.js, src/core/components/load-element-error/styles.js, src/core/components/load-element-error/types.js, src/index.js
When the document is already loaded on to the screen but the subsequent requests fail due to an error while scrolling, currently entire screen shows an error message, and we lose the previous content.
This PR aims to handle HTTP errors gracefully by showing a banner at the bottom indicating there was an error but still let the user browse the content which was already loaded.
| --- | --- |
| <video src="https://user-images.githubusercontent.com/28518512/217921739-5aed32a3-fd03-4d93-b1fc-8cfe406da5f5.mp4" /> | <video src="https://user-images.githubusercontent.com/28518512/217847216-56d2e123-e7f9-4933-89c0-d3b28cf345b9.mp4" /> |
=> feat: Handle element error gracefully

src/services/url/index.js, src/services/url/types.js
Web API does not expose the same methods allowing to retrieve the form data as React Native does. Update the implementation to be compatible with Web API.
=> fix(web): Add form data to URL

docs/reference_index.md, docs/reference_item.md, docs/reference_items.md, docs/reference_section.md, docs/reference_sectionlist.md, docs/reference_sectiontitle.md, examples/behaviors/index.xml.njk, examples/case_studies/photos/index.xml, examples/ui_elements/list/index.xml, examples/ui_elements/sectionlist/_deprecated_scroll_page2.xml, examples/ui_elements/sectionlist/_infinite_scroll_append_page2.xml, examples/ui_elements/sectionlist/_infinite_scroll_page2.xml, examples/ui_elements/sectionlist/_refresh_load.xml, examples/ui_elements/sectionlist/_refresh_load2.xml, examples/ui_elements/sectionlist/basic.xml, examples/ui_elements/sectionlist/deprecated_sections.xml, examples/ui_elements/sectionlist/index.xml, examples/ui_elements/sectionlist/infinite_scroll.xml, examples/ui_elements/sectionlist/non_sticky_titles.xml, examples/ui_elements/sectionlist/refresh.xml, examples/ui_elements/web_views/index.xml, schema/core.xsd, src/components/hv-section-list/index.js, src/components/hv-section-list/stories/basic.xml, src/components/hv-section-list/stories/index.js, src/components/hv-section-list/stories/infinite_scroll_append.xml, src/types.js, storybook/templates.gen.js
Update section-list to not require grouping via \<section\> children
Added a new 'deprecated' example which displays backwards compatibility for including \<section\> elements within a \<section-list\> and as the top element in a reload/refresh page.
Resolves #294
=> feat(section-list): remove 'section' requirement

schema/core.xsd
Removing the redundant `hv:item` inside `section`
=> Removing redundant entry in <section>

schema/core.xsd
Restoring `hv:behavior` to the `section` schema
=> Restoring the behavior to the section elements

schema/core.xsd
`items` is required as an element of `section-list` to allow grouped elements like a loading indicator
=> feat(section-list): add 'items' to list of 'section-list' child types

schema/core.xsd
The 'id' attribute is required to allow `items` as an identifiable container element
=> fix: add 'id' to 'items'

src/components/hv-picker-field/index.js
In this component, we have special rendering for iOS, while Android relies on the default picker UI. This code change makes the Android handling the "default" so that `web` platform can also correctly be rendered.
=> refactor(hv-picker-field): Correctly handle web picker

schema/core.xsd
`load-stale-error` was introduced in this [PR](https://github.com/Instawork/hyperview/pull/504), adding it to the schema as well.
=> chore: add trigger `load-stale-error` to the schema

docs/reference_datefield.md, docs/reference_pickerfield.md, examples/behaviors/blur.xml, examples/behaviors/change.xml, examples/behaviors/focus.xml, schema/core.xsd, src/components/hv-date-field/index.js, src/components/hv-picker-field/index.js
Add `focus`/`blur`/`change` triggers to `picker-field` and `date-field` elements.
Relates to https://github.com/Instawork/hyperview/issues/298
https://user-images.githubusercontent.com/309515/231906873-64395d0f-618b-4220-9329-42368c00dff6.mp4
=> feat: `picker-field`/`date-field` new triggers

src/index.js
Currently `once` is only respected for [update actions](https://github.com/Instawork/hyperview/blob/master/src/types.js#L390). All the other actions such as `load`, `load-stale-error` etc. ignore `once`.
This causes an infinite render of `HyperScreen` and thereby causing a crash in some situations. The same is true with custom behaviors (https://github.com/Instawork/hyperview/issues/290).
| --- | --- |
| <video src="https://user-images.githubusercontent.com/28518512/235128036-23e453ad-79e4-4c44-9b02-2e19910552fc.mp4" /> | <video src="https://user-images.githubusercontent.com/28518512/235133854-4cc711f3-ff0d-4255-90de-60085085e493.mp4" /> |
=> fix(behavior): respect `once` for custom update

schema/core.xsd
Re-organize border section of schema to follow same order defined in [RN docs](https://reactnative.dev/docs/view-style-props#borderbottomcolor), and add missing style attributes.
=> fix(schema): missing style props

package.json, yarn.lock
This pull request addresses the security issue that was discussed in ticket #541
=> fix(security): upgrade url-parse to v1.5.10 to fix CVE-2022-39353

.eslintrc
Updated linting rules for .ts and .tsx files
https://app.asana.com/0/0/1204637347494056/f
`arrow-body-style`
---
`allow-parens`
---
`instawork/flow-annotate`
---
`flowtype/no-types-missing-file-annotation`
---
`func-call-spacing`
---
`function-parens-newline`
---
`indent`
---
`no-spaced-func`
---
`no-use-before-define`
---
`operator-linebreak`
---
`object-curly-newline`
=> chore(eslint) - Updated linting rules for TypeScript

docs/reference_style.md, schema/core.xsd, src/services/stylesheets/index.js
Allow `flex-basis` to be a string or number (previously only number). This allows setting the underlying RN style attribute to `auto`. Also update the schema to make a comparable style type reusable (`margin` becomes `sizing`)
=> fix: `flex-basis` style

src/services/navigator/helpers-legacy.ts, src/services/navigator/types-legacy.ts
This is the set of features needed from the original /src/types.js file, ported to TypeScript. This file can be eliminated once the types.ts file is completed.
A few small changes to the original functionality are noted with ***** ADDED ***** to ensure easier migration
=> feat(navigator) - Migrate types

src/index.js
When fetching a partial fails then don't update the state with new doc.
| --- | --- |
| <video src="https://github.com/Instawork/hyperview/assets/28518512/8c885640-2c7c-4741-ab9f-7fcbce12cf91" /> | <video src="https://github.com/Instawork/hyperview/assets/28518512/47ee48c5-590f-4746-bb66-0386c062a71a" /> |
=> fix(fetch-element): Don't update the state when fetch fails

src/components/hv-view/index.js
[This commit](https://github.com/Instawork/hyperview/commit/76a367a660683645c6819e04987f423103573581) (added in 0.58.0) introduced element attributes caching in `HvView`, which was mostly a refactor for convenience before restructuring the component itself, so that the attributes could be shared by multiple instance methods of `HvView`. It was first assumed that any state/props changes would cause the `componentDidUpdate` method, which in turn could help us re-set the attributes. However, the caching mechanism appear to cause incorrect attributes to be initially set but never updated to expected values. It's unclear if this is due to DOM mutations which could cause the `element` prop to remain unchanged when some parts of the object have changed, or something else. Removing caching help …
=> fix(hv-view): remove attributes caching

src/index.js
Permanent fix for https://github.com/Instawork/hyperview/pull/561. When partial fetch fails make sure to get the latest doc to avoid any race conditions. This will ensure that we properly clear loading indicators after the fetch call.
=> fix: when fetch fails, get the latest doc

src/core/components/load-element-error/styles.js
Some devices are not inheriting black color by default, explicitly setting the color
=> fix: error text color

src/core/components/load-error/styles.js
Android sets text color to white in dark mode. Setting the error color explicitly for full page error, text on element error is already set in this [pr](https://github.com/Instawork/hyperview/pull/567).
| --- | --- |
| <img src="https://github.com/Instawork/hyperview/assets/28518512/2eaac7ba-cf01-4e13-a933-d08a877d048f)" /> | <img src="https://github.com/Instawork/hyperview/assets/28518512/8b107574-2c63-40c4-921f-ab0aa12d229d" /> |
=> fix(error): explicitly set text color for android

demo/App.js, demo/package.json, demo/yarn.lock, examples/navigator/dynamic-complex.xml, examples/navigator/home.xml, examples/navigator/my-shifts.xml, examples/navigator/shifts.xml, package.json, schema/core.xsd, src/core/components/hv-navigator/index.tsx, src/services/navigator/imports.ts, src/services/navigator/index.ts, src/services/navigator/types.ts, yarn.lock
- Correct App.js to import gestures from local src to support multi-platform
- Replacing 'top-tab' and 'bottom-tab' with 'tab'
- Updated schema
- Remove material top tab package and dependencies from package manifest
- Updated temp demo to use new types
=> chore(navigator) - removing different tab types

src/core/components/hv-navigator/index.tsx, src/core/components/hv-route/index.tsx
- Resolved issue with having a stack navigator with nested navigators in a single file
- Updated HvRoute to not reload the document when it is created with a nested navigator
=> fix(navigator) - bug fixes for nested hierarchies

docs/reference_behavior_alert.md, examples/advanced_behaviors/alert/options.xml.njk, schema/alert.xsd, src/behaviors/hv-alert/index.js
Allow alert option button style to be defined.
=> feat: alert button style

src/components/hv-list/index.js, src/components/hv-section-list/index.js
Follow up for #413
Apply the same fix for `list` and `section-list` that was originally applied to scrollable `view`.
|  | Before | After |
|--|--------|-------|
| `list` | ![before-list](https://github.com/Instawork/hyperview/assets/309515/e933862a-3631-4cf5-9302-ff2a4d7a0847) | ![after-list](https://github.com/Instawork/hyperview/assets/309515/ed8e7f09-bb5f-4415-a64f-b69941f6577a) |
| `section-list` | ![before-section-list](https://github.com/Instawork/hyperview/assets/309515/0ec527ca-eee1-4787-a92c-1067fe461587) | ![after-section-list](https://github.com/Instawork/hyperview/assets/309515/7ff16fa7-0aed-41c7-a22c-39caf83071ce) |
=> fix: scrollbar bug with iOS 13+

.prettierignore, package.json
Before this change, one would need to delete the `_examples_site` directory before being able to run Prettier tests. This change also removes the trailing slash in the command that validates XML (doesnt change the test behavior, but makes the output of validated file paths correct).
=> fix: ignore Eleventy generated files from Prettier

src/core/components/hv-route/index.tsx
Resolve an issue where subsequent dynamic screens were reloading the defined sub-navigator rather than using the passed url.
Asana: https://app.asana.com/0/0/1204865667381531/f
=> fix(navigator) - Stack navigator with defined sub-navigator

src/behaviors/hv-alert/index.js
Add a default option on Android when none specified.
|------|------|
| <img width="559" alt="Screenshot 2023-06-26 at 1 04 24 PM" src="https://github.com/Instawork/hyperview/assets/309515/cb382cac-a066-4447-8e68-e2f199c9ed5e"> | <img width="559" alt="Screenshot 2023-06-26 at 1 01 24 PM" src="https://github.com/Instawork/hyperview/assets/309515/04a1d227-e8ce-41db-8995-4bf259c228b9"> |
=> fix(alert): Android alert without options

src/index.js
This used to be disabled on the legacy entry point, and apparently helped obfuscating a lot of typing errors in our apps, which now have resurfaced. This reverts the original behavior.
=> fix(flow): disable flow on entrypoint file

package.json
- The package was defined in devDependencies but needs to be in the peer as well
=> fix(types) - adding peer dependency for types/react

src/core/components/hv-route/index.tsx, src/core/components/hv-route/types.ts, src/core/components/hv-screen/index.js, src/core/components/hv-screen/types.ts, src/types-legacy.ts
- Provide a document to HvScreen when it is created from HvRoute
- Use the document once in lieu of loading from url
- Remove the initial document so it won't be used after initialization completes
Asana: https://app.asana.com/0/1204008699308084/1204911836776291/f
=> fix(navigation) - Allow injecting a doc into HvScreen

src/contexts/navigator.tsx, src/core/components/hv-route/index.tsx, src/core/components/hv-route/types.ts, src/core/components/hv-screen/index.js, src/core/components/hv-screen/types.ts, src/services/components.d.ts, src/services/navigation/index.js, src/services/stylesheets.d.ts, src/types-legacy.ts
Adding preload screen functionality to HvRoute since it is now handling loading
- Added global preload screen registry to navigator context
- In legacy code, this is local to the screen as each screen instantiates its own navigation service. This change allows the preload registry to continue to live in the local navigation service and also in a global context available to all HvRoutes in the hierarchy.
- provided callback to allow HvScreen+local navigation service to also register in the global context registry
- Added preloadScreen to route params
- previous requirement included only id and url
- Added preload screen rendering into HvRoute
- HvRoute now performs the loading which HvScreen previously performed
- Created description files for services required for preload render
- …
=> feature(navigation) - Add preload functionality to HvRoute

README.md, demo/package.json, demo/yarn.lock, package.json, src/components/hv-list/index.js, src/components/hv-section-list/index.js, src/core/hyper-ref/index.js, src/services/dom/index.test.js, src/services/dom/parser.js, src/services/index.test.js, storybook/helpers.js, test/helpers.js, yarn.lock
Addresses https://github.com/Instawork/hyperview/issues/520
Switching from `xmldom-instawork` NPM package to `@instawork/xmldom`. The new NPM package is branched from a version of https://github.com/xmldom/xmldom that has a critical security fix. We applied our own parser error fix on top of it.
NOTE: before creating a full release, we will create a pre-release on NPM to do a full regression test.
=> switch to new xmldom lib

schema/core.xsd, src/core/components/hv-navigator/index.tsx, src/services/navigator/helpers.test.ts, src/services/navigator/helpers.ts, src/services/navigator/index.ts
To better reflect both the initial state and the potential tracking of current state, the 'initial' attribute is being renamed 'selected'
- Updated method name in helpers and exports
- Updated tests
- Updated schema
=> chore(initial) - Change 'initial' attribute to 'selected'

src/contexts/navigator-map.tsx, src/contexts/route-doc.tsx, src/core/components/hv-navigator/index.tsx, src/core/components/hv-navigator/types.ts, src/core/components/hv-route/index.tsx, src/core/components/hv-route/types.ts, src/services/dom/helpers-legacy.ts, src/types-legacy.ts
The original implementation for handling `<navigator>` elements nested inside `<nav-route>` elements relied on storing Dom elements in a map by the id of the route which contained them.
This had several problems:
- A cache had to be created
- The items in the cache could become orphaned from their parent doc
- Mutations to the doc would not be reflected in the cache
- The cache was never cleared
- The id or index of the implementation could change
This new solution uses a context to wrap every `hv-route` which contains its own document. This allows child routes to retrieve their Dom element and retrieve any nested navigator direction from the doc.
Improvements are also made to the initial route by creating all routes into the stack navigator.
=> fix(navigator) - improved handling of nested navigators

src/core/components/hv-route/index.tsx, src/services/navigator/helpers.ts, src/services/navigator/index.ts, src/services/navigator/types.ts, src/types-legacy.ts
Reflect the user's selections in the document
- Use the 'focus' listener to allow each hv-route to set its selected state within the document
- De-select any sibling routes to ensure the current is the only selected
Note: I did not use 'blur' to have each route deselect itself as that would cause routes in the background to lose their state.
In the video, as the user selects between the different tabs, the various \<nav-route\> children of `tabs-navigator` are shown to reflect current selection. When the `company` modal is popped up, the `company` \<nav-route\> shows selected while its sibling `tabs-route` becomes deselected. Note that the `tabs-navigator` children retain their correct selection state.
Asana: https://app.asana.com/0/0/1205197138955014/f …
=> feature(selection) - Track the current selection state of each nav-route

schema/core.xsd, src/contexts/navigator-map.tsx, src/core/components/hv-navigator/index.tsx, src/core/components/hv-route/index.tsx, src/core/components/hv-route/types.ts, src/services/navigator/helpers.test.ts, src/services/navigator/helpers.ts, src/services/navigator/index.ts, src/services/navigator/types.ts, src/types-legacy.ts
Previous implementation used 'dynamic' and 'modal' routes as the only two children of `stack` navigators. The urls were cached into a context and retrieved by id.
This update allows each defined `\<nav-route\>` to be added to its navigator. These known routes can retain their original url and presentation and reduce the complexity of navigating between them.
One note about the implementation: the 'initialParams' passed into each route contain their actual url. When we navigate to a route through a behavior, the new params are merged with the existing. The url had to explicitly be deleted from the object as passing a url:undefined would overwrite the initial url value with an 'undefined' value.
Asana: https://app.asana.com/0/0/1205197138955012/f
=> chore(nav-routes) - Update to support adding all defined routes to navigators

package.json
Versions on peer dependencies no longer pinned, this will allow for updating these dependencies on target apps without having new NPM/Yarn warnings.
=> fix: Change peer dependencies accepted versions

docs/reference_datefield.md, examples/advanced_behaviors/set_value/index.xml.njk, examples/behaviors/blur.xml, examples/behaviors/change.xml, examples/behaviors/focus.xml, examples/ui_elements/forms/date_field/index.xml.njk, schema/core.xsd, src/components/hv-date-field/modal/index.js, src/components/hv-date-field/overlay/index.js, src/components/hv-date-field/overlay/styles.js, src/components/hv-date-field/overlay/types.js, src/components/hv-date-field/stories/basic.xml, storybook/templates.gen.js
This updates the UX of the date field component, by adding an overlay / "scrim" element covering the screen under the modal. The overlay is tappable and dismiss the modal (same action as pressing the "cancel" button). Both opening and closing action cause the modal to slide up and down in an animated fashion.
Implementation details:
The slide up animation of the modal is recreated with an animated view - this is needed so that the overlay can be decoupled from this animation.
Another refactor will follow to pull out the modal + overlay components, in order to share/reuse these with the picker field.
https://github.com/Instawork/hyperview/assets/309515/f7f0ad93-a31c-417b-857e-b588512e99ca
=> refactor(hv-date-field): Add modal overlay

src/core/components/hv-navigator/index.tsx, src/services/navigator/imports.ts, src/services/navigator/index.ts
Using the `cardStyleInterpolator` option to force iOS to render modals at full screen while retaining their intended animation.
| Default | Updated iOS | Updated Android |
| ------ | ----- | ----- |
| ![default](https://github.com/Instawork/hyperview/assets/127122858/d7a3d4c7-459b-453e-b454-37e1b56ec62f) | ![iOS](https://github.com/Instawork/hyperview/assets/127122858/239bad17-48fe-40e6-86d4-e4cb1bad4603) | ![android](https://github.com/Instawork/hyperview/assets/127122858/135dd21b-4725-4efa-94eb-5859ac983a94) |
Asana: https://app.asana.com/0/0/1205197143810575/f
=> chore(modal) - Change iOS presentation to use fullscreen

src/core/components/hv-navigator/index.tsx, src/core/components/hv-route/index.tsx, src/services/navigator/imports.ts, src/services/navigator/index.ts
Changed approach to use `getDerivedStateFromProps` to drive the state.doc value
=> fix(state) - override the state.doc

src/core/components/hv-route/index.tsx
- use the more performant `getFirstChildTag` since all these locations know their structure
- simplified the usage of the internal component to not require its own props type
=> chore(cleanup) - performance improvements

src/core/components/hv-navigator/index.tsx, src/core/components/hv-navigator/types.ts, src/core/components/hv-route/index.tsx, src/services/navigator/helpers.ts, src/services/navigator/index.ts
A few code refactors which will help the next step:
1. Created a helper to determine if a route id is one of the generated 'dynamic/modal' routes
2. Centralized the `screenOptions` for stack navigators to reduce redundant code
3. Created a better `getId` function for getting the id of dynamic and defined routes
4. Moved the creation of dynamic routes into its own function
5. Re-use `buildScreen` when building dynamic routes to avoid redundant code
=> chore(refactor) - small improvements to navigator code organization

src/core/components/hv-navigator/index.tsx, src/core/components/hv-navigator/types.ts, src/core/components/hv-route/index.tsx, src/core/components/hv-route/types.ts
When a modal is opened, there may be additional navigation which happens within its content. If the modal implements its own stack, those navigation actions can occur within the view of the modal. They can be closed without having to back out of all the screens.
In the following videos, the 'company' view is defined as a modal. Without the stack navigator, the 'edit' action replaces the 'company' view and the user has to go back before closing the modal. With the stack navigator, the user can close the modal at any point.
Note: default react-navigation UI is being used in these videos to simplify the navigation.
| No stack | With stack |
| ---- | ---- |
| ![nostack](https://github.com/Instawork/hyperview/assets/127122858/8fbf265d-2720-4879-812b-7579205291c5) | …
=> chore(modal) - add a stack navigator to modals

examples/ui_elements/forms/picker/index.xml.njk, src/components/hv-picker-field/field-label/index.js, src/components/hv-picker-field/field-label/types.js, src/components/hv-picker-field/field/index.js, src/components/hv-picker-field/field/types.js, src/components/hv-picker-field/index.js, src/components/hv-picker-field/types.js
Note: This PR is one in a series of refactors, see #633 for other related changes.
Refactor `hv-picker-field` to use `modal` component, and model internal implementation after `hv-date-field`, in particular with regards to maintaining the picker state in the DOM instead of React's state.
In addition to the UX improvements, these changes bring fixes to the following bugs (visible in "before" video captures below):
- [Android]: `focus` and `blur` events would not trigger
- [iOS]: when picker does not have an "empty" first option, opening the picker and selecting the first option wasn't working properly, and user would need to scroll to trigger a state change and then reselect the first option.
|  | Before | After |
|--|------|--------|
| iOS | …
=> refactor(`hv-picker-field`): use `modal` component

src/components/hv-picker-field/index.ios.js, src/components/hv-picker-field/index.js
Note: This PR is one in a series of refactors, see #633 for other related changes.
When the field does not have an empty first value, generate one during rendering to allow the first option to become selectable.
|--------|-------|
| ![before](https://github.com/Instawork/hyperview/assets/309515/11d9625b-9bcb-467f-bc93-ecd7ceb84e0a) | ![after](https://github.com/Instawork/hyperview/assets/309515/4575bdc4-1ab0-4f0b-a94a-22a6b7b518c1) |
=> fix(`hv-field-picker`): First option not selectable on Android

src/core/components/hv-navigator/index.tsx, src/services/navigator/helpers.test.ts, src/services/navigator/helpers.ts, src/services/navigator/index.ts, src/services/navigator/types.ts
Replaced all uses of 'dynamic' as a type of route to 'card' to better reflect the implementation details.
=> chore(dynamic) - refactor 'dynamic' to 'card'

demo/package.json, demo/yarn.lock, package.json, src/behaviors/hv-copy-to-clipboard/index.js, yarn.lock
The `Clipboard` class has been extracted from the react-native core, and the proper way to use it is through a package `@react-native-clipboard/clipboard`.
- Add the required package to the peer and dev dependencies.
- Import the Clipboard object from the correct package.
Functional and no warning:
https://github.com/Instawork/hyperview/assets/125880/c8963eb4-a219-4c2e-ae39-a2692b21bfe0
Closes #461
=> fix: stop usage of deprecated api

src/core/components/hv-route/index.tsx, src/services/navigator/helpers.ts, src/services/navigator/index.ts, src/services/navigator/types.ts, src/types-legacy.ts
The initial document may contain multiple <nav-route> elements in a stack. These will be pushed onto the stack immediately. As they are closed they should be removed from the dom to reflect the current state.
Note: card and modal routes pushed onto the stack by user activity will not be added to the dom to reflect state.
Asana: https://app.asana.com/0/0/1205225573228534/f
---
Example: closing the 'company' modal.
Before:
```XML
<doc ...>
<navigator id="root-navigator" type="stack">
<nav-route id="tabs-route" selected="false">
<navigator id="tabs-navigator" type="tab">
<nav-route id="live-shifts-route" href="/biz_app/gigs/live_shifts" selected="false"/>
<nav-route id="shifts-route" href="/biz_app/sub-navigator" selected="true"/>
<nav-route id="account-route" href="/biz_app/account" …
```
=> chore(dom) - reflect navigation state in dom

docs/reference_datefield.md, docs/reference_pickerfield.md, examples/ui_elements/forms/date_field/index.xml.njk, examples/ui_elements/forms/picker/index.xml.njk, schema/core.xsd, src/core/components/modal/index.js
Add parameters to customize duration of opening and closing animations of both modal and overlay for date field and picker field.
https://github.com/Instawork/hyperview/assets/309515/4d265bf1-13a6-44e2-a9df-149dff02d566
=> feat(pickers): Custom animation transitions of modal/overlay

demo/package.json, demo/yarn.lock, package.json, src/behaviors/hv-copy-to-clipboard/index.js, yarn.lock
Reverts Instawork/hyperview#646
This library does not work "as-is" in the Expo demo app, forcing additional/manual work to append. We should instead use the library [expo-clipboard](https://docs.expo.dev/versions/v49.0.0/sdk/clipboard/).
=> Revert "fix: stop usage of deprecated api"

src/components/hv-date-field/index.js
Refactor in #634 led to DOM being updated twice, causing the UI to glitch upon selecting a date in Android date field. This combines the date selection with the dimsissal of the picker (much like the way done for picker field).
|-----|------|
| ![before](https://github.com/Instawork/hyperview/assets/309515/427b39e4-b366-4b90-8648-c12f95b22ef5) | ![after](https://github.com/Instawork/hyperview/assets/309515/d3fcdcab-2c1c-4146-952c-22a0a4186804) |
=> fix(android): `DateField` selection visual bug

src/components/hv-picker-field/index.ios.js
[This method](https://github.com/Instawork/hyperview/blob/master/src/components/hv-picker-field/index.js#L116C3-L134C5) got lost in the few previous refactors, and caused a regression in the formatting of the label on iOS.
|-----|-----|
| ![before](https://github.com/Instawork/hyperview/assets/309515/4d175a34-2c46-4b12-9af0-a592af8d5450) | ![after](https://github.com/Instawork/hyperview/assets/309515/23fc9cc2-6690-4a97-8f8b-3594cda8b399) |
=> fix(ios): bring back `getLabelForValue`

src/core/components/modal/index.js
Allow duration of 0 and more only.
=> fix(pickers): Animation durations config parsing

src/core/components/hv-navigator/index.tsx, src/core/components/hv-navigator/types.ts
Making the tab navigator setup more closely resemble the stack navigator
=> chore(cleanup) - improved setup for tab navigator options

src/components/hv-image/index.js, src/components/hv-text/index.js, src/components/hv-view/index.js, src/core/hyper-ref/index.js
With previous code, we would first render the Hyperview element and its children (example: [HvText](https://github.com/Instawork/hyperview/blob/25d1633ca92fd2d87a8c504a1b61245a50ab6a2f/src/components/hv-text/index.js#L36-L49)) before [delegating to addHref](https://github.com/Instawork/hyperview/blob/25d1633ca92fd2d87a8c504a1b61245a50ab6a2f/src/components/hv-text/index.js#L53), which would then check for presence of behavior, and when some found, would [render element's children again](https://github.com/Instawork/hyperview/blob/25d1633ca92fd2d87a8c504a1b61245a50ab6a2f/src/core/hyper-ref/index.js#L451), before rendering `HyperRef`, which internally would [render the element again](https://github.com/Instawork/hyperview/blob/25d1633ca92fd2d87a8c504a1b61245a50ab6a2f/src/core/hyper-ref/index. …
=> refactor(`HyperRef`): Remove unnecessary render cycles

examples/navigation/reload.xml.njk
The current functionality doesn't support using <screen> elements for show-during-load. The demo was trying to illustrate this feature.
For now, I have not removed the <screen> but have added a small <view> element with message and spinner to illustrate the feature.
More work to be done separately to add support for <screen> loaders: https://app.asana.com/0/1204323441804469/1205320418809826/f
https://github.com/Instawork/hyperview/assets/127122858/57dac9f0-0c01-441a-bf96-16eb5fb8c910
=> chore(demo) - fixed navigation/reload load indicator

examples/case_studies/tabs/groups.xml, examples/case_studies/tabs/index.xml, examples/case_studies/tabs/users.xml, src/VisibilityDetectingView.js, src/core/hyper-ref/index.js, src/core/hyper-ref/types.js
When toggling views with `show`/`hide` behaviors, if the layout is identical enough (i.e. same elements structure), then React does not unmount the instances of `VisibilityDetectingView`, which in turn cause the previous "visible" state to not be reset. The code change here works around the issue, by adding an `id` prop to `VisibilityDetectingView`, which is then used to decide internally to reset the "visible" state. The `id` prop is either set from an existing `id` attribute on the element targeted by the `visible` behavior, or generated, using every behavior attributes available on the element (which means if all attributes are identical, the observed issue will remain - however unlikely to happen).
The fix also addresses another bug that was uncovered after the first resolution: we …
=> fix: `visible` behavior missing detections

src/components/hv-image/index.js, src/components/hv-text/index.js, src/components/hv-view/index.js, src/core/hyper-ref/index.js
This reverts commit dae263f4b7926ffe477024a0892ed374a8b93860, introduced in #658.
The change appears to cause regression in our mobile app. The change was a nice to have, but not a requirement for #659.
=> Revert "refactor(`HyperRef`): Remove unnecessary render cycles (#658)"

src/components/hv-date-field/index.js, src/components/hv-option/index.js, src/components/hv-switch/index.js, src/components/hv-text-field/index.js, src/services/dom/helpers.js
Remove duplicated/identical implementations of logic triggering certain behaviors on elements.
Note: hv-alert, hv-list and `hyper-ref` still have their own custom implementation of selecting/executing behaviors.
=> refactor: de-dup behavior trigger logic

src/core/components/hv-screen/index.js
I found the following functionality:
- dom (level 1-3) will return an empty string if the attribute is missing or has no value: https://www.w3.org/TR/DOM-Level-3-Core/core.html#ID-666EE0F9
- dom (level 4) will return null if the attribute is not present: https://dom.spec.whatwg.org/#dom-element-getattribute
The definition in dom v4 appears as
[DOMString](https://webidl.spec.whatwg.org/#idl-DOMString)? [getAttribute](https://dom.spec.whatwg.org/#dom-element-getattribute)([DOMString](https://webidl.spec.whatwg.org/#idl-DOMString) [qualifiedName](https://dom.spec.whatwg.org/#dom-element-getattribute-qualifiedname-qualifiedname));
It seems most prudent to check for
- null, undefined (level 4)
- empty string (level 1-3)
- hash (Hyperview)
Closes …
=> fix(reload) - Reload should not require an href value

src/components/hv-picker-field/index.ios.js
Remove `field-style` stylesheet that was applied to the intermediate view wrapping the picker - this style is already applied to the actual field UI (see src/components/hv-picker-field/field/index.js), and its presence is causing improper rendering in Instawork mobile app.
This issue was introduced by recent refactor in #633 
| Before | After | Sanity check with Demo app |
|-------|--------|----------|
| ![before](https://github.com/Instawork/hyperview/assets/309515/a785ef6e-6bd0-4557-808d-7d1c641426fd) | ![after](https://github.com/Instawork/hyperview/assets/309515/1918604a-5e37-4e5a-96a6-3a93865b3692) | ![demo](https://github.com/Instawork/hyperview/assets/309515/20f977e1-b7dd-4c2f-bdea-f193fc76dcae) |
=> fix(picker-field): Unwanted style

src/components/hv-list/index.js, src/components/hv-section-list/index.js, src/core/components/hv-root/index.tsx, src/core/components/hv-screen/index.js
`RefreshControl` context allows for customizing the refresh control in `<list>` and `<section-list>`. Consumers were setup in a React class component fashion, using the static `contextType` property. This approach is limiting, as only one context can be set on a given class component, but is necessary when the context needs to be accessed outside the render method. Since this is not the case for either of these classes, refactor to use the JSX consumer style in the render methods, which now leaves room for introducing another context (future PR coming soon) that does need to be accessed outside the render method. Additionally, this re-adds the missing `refreshControl` property being passed down from `hv-root` to `hv-screen`.
| `<list>` | `<section-list>` |
|-------|-----------|
| …
=> refactor: `RefreshControl` context

docs/reference_behavior_scroll.md, examples/advanced_behaviors/scroll/index.xml.njk, examples/advanced_behaviors/scroll/list.xml.njk, examples/advanced_behaviors/scroll/section_list.xml.njk, examples/advanced_behaviors/scroll/section_list_deprecated.xml.njk, schema/core.xsd, schema/hyperview.xsd, schema/scroll.xsd, src/components/hv-list/index.js, src/components/hv-list/types.js, src/components/hv-section-list/index.js, src/components/hv-section-list/types.js, src/contexts/index.ts, src/core/components/hv-root/index.tsx, src/core/components/hv-screen/index.js, src/services/dom/helpers.js, src/services/namespaces/index.js
Add new behavior action `scroll`, that scrolls a `<list>` or `<section-list>` to desired `target`. Implementing the same support as part of scrollable views is a larger effort, so we'll postpone this until needed.
See included list and section list examples for usage.
TODO:
| iOS | Android |
|-----|--------|
| ![iOS](https://github.com/Instawork/hyperview/assets/309515/8db0d69a-1b65-44fe-b5f0-f1f28431f96e) | ![android](https://github.com/Instawork/hyperview/assets/309515/abce676d-be61-4a18-a2ed-50943ccd441c) |
=> feat(lists): `scroll` behavior action

docs/reference_textfield.md, examples/ui_elements/forms/text_input/index.xml.njk, schema/core.xsd
Add missing keyboard modes available to `<text-field>` via the attribute `keyboard-type`
https://github.com/Instawork/hyperview/assets/309515/2022b574-7957-4470-a2a6-664b796195dd
=> chore(docs): Additional keyboard types

examples/case_studies/contacts/index.xml.njk, examples/case_studies/contacts/list.xml.njk
Now that scroll behavior is supported, remove hack that reloaded the entire list on search to re-index the scroll position.
=> chore(examples): Update contacts case study

src/components/hv-text-field/index.js
When the component backing the `<text-field>` element re-rendered with a new `element` prop, the state previously set locally is lost, causing the styles to no longer apply the `focused` modifier. This fix removes the local DOM state for `focused`, and instead reads the state from the actual RN component.
|-------|-------|
| ![before](https://github.com/Instawork/hyperview/assets/309515/a65e5830-123b-41ad-a8da-28fbb6708dc1) | ![after](https://github.com/Instawork/hyperview/assets/309515/b2c848aa-ee9b-4709-9ac1-04a62f3094b7) |
=> fix(`hv-text-field`): `focused` state

schema/core.xsd
Eventhough the `debounce` attribute is limited to `<text-field>`, it can be applied to `<behavior>` elements nested under a `<text-field>`. Right now our schema definition does not have this level of granularity to restrict the attribute to elements nested under another kind of element.
=> fix(schema): move `debounce` attribute to `behaviorAttributes`

demo/src/Navigator.js
Resolves safe area handling for Android. iOS should work the same as before.
Uses the approach [recommended by react-navigation](https://reactnavigation.org/docs/7.x/handling-safe-area/) (including not using `SafeAreaView`)
Tested on iOS simulator and Android device
| | IOS | Android |
| --- | --- | --- |
| before | ![ios-original](https://github.com/Instawork/hyperview/assets/127122858/564f98a0-5916-48ec-9879-2bfce6d24733) | ![android-original](https://github.com/Instawork/hyperview/assets/127122858/8366bb07-b8b5-4005-ab64-b019f3315db4) |
| after | ![ios-safe-area](https://github.com/Instawork/hyperview/assets/127122858/7e7dc943-67a9-4fd5-bc43-3487aa3f43ba) | ![android-safe-area](https://github.com/Instawork/hyperview/assets/127122858/c57aba46-3603-42e8-86c6-bb1904a14fd4) |
Asana: …
=> fix(safe area) - adding safe area to demo

.eslintrc
Warn instead of erroring if stories are missing for core components. Related to https://github.com/Instawork/eslint-plugin-instawork/pull/43 where we're expanding the matcher to any `components/`
=> Fix: Ignore stories rule for core components

src/core/components/hv-navigator/index.tsx, src/core/components/navigator-stack/index.tsx, src/core/components/navigator-stack/router.tsx, src/core/components/navigator-stack/types.ts, src/core/components/navigator-tab/index.tsx, src/core/components/navigator-tab/types.tsx
This is a working prototype of deep links with custom navigators.
- For stack navigators, the custom navigator provides an injection of a custom router which overrides the behavior of initial state and updates for new routes
- In the override, all routes are pushed onto the stack
- For tab navigators, the custom navigator calls a 'navigate' whenever the initial route name prop changes
This functionality requires mobile branch https://github.com/Instawork/mobile/tree/hardin/deep-link-url-wip
**Tabs**
With the default behavior, the initial state is correct: shifts-route (middle tab), and second-shifts (right sub tab). However, the deep link has no effect. The current tab selection remains.
Deep link
```xml
<doc {% namespaces %}>
<navigator id="root-navigator" type="stack" merge="true"> …
```
=> feature(deep link) - provide deep link support for navigation

.eslintrc, src/contexts/index.ts, src/contexts/navigator-map.tsx, src/core/components/hv-navigator/index.tsx, src/core/components/hv-navigator/types.ts, src/core/components/hv-route/index.tsx, src/core/components/hv-route/types.ts, src/core/components/hv-screen/types.ts, src/services/dom.d.ts, src/services/dom/helpers-legacy.ts, src/services/keyboard/index.ts, src/services/navigator/helpers.test.ts, src/services/navigator/helpers.ts, src/services/stylesheets.d.ts, src/types-legacy.ts, tsconfig.json
Instead of redefining DOM types, rely on the official library.
Note:
In b5d1e7b3e6111cd10bb116e6f083794295125811, we're explicitly defining the libs to import in TS. The list of sources applied are existing sources from the extended file (`@tsconfig/react-native/tsconfig.json`) with one addition, `dom`, which allows for global definition of DOM types. In our previous work updating to TS, we didn't needed to define this, likely because we already had TS code importing types from xmldom library, which itself imports the `dom` library.
This override is only needed for the time being to keep tests passing. We should be able to remove the override before the final merge.
=> chore(ts): remove explicit DOM types

package.json, src/components/hv-date-field/index.tsx, src/components/hv-date-field/types.ts, yarn.lock
These libraries are used in the demo app and Instawork apps, but the versions we currently had in Hyperview were old and defining incompatible types.
=> chore: update library versions

scripts/sync/index.js, src/core/components/hv-screen/types.ts, src/core/components/keyboard-aware-scroll-view/index.d.ts, tsconfig.json
- Update sync script to point to index.ts instead of index.js
- Make navigation prop type explicitely loose to prevent conflicts with demo app
- Remove duplicated type file
- Ignore demo/ directory when validating types of Hyperview library
=> chore(ts): more clean up and fixes

package.json
This was inadvertently changed in #604 - revert it back to point to the transpiled version by default
=> fix: revert package.json `main` field

src/components/hv-switch/style-sheet/index.ts
Revert [a change that occured during the migration](https://github.com/Instawork/hyperview/pull/693/commits/8eb6a6442a6beea35d80470227cc5d8084498046#diff-d610e5fb53e9820675e03e4d336b6a1a210e78863d68e344182b8cc31d9afda6), which changed the underlying helper used to convert the switch color on Android.
Note: as we cannot resolve the type correctly, I'm temporarily adding an ignore statement to satisfy TS. We will rework the switch implementation in an upcoming refactor, and we should revise how the color styles are applied / what functions from RN we use for this.
|--------|------|
| <img width="559" alt="Screenshot 2023-10-16 at 1 09 25 PM" src="https://github.com/Instawork/hyperview/assets/309515/fe9c5665-2318-43e1-9832-ac7f20a85036"> | <img width="559" alt="Screenshot …
=> fix: Android switch color

src/behaviors/index.ts, src/contexts/navigation.ts, src/core/components/hv-root/index.tsx, src/core/components/hv-route/index.tsx, src/core/components/hv-route/types.ts, src/core/components/hv-screen/index.js, src/core/components/hv-screen/types.ts, src/services/behaviors/index.ts, src/types.ts
Follow the commits for the individual steps taken
- moved the 'once' handling methods into /services/behaviors
- updated `BehaviorOptions` to properly reflect the state of the data
- created new `RootOnUpdate` and `OnUpdateCallbacks` types
- added `onUpdate` to all props which occur from `hv-root` to `hv-screen`
- ported the `onUpdate` method and all of its related methods from `hv-screen` to `hv-root`
- use the callbacks prop to inject any of the instance-specific callbacks needed for the `onUpdate`
- inject the new `onUpdate` into the props
Asana: https://app.asana.com/0/1204008699308084/1205741965789634/f
=> chore(on update): lift onUpdate and its methods from hv-screen to hv-root

src/behaviors/hv-hide/index.ts, src/behaviors/hv-select-all/index.ts, src/behaviors/hv-set-value/index.ts, src/behaviors/hv-show/index.ts, src/behaviors/hv-toggle/index.ts, src/behaviors/hv-unselect-all/index.ts, src/core/components/hv-root/index.tsx, src/types.ts
Both `hv-screen` and `hv-route` have the potential to have a null `doc` in state. This can happen from a bad load, or from an override document being provided by a parent component.
The code used in `onUpdate` and its related methods were not accounting for the possibility of a null `doc'.
- Updated `ScreenState` to reflect the values of the state as assigned in `hv-screen`
- Updated callback signature to allow `getDoc` to return null
- Updated `hv-root` implementation of `onUpdate` and related to account for null doc
- Updated `HvGetRoot` to account for null doc
- Updated behavior implementations which used `HvGetRoot` to account for null doc
Asana: https://app.asana.com/0/0/1205741965789643/f
=> chore(document): account for possible null doc in state

src/contexts/index.ts, src/core/components/hv-navigator/types.ts, src/core/components/hv-root/index.tsx, src/core/components/hv-route/index.tsx, src/core/components/hv-route/types.ts, src/services/navigator/index.ts, src/types.ts
Implement `hv-route` as a provider of `onUpdate` to allow navigators to process behaviors
Only routes which own a document are providers, any children which do not own a document will inherit.
Asana: https://app.asana.com/0/1204008699308084/1205741965789637/f
=> chore(hvroute): hvroute as an onUpdate provider for navigator

src/core/components/hv-navigator/index.tsx
Deep link requests were not properly triggering navigation events like tab selections. Behaviors continued to work as expected.
Cause:
There was a chunk of code which was calling `useContext` in the hv-navigator for two contexts. The result of these were not being used so [the code was removed](https://github.com/Instawork/hyperview/pull/701/commits/f3e25c0ae8a3f570387c3727bb094a086fa684ae). Without that context, the `useEffect` of the custom navigators doesn't fire.
Adding it back as part of the hierarchy restores the functionality.
In the videos below, the deep link should cause a selection of the "Accounts" tab.
| -- | -- |
| ![before](https://github.com/Instawork/hyperview/assets/127122858/268e58a2-5beb-4dea-b554-eb5328bd6df9) | …
=> fix: deep link urls are not triggering navigation events

schema/core.xsd
Changing the <navigator> child type from `sequence` to `choice` to allow flexibility in the ordering of `<nav-route>` and `<behavior>` elements.
=> chore: update <navigator> schema for flexible ordering

src/contexts/navigation.ts, src/core/components/hv-root/index.tsx, src/core/components/hv-route/index.tsx, src/core/components/hv-route/types.ts, src/core/components/hv-screen/index.js, src/core/components/hv-screen/types.ts, src/types.ts
When the reload functionality was moved into `<hv-root>` the local reload functionality was broken in `<hv-screen>`
Relates to https://github.com/Instawork/hyperview/pull/727
Resolves https://github.com/Instawork/hyperview/issues/737
Asana: https://app.asana.com/0/1204008699308084/1205859670749796/f
| -- | -- |
| ![before](https://github.com/Instawork/hyperview/assets/127122858/1f2173a3-aea6-4474-8ec8-e392e592cf16) | ![after](https://github.com/Instawork/hyperview/assets/127122858/1e0dbdba-472c-496c-b552-4efbe1ce6a47) |
=> fix: reload button broken in error screens

src/core/components/hv-screen/index.js
The order of the callback injection was wrong from [PR](https://github.com/Instawork/hyperview/pull/739). Which could cause the wrong callbacks to be used in onUpdate() calls.
Relates to https://github.com/Instawork/hyperview/pull/739
Asana: https://app.asana.com/0/1204008699308084/1205908537013919/f
=> fix: update callback injection in hv-screen

src/core/components/hv-root/index.tsx, src/core/components/hv-screen/index.js, src/types.ts
Simplifying the signature and call to `reload` to use the update callbacks from options rather than as a separate param.
Asana: https://app.asana.com/0/1204008699308084/1205888765821732/f
https://github.com/Instawork/hyperview/assets/127122858/1ef6092b-e4ad-42bf-bc3a-2062ef772c2f
=> chore: clean up reload signature

src/contexts/navigation.ts, src/core/components/hv-navigator/index.tsx, src/core/components/hv-navigator/types.ts, src/core/components/hv-root/index.tsx, src/core/components/hv-route/index.tsx, src/core/components/hv-route/types.ts, src/core/components/hv-screen/types.ts, src/types.ts
Allow navigation actions to report the blur/focus state of each route. The entire `route` object is returned. This is a combination of
- Elements injected by react-navigation (key and maybe other values)
- Elements injected by Hyperview (params)
- The `id` is pulled from the `<nav-route>` attribute in the navigation structure.
- The `url` is from either the `<nav-route>` `url` attribute or from the `href` passed in a `<behavior>`
The `id` will be undefined for any navigation events which occur from `<behavior>` triggers.
The 'url' will be undefined for any `<nav-route>` which does not define an `href` value.
I have verified that the listeners are properly cleaned and resubscribed without causing duplicate listeners.
Asana: https://app.asana.com/0/1204008699308084/1205094358200852/f …
=> feat: report route focus and blur events

src/core/components/hv-root/index.tsx
Added a missing option into the navigation call.
| -- | -- |
| ![before](https://github.com/Instawork/hyperview/assets/127122858/fed81afa-fb29-4e1e-95d1-9eeafab11b3a) | ![after](https://github.com/Instawork/hyperview/assets/127122858/a8729133-ac76-47a1-93d4-17bf61b5b699) |
Asana: https://app.asana.com/0/1204008699308084/1205908539633327/f
=> fix: loading screens not working

src/core/components/hv-route/index.tsx
When viewing a modal screen from a deep link, the url was loaded three times.
Background: when a modal is defined in Hyperview navigation XML schema, we can include a designation of "modal=true". When true, Hyperview will automatically create a stack navigator to contain the modal so that any additional navigation actions from the modal are contained within its own stack.
Cause: the original route was continuing to call a url load in the middle of the render cycle for the new stack navigator causing a state refresh multiple times.
Fix: ensure that routes which are defined as modal don't trigger their own load action (the child modal screen will have a unique name).
**Code explanation**
Given a (simplified) document input
```xml
<doc>
<navigator id="root-navigator" type="stack">
<nav-route …
```
=> fix: deep link modals trigger too many page loads

src/services/dom/helpers.ts, src/services/navigator/helpers.test.ts, src/services/navigator/helpers.ts
When an existing structure exists and a deep link comes in, merging must take into account that the document structure has changed:
1. The primary element may change from a <navigator> to a <screen> or vice versa
2. Any navigator could change types (stack, tab)
These changes validate the incoming type matches the existing. In the case of mismatches, the incoming data replaces existing.
Commits were performed sequentially for easier visibility.
Example below uses an error page to illustrate the issue.
| -- | -- |
| ![before](https://github.com/Instawork/hyperview/assets/127122858/fb7f4bcc-21a9-4adb-86cd-0f1666143a9b) | ![after](https://github.com/Instawork/hyperview/assets/127122858/0d46746a-c4e2-4494-a6b3-422d4b3f73c8) |
Asana: …
=> fix: deep link merging

src/contexts/index.ts, src/core/components/hv-route/index.tsx, src/core/components/navigator-stack/helpers.test.ts, src/core/components/navigator-stack/helpers.ts, src/core/components/navigator-stack/index.tsx, src/core/components/navigator-stack/router.tsx, src/core/components/navigator-stack/types.ts, src/services/navigator/helpers.test.ts, src/services/navigator/helpers.ts, src/services/navigator/index.ts, src/services/navigator/types.ts
An issue was identified where the deep link state of a stack navigator could be handled incorrectly when the incoming navigation didn't include changes to the stack navigator. At the same time, we decided to improve the logic of incoming state affects existing state.
We determined that in cases where a user has already opened views, and they match the order of the incoming deep link, they can remain with their existing state. For example:
- user clicks "company", then views deep link "company"
- in this case, the user's action is identical to the deep link so their view remains including any existing state
This shows the original bug finding and its resolution
| -- | -- |
| ![before](https://github.com/Instawork/hyperview/assets/127122858/aa824aba-0673-4f46-84b6-8070b9be …
=> fix: deep link state handling

src/core/components/navigator-stack/helpers.test.ts, src/core/components/navigator-stack/helpers.ts
When a deep link is processed which does not set a new tab, the existing tab should remain selected.
The logic which checked for presentation changes wasn't accounting for routes which aren't dynamically added.
| -- | -- |
| ![before](https://github.com/Instawork/hyperview/assets/127122858/7b5bab08-7548-40b9-ac5c-827515bc37a3) | ![after](https://github.com/Instawork/hyperview/assets/127122858/268f00d2-630c-4724-ad4a-9822ee149e16) |
Asana: https://app.asana.com/0/1204008699308084/1205979074786687/f
=> fix: tab reset with deep link

.eslintrc, demo/src/HandleBack.ts, demo/src/HyperviewScreen.tsx, src/components/hv-date-field/field/types.ts, src/contexts/navigation.ts, src/core/components/modal/types.ts, src/core/components/navigator-stack/index.tsx, src/types.ts
Manually removed extra spaces.
Added `padding-line-between-statements` linting rule to error when there's spaces between imports. Comments or linting overrides are allowed.
Rule info:
- https://typescript-eslint.io/rules/padding-line-between-statements/
- https://eslint.org/docs/latest/rules/padding-line-between-statements#rule-details
https://github.com/Instawork/hyperview/assets/127122858/1106233c-424d-4df2-929a-3d72857b020b
Asana: https://app.asana.com/0/1204323441804469/1205761921034729/f
=> chore: clean up import spaces

src/components/hv-date-field/index.test.ts, src/components/hv-date-field/index.tsx
Fixes #757 
Previously, dates where the month is a single digit (January – September / 1 - 9) created formatted dates like `2023-1-27`. This would break parsing the date as an ISO string in certain languages.
This PR pads the month part with a leading zero to make it correctly formatted as `YYYY-MM-DD`.
=> fix: format single digit months in date-field

src/core/components/hv-navigator/index.tsx
When the component is re-rendered, there was a possibility of adding a duplicate node into the DOM.
This is a follow up to the work from https://github.com/Instawork/hyperview/pull/760
Asana: https://app.asana.com/0/1204008699308084/1206058760311122/f
=> fix: avoid multiple DOM mutations for dynamic stack navigator

src/components/hv-list/index.tsx, src/components/hv-section-list/index.tsx
Check for the "refresh" trigger before adding the <RefreshControl> to `list` and `section-list`.
Confirmed in Pro app and HV Demo.
Fixes https://instawork.sentry.io/issues/4682025463/
Fixes https://instawork.sentry.io/issues/4585045549/
Sentry: this should resolve any of the `Error: No href passed to fetchElement` errors which contain `hyperview/worker_app/helpdesk-parent` at the end of the breadcrumbs.
| -- | -- |
| ![before](https://github.com/Instawork/hyperview/assets/127122858/edfab479-4471-462a-8aec-eb4be370cdb3) | ![after](https://github.com/Instawork/hyperview/assets/127122858/676cd54d-2abc-4f95-ba83-6ee6c05786fa) |
Asana: https://app.asana.com/0/1204008699308084/1206114436157353/f
=> fix: refresh control should only be added when a refresh trigger exists

src/core/components/hv-route/index.tsx
This function is no longer relevant. It was used to override the returned state when a deep link changed the hierarchy and the state should no longer return a document. This functionality is out of date because:
- The class no longer owns its state
- The class is wrapped with a state context based on the presence of an element
=> chore: cleanup hv-route state

src/core/components/hv-route/index.tsx, src/core/components/hv-route/types.ts
Moving the props out of the class into the FC as a first step in externalizing the onUpdate.
=> chore: externalize hv-route props

src/contexts/index.ts, src/core/components/hv-route/index.tsx
The onUpdate context is no longer needed but was passing a default implementation down to children. Removing the context and using the onUpdate passed by props resolves the bug and cleans up the code.
Asana: https://app.asana.com/0/1204008699308084/1206198337202880/f
=> fix: deep links with behaviors are failing to trigger

src/behaviors/hv-hide/index.ts, src/behaviors/hv-select-all/index.ts, src/behaviors/hv-set-value/index.ts, src/behaviors/hv-show/index.ts, src/behaviors/hv-toggle/index.ts, src/behaviors/hv-unselect-all/index.ts, src/components/hv-list/index.tsx, src/components/hv-section-list/index.tsx, src/core/components/hv-navigator/index.tsx, src/core/components/hv-root/index.tsx, src/services/behaviors/index.ts, src/services/dom/errors.ts, src/services/dom/helpers.ts
Attempting to reduce getElementById errors by evaluating whether the passed object is an element. Barring success, improve error logs to include the id being retrieved.
The bug is not easily reproducible locally, putting this into the next release should give us more information into what's happening.
Example of the existing error: https://instawork.sentry.io/issues/4653618920/?query=getElementById&referrer=issue-stream&sort=freq&statsPeriod=30d&stream_index=1
Asana: https://app.asana.com/0/1204008699308084/1205467413007358/f
=> fix: getElementById errors

src/core/components/hv-route/index.tsx
Dimpal reported an issue with live shift booking. Passing the hv-route's onUpdate was causing the wrong document to be targeted in behaviors.
Asana: https://app.asana.com/0/0/1206225556817618/f
=> fix: replacement behavior issue

src/core/components/hv-route/index.tsx
Dimpal reported an issue with retriggering the same deep link multiple times.
The route was using the wrong document to perform focus and cleanup tasks.
Asana: https://app.asana.com/0/1204008699308084/1206225556817630/f
=> fix: deep link retriggers

src/core/components/hv-route/index.tsx, src/core/components/hv-route/types.ts
The fixes required for https://github.com/Instawork/hyperview/pull/783 and https://github.com/Instawork/hyperview/pull/785 necessitated a change to how the navigator accesses an onUpdate. It is now passed as a unique name to avoid collision with other functionality.
Asana: https://app.asana.com/0/1204008699308084/1206320269516407/f
=> fix: navigator load behaviors

src/core/components/hv-doc/index.tsx, src/core/components/hv-root/index.tsx, src/core/components/hv-route/index.tsx, src/core/components/hv-route/types.ts, src/core/components/hv-screen/index.js, src/types.ts
Fixing an issue where reload behaviors didn't reload content.
The issue found was that the state set in hv-root did not cause the hv-screen to update. This meant the `componentDidUpdate` was never fired so the "needsLoad" value wasn't evaluated to cause a reload.
The fix is to remove the setting of "needsLoad" from within hv-root and replace it with an explicit call to load.
A separate task has been created to evaluate ways to remove the "needsLoad" from hv-screen and hv-route. https://app.asana.com/0/1204323441804469/1206385492929255/f
| -- | -- |
| ![before](https://github.com/Instawork/hyperview/assets/127122858/8cba50de-0ab9-4016-bd3e-4989aa1dd050) | ![after](https://github.com/Instawork/hyperview/assets/127122858/ba030c47-4a92-43c8-9ebf-8c0a5a7a7eca) |
| …
=> fix: reload not triggering a load

src/contexts/back-behaviors.test.ts, src/contexts/back-behaviors.tsx, src/core/components/hv-root/index.tsx, src/core/components/hv-route/index.tsx, src/core/hyper-ref/index.tsx, src/services/navigator/types.ts, src/types.ts
Re-working the support for back navigation control with a simplified approach.
- added new "back" trigger
- added new "BackBehaviorContext" to manage a behavior registry and store the current 'onUpdate' which will handle the behaviors
- modified hyper-ref to register/deregister its 'trigger=back' behaviors along with its 'onUpdate'
- wrapped all instances of 'hv-route' with a BackBehaviorContext and also wrapped the standalone hv-screen
Tested in iOS simulator for Pro and Partner app
- Pro app won't currently support the feature but its addition doesn't break anything
- Partner app was tested with 'back' behaviors in place and omitted and worked as expected
Verified the following test setups:
```XML
<view id="back-container">
<behavior
trigger="back"
action="hide"
target="back-container" …
```
=> feature: Adding support for blocking close/back navigation

src/components/hv-list/index.tsx
As reported in https://github.com/Instawork/hyperview/issues/776 the scroll to target was broken during TS migration.
Updated how the doc is retrieved from the updated DocContext.
Asana: https://app.asana.com/0/1204008699308084/1206433111684039/f
| -- | -- |
| ![before](https://github.com/Instawork/hyperview/assets/127122858/b34e09a8-0dc1-40e4-835e-bfadfb417a50) | ![after](https://github.com/Instawork/hyperview/assets/127122858/d8aadfff-ecd3-46f2-a22f-50ae3c2d481c) |
=> fix: scroll to target

src/core/components/hv-root/index.tsx, src/core/components/hv-root/types.ts, src/core/components/hv-screen/types.ts
In current release, HvRoot is sharing the same props as HvScreen. Some recent required props for HvScreen are causing HvRoot to include required props which it doesn't need.
Separating the two props out allows HvRoot to only require the external dependencies.
Asana: https://app.asana.com/0/1204008699308084/1206433111684035/f
=> chore: separate props from HvRoot and HvScreen

src/core/components/hv-route/index.tsx
Removing the prop spreading between the functional component and the class component
Asana: https://app.asana.com/0/1204008699308084/1206433111684027/f
=> chore: remove HvRoute prop spreading

docs/reference_behavior_attributes.md, docs/reference_screen.md
Hyperview does not support subsequent screens in navigation by adding the content of these screens in the first document loaded, this is only supported for "loading state" of subsequent screens. Originally raised in #794.
=> fix(docs): Remove ambiguous statement on `<screen>`

src/services/navigation/index.ts
The navigation service has not previously supported the delay attribute. The completion of the `navigate` is now performed after the delay (or immediately if not delay is provided).
=> chore: Add support for delaying navigate calls

examples/_includes/directory_list.xml.njk, examples/index_hyperview.xml.njk
- Updated the directory to split the "list_tag" field
- Updated the index_hyperview to look for both 'root' and 'hvroot' entries
This will allow `index_hyperview.xml` to include all of the "root" examples and will add any "hvroot" examples. The original `index.xml` will not include the "hvroot" and will therefore not provide examples it can't support.
Note: the 'navigators' section isn't yet committed, pending some additional examples.
https://github.com/Instawork/hyperview/assets/127122858/b34bca7e-12a2-4d95-b2b7-81b25a054f35
=> chore: add support for example filtering

examples/navigator/back/index.xml.njk, examples/navigator/index.xml.njk
- Created a new 'navigator' section for the examples. This section will only appear when the `Hyperview Navigator` switch is enabled
- Added an example of using the `trigger="back"` behavior
https://github.com/Instawork/hyperview/assets/127122858/1aa805c3-d1af-4ccd-8130-e273588da4a1
Asana: https://app.asana.com/0/1204008699308084/1206596675964910/f
Asana: https://app.asana.com/0/1204008699308084/1206596675964914/f
=> chore: add back trigger to examples

.circleci/config.yml, package.json, schema/core.xsd, schema/hyperview.xsd
- Added new `xmlschema` installation in circleCI
- Removed previous `xmllint` installation from circleCI
- Updated `validate-xml` test to use new `xmlschema-validation`
- Updated schema version of core.xsd and hyperview.xsd
Asana: https://app.asana.com/0/1204008699308084/1205539800446895/f
=> chore: upgrade xml validation to support schema v1.1

examples/navigator/simple_stack/index.xml.njk, examples/navigator/simple_stack/modal_1.xml.njk, examples/navigator/simple_stack/modal_2.xml.njk, examples/navigator/simple_stack/push_1.xml.njk, examples/navigator/simple_stack/push_2.xml.njk, examples/navigator/simple_stack/screen.xml.njk
Adding a simple stack navigation example. This shows developers how to create a stack navigator and how "push" and "new" behaviors respond. It also shows a navigate with href to "go back to beginning".
https://github.com/Instawork/hyperview/assets/127122858/9331dc30-4c16-4367-99b6-b50182f6044e
Asana: https://app.asana.com/0/1204008699308084/1206627007566088/f
=> chore: add simple stack example

src/core/components/navigator-tab/index.tsx, src/core/components/navigator-tab/types.tsx
Adding ability to override tab bar component.
The UI is still disabled and no component is being injected so the tab bar won't be shown yet.
=> chore(tabbar): add support for overriding the tab bar component

src/core/components/hv-navigator/index.tsx
The component props contains a nullable value: `element?: Element;`. The `buildScreens` method was expecting a valid value `element:Element`. For some reason this was not caught by TypeScript.
Updated `buildScreens` to accept a nullable element, which required switching the order of the args.
=> fix: hv-navigator buildScreens has mismatched argument signature

package.json
Was receiving the following error when running `yarn storybook`:
```
opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
library: 'digital envelope routines',
reason: 'unsupported',
code: 'ERR_OSSL_EVP_UNSUPPORTED'
```
Adding `NODE_OPTIONS=--openssl-legacy-provider` before starting the storybook server resolves the issue
=> fix: storybook fails with newer Node.js

schema/core.xsd
Using assertion to improve validation of <nav-route> structure:
- href is required and should contain non-empty string
- or
- nav-route has a navigator child
Asana: https://app.asana.com/0/1206623701273671/1206623701273674/f
=> chore(xml validation): improve nav-route assertion

src/core/components/hv-route/index.tsx, src/services/navigator/types.ts
The tab navigator was allowing unfocused screens to block navigation because the "before remove" is applied to all open tabs in the navigator.
Use the 'isFocused()' check to ensure a screen which is not focused can't prevent back navigation.
- For tab navigators, only the active tab is focused
- For stack navigators, a modal does not defocus the screen below so it will maintain focus on multiple screens at once
In the following, the back blocker was applied only to tab-1
| --- | --- |
| ![before](https://github.com/Instawork/hyperview/assets/127122858/2c6e54bd-3b72-4ccc-8f6b-5b5e453abc88) | ![after](https://github.com/Instawork/hyperview/assets/127122858/c35fb8e9-9899-4705-841e-210e84b365eb) |
=> fix: inactive tab should not be able to block back navigation

demo/package.json, demo/yarn.lock, package.json, src/components/hv-picker-field/index.tsx, yarn.lock
Updating @react-native-picker/picker from 2.4.0 to 2.6.1
- [updated package references]()
- [chore run `yarn`]()
- [updated demo package references]()
- [chore run `yarn` in demo]()
- [Resolved Android render issues]()
On Android, starting after v2.5.1, an issue occurs where a zero font size is used for the picker. See notes: https://github.com/react-native-picker/picker/issues/536
Upgrading Expo seems to resolve the issue. However, we decided that it would be better to include a fix in our wrapper.
- A default fontSize has been added to `<Picker.item>`
- iOS is not affected by this issue and has not been changed
Illustration of bug: https://github.com/Instawork/hyperview/assets/127122858/71029ef9-c335-4ef1-bdcb-ef3272dac9b5
| v2.4.0 | v2.6.2 (w/ 16 default) |
| -- | -- |
| …
=> chore: update @react-native-picker/picker

.npmignore, package.json
Hyperview does not require transpilation anymore.
- [chore: set package main to use src instead of lib](https://github.com/Instawork/hyperview/commit/3843e7934f19ba478f5a9e8e7e0a96e627ebb52d)
- [chore: remove build script](https://github.com/Instawork/hyperview/commit/75d25c3e9d730f73f3a7c67abb614d81a1638078)
- [chore: ignore lib in future npm releases](https://github.com/Instawork/hyperview/commit/19d03b344034ccf5ee56ea2d9e7f46757c4751ee)
Tested against MDS viewer.
Asana: https://app.asana.com/0/1204008699308084/1207079738575229/f
=> chore: Remove transpilation

website/pages/en/index.js
Fixing typo in documentation.
Relates to: https://github.com/Instawork/hyperview/issues/854
Closes https://github.com/Instawork/hyperview/issues/854
=> fix (documentation): fix typo on index

src/core/components/hv-route/index.tsx, src/services/navigator/helpers.ts, src/services/navigator/index.ts
Resolving several issues found when implementing navigation in the pro app:
- Screens which call a "back" while a modal is open should not close the modal
- The "close" action should close the modal, even if it not the currently focused screen
- The updated href for "close" or "back" should be passed to the route which appears after the back/close
This is a replacement for
- https://github.com/Instawork/hyperview/pull/848
- https://github.com/Instawork/hyperview/pull/838
Testing for this has been provided in https://github.com/Instawork/mobile/tree/florent/pro-app-hv-nav
Asana: https://app.asana.com/0/1204008699308084/1207250244181411/f
=> fix(navigation): resolve close and back behavior issues

docs/guide_navigation.md
- Adding an `Initial state` section to the guide
- Cleaned up the navigator and route definitions
- Fixed example numbering
=> chore (documentation): add initial state section

src/core/components/hv-route/index.tsx, src/services/navigator/helpers.ts, src/services/navigator/index.ts, src/services/navigator/types.ts
When navigating between multiple screens, if the url is updated in a screen, that change is lost when navigating away and back again.
**Resolution:**
Ensure the DOM is updated with the new href value
| --- | --- |
| ![before](https://github.com/Instawork/hyperview/assets/127122858/032d88ac-0099-44ee-9def-59b1d3af3911) | ![after](https://github.com/Instawork/hyperview/assets/127122858/75aac815-4094-48d7-aba8-380ed554cbde) |
Asana: https://app.asana.com/0/1204008699308084/1207291078589952/f
=> fix: url is reverted after navigation change

src/core/components/hv-route/index.tsx, src/core/components/hv-screen/index.js
HvRoute should not load new documents once an HvScreen has been created. The HvScreen will handle its own reloads.
Asana: https://app.asana.com/0/1204008699308084/1207291078589952/f
=> fix: avoid duplicate loads

src/components/hv-select-single/index.ts
HvSelectSingle component's on select function does not parse allow-deselect properly.
Right now, setting allow-deselect to any value causes the option to be de-selectable. It should only be the case when the attribute is set to true
Asana ticket:
https://app.asana.com/0/1204008699308084/1207361925394121/f
Fix:
1. check if allowDeselect === "true" rather than just asserting on allowDeselect
Testing:
1. open file: hyperview/examples/ui_elements/forms/select_single/index.xml.njk and set allow-deselect = "asdf"
2. Open the Hyperview demo app. UI Elements > Forms > Single Select
3. Test the changes for the "Optional Select" select group by selecting an option.
4. Deselect should not work as allow-deselect is set to arbitary string.
5. Perform steps 1-5 by setting allow-deselect = "true". …
=> Fix: Parse <select-single>'s allowDeselect attribute correctly

src/core/components/hv-screen/index.js, src/core/components/load-element-error/styles.ts
The internal `load-element-error` component was rendering at the bottom of the HVScreen. In applications which use ReactNavigation's tab bars, the bottom of the screen was above the tab bar. When tabs are rendered within the screen, the component floated part way up the tab bar (see 'original' below).
By moving the error to the top of the screen and pushing content down, we retain safe area boundaries and avoid floating over existing content.
| Original | Updated |
| -- | -- |
| ![shifts-before](https://github.com/Instawork/hyperview/assets/127122858/519c878c-1ef9-4983-90bd-7700cd7cae36) | ![updated](https://github.com/Instawork/hyperview/assets/127122858/db0b59d1-e45b-4801-81fe-de8cd2e1d83f) |
The following show a few other examples of how the change affects screen appearance.
| …
=> fix (error component): error component is covering tabor

src/core/components/hv-route/index.tsx
When HVScreens are rendered outside of normal inheritance chains, the navigation property may be missing. This update allows Hyperview to automatically inject a higher-level navigation property into the new screen.
Works by using ReactNavigation's context to get the navigation and only use it if:
- There is no navigation passed in via props
- The parent navigation has already been set up (has a state). This is to prevent the top-level HVRoute from also inheriting the root unnecessarily.
https://github.com/Instawork/hyperview/assets/127122858/98f95895-f456-464f-b547-93f50ff42a8f
=> feature (navigation): allow nesting navigation with broken inheritance chain

docs/reference_custom_elements.md
This fixes a typo I found in documentation.
=> Fix typo in reference_custom_elements.md

schema/core.xsd, src/components/hv-select-single/index.ts, src/components/hv-web-view/index.tsx
[Asana Ticket](https://app.asana.com/0/491474088351836/1207417081499074/f)
1. WebView might render the document before other sub-resources have finished loading
2. This forces HvWebView to show a loading spinner rendering the WebView non-interactive.
3. Adding a custom javascript snipped to close the spinner upon initial render fixes this problem
4. Added Custom handler to capture document load event
| -- | -- |
| ![before](https://github.com/Instawork/instawork/assets/171086373/53b52294-b081-4b2f-8110-2f7f6238a2af) | ![after](https://github.com/Instawork/instawork/assets/171086373/adbecc51-0dd3-456a-a7bc-1789f0920050) |
=> fix(webview): Hide webview loader when page renders before the loading of subresources

src/core/components/hv-route/index.tsx
The `useNavigation` syntax throws an exception if navigation is not found higher in the tree. This was failing some existing tests. Using the context instead provides a safe way to get the navigation if it exists and otherwise return undefined without throwing.
=> fix(navigation): get navigation from higher in the tree

src/core/components/hv-screen/index.js, src/core/components/load-element-error/index.tsx, src/core/components/load-element-error/styles.ts, src/core/components/load-element-error/types.ts
- Moved the component to the top
- Use top padding to provide safe area for Android
- Add a close button to dismiss the component
Android shows the close action, iOS shows the reload action.
| Android | iOS |
| -- | -- |
| ![android](https://github.com/Instawork/hyperview/assets/127122858/cf51e118-c1cf-4484-b425-efaec4b52c02) | ![iOS](https://github.com/Instawork/hyperview/assets/127122858/b9b9a080-4fdd-4ff6-8370-2cd7c6f96e0c) |
Asana: https://app.asana.com/0/1204008699308084/1207426043394013/f
=> fix(error): improve error component placement

src/services/logging/default-logger.ts, src/services/logging/index.ts, src/services/logging/tostring-helper.test.ts, src/services/logging/tostring-helper.ts
The new logging system supports filtering out logs. In some places in the code, an expensive operation is implemented to pass data into the log. If the log is not dispatched, the expensive operation will have still run.
Create a util which allows deferring the toString() operation until the content is required.
- Supports passing `any` type
- If the passed value is a function, it will only be called when toString() is called
Example usage:
```javascript
import { deferredToString } from 'hyperview/src/services/logging';
class Logger {
log = (m?: any): void => console.log(String(m));
}
const logger = new Logger();
// Create instance of the helper, function is not called yet
const expensiveData = deferredToString(()=>{return 'expensive string process'});
// Function is called when …
```
=> feat(logging): support deferred toString() operations

src/core/hyper-ref/index.tsx, src/services/behaviors/index.ts, src/services/events/index.ts
- Remove unneeded --DEV-- block on logging in `services/events/index`
- Replaced use of --DEV-- with deferredToString in `core/hyper-ref`
- Add logs to behaviors in `services/behaviors`
- Updated severity of `[on-event]` and `[dispatch-event]` to INFO to match new behavior logs.
Example logs:
```
INFO  [behavior] | action: toggle | ["<view action=\"toggle\" delay=\"1000\" show-during-load=\"toggle3-spinner\" style=\"Button\" target=\"toggle3-content\" ran-once=\"true\" xmlns=\"https://hyperview.org/hyperview\"/>"]
INFO  [behavior] | action: copy-to-clipboard  ["<view action=\"copy-to-clipboard\" trigger=\"press\" copy-to-clipboard-value=\"Hello World\" style=\"Button\" ran-once=\"true\" xmlns=\"https://hyperview.org/hyperview\">
<text style=\"Button__Label\">Copy to clipboard</text> …
```
=> chore(logging): improve logging

src/services/logging/default-logger.ts, src/services/logging/tostring-helper.ts
Forcing all params in DefaultLogger to string caused any objects to be converted to `[object Object]` making it impossible to inspect the element in Chrome.
Checking whether `toString` was available yielded false positive as all objects contain this function.
**Solution**
Relying on `instanceof` to ensure only `ToStringHelper` params are converted.
Before
After
=> fix(logging): object debugging

src/core/components/hv-navigator/index.tsx
When navigating to a new root navigation structure, we are seeing a push animation as if the new structure is being pushed onto the stack.
Using the index of the defined screens, the first screen will inhibit its animations. Subsequent screens will retain their correct animations.
> If a nested stack exists, it is a route within its parent so it will still animate in correctly
| -- | -- |
| ![before](https://github.com/Instawork/hyperview/assets/127122858/8917e2b9-5429-4599-a24e-f944a918ce86) | ![after](https://github.com/Instawork/hyperview/assets/127122858/e4c9c7a4-3152-493b-843a-7b9b3e66854a) |
Example navigating beyond the initial reload
Asana: https://app.asana.com/0/1204008699308084/1205888766113004/f
=> chore(navigation): skip animation for first stack screen

src/core/hyper-ref/index.tsx, src/services/behaviors/index.ts
Logs for behaviors are resulting in lengthy console logs when the element has children. Remove the children from the cloned element prior to serializing.
Before:
```xml
INFO  2024-07-22T18:39:19.909Z | core-mobile/src/components/hyperview | [behavior] | action: add-styles | <behavior trigger="load" immediate="true" once="true" action="add-styles" ran-once="true" xmlns="https://hyperview.org/hyperview">
<styles>
</styles>
</behavior>
INFO  2024-07-22T18:39:19.777Z | core-mobile/src/components/hyperview | [on-event] trigger [ open-gigs-money-cta-call ] caught by:  <behavior trigger="on-event" event-name="open-gigs-money-cta-call" action="replace" target="money-cta-open-gigs" href="/worker_app/earnings-tab/open-gigs-iw-card-cta" xmlns="https://hyperview.org/hyperview"/>
```
After:
```xml …
```
=> chore(logging): reduce length of behavior logs

test/helpers.tsx
Default `onUpdate` prop to NOOP and allow consumer to set it. This helps solving an issue where the component is serialized by storybook, but the returned structure by `action` is not serializable.
=> fix(test-helpers): `onUpdate` prop

examples/advanced_behaviors/set_value/index.xml.njk, src/components/hv-text-field/index.tsx
React to text-field value being changed from props, and correctly call change handler.
Relates to #914.
Note - we currently have only two field types that support "change" event: `text-field` and `switch`. This PR only addresses the issue with `text-field` as this component was already migrated to a functional component, and the use of `useEffect`/`useRef` is trivial. Follow up needed:
- The switch component should be refactored to a functional component, then implement the same fix
- The "change" behavior trigger should be extended to other type of fields (related: https://github.com/Instawork/hyperview/issues/298)
https://github.com/user-attachments/assets/105fb0ac-9239-480a-b86c-e1234a07b28a
=> fix(text-field): `set-value` triggers `change` behaviors

docs/example_live.md, website/sidebars.json
Add new page that renders an iframe pointing to our web demo app.
=> feat(docs): render live demo app

src/core/components/hv-route/index.tsx, src/core/components/hv-route/types.ts
This change corrects the issue in Hyperview which makes the experience inconsistent. A separate PR will be raised in the `mobile` repo to change the error behavior.
hv-route was not properly forwarding the `onError` to the inner `route` component. This caused an inconsistent error behavior between `hyperview_navigation_pro_app` experiment enabled and disabled.
| | Experiment On | Experiment Off |
| - | -- | -- |
| Before | <img width="697" alt="before-on" src="https://github.com/user-attachments/assets/c3b1181c-3642-4366-8916-f6f3849ac78a"> | <img width="697" alt="before-off" src="https://github.com/user-attachments/assets/6feda32a-4a20-42a9-8b3e-904037485de0"> |
| After | <img width="697" alt="after-on" src="https://github.com/user-attachments/assets/76112a2b-1d34-41e0-b291-e1fb52b211f5"> …
=> chore(error): supply onError to hv-route

src/services/navigator/index.ts
To reduce the number of unique warnings in Sentry, removing the `targetId` from the warning. Added a new `info` with the received `action` and `requestParams` to allow investigation into the cause of the warning.
Asana: https://app.asana.com/0/1204008699308084/1208227730998031/f
=> chore(logging): remove unique targetId from `warn`, add to `info`

schema/core.xsd
`form` element is handled by same component as `view` and has the same capabilities, reflecting this on the schema
=> fix(schema): view aliases common schema

docs/reference_list.md, docs/reference_sectionlist.md, examples/_includes/macros/text-field/index.xml.njk, examples/_includes/macros/text-field/styles.xml.njk, examples/_includes/templates/styles.xml.njk, examples/ui/ui-elements/list/keyboard-dismiss/index.xml.njk, examples/ui/ui-elements/list/keyboard-persist-tap/index.xml.njk, examples/ui/ui-elements/section-list/dismiss-keyboard/index.xml.njk, examples/ui/ui-elements/section-list/keyboard-persist-tap/index.xml.njk, schema/core.xsd, src/components/hv-list/index.tsx, src/components/hv-section-list/index.tsx, src/services/keyboard/index.ts
Add support for `keyboardShouldPersistTaps` to List and SectionList. 
| List  | SectionList  |
|---|---|
| ![list](https://github.com/user-attachments/assets/29116f31-bce5-42ff-9ba4-42b8fe1efc65)  |  ![sectionlist](https://github.com/user-attachments/assets/116decd9-31af-4a0a-9f00-291666a09405) |
=> feat(lists): Add support for `keyboardShouldPersistTaps`

src/core/components/hv-root/index.tsx, src/services/dom/parser.ts, src/services/dom/types.ts, src/types.ts
This PR adds support for `network-retry-action`.
When the attribute is present, we will pass down the value in the request header (`X-Network-Retry-Action`).
This is meant for retrying non GET requests when the network call fails. It is up to the consumer of the Hyperview library to handle this header as part of the fetch implementation (passed in as a prop).
=> feat(network-retry): add network retry action

docs/reference_navigator.md, src/core/components/hv-navigator/index.tsx
Add the ability to install event listener on the `<navigator>` tag, for example to allow reloading the navigator document upon certain event occurring.
=> feat(hv-navigator): Support for behaviors with `on-event` trigger

src/core/components/hv-root/index.tsx, src/services/render/index.tsx
As we move to create more community components within Hyperview, we will start running into issues with XML structures and rendering. As an example, the updated `bottom-sheet` schema is going to require non-rendering child elements to pass multiple values. The current functionality only supports two ways of ignoring rendering a child:
1. Use of the [`hide` attribute](https://github.com/Instawork/hyperview/blob/d1e0364a95f61bb378b7c4e830817a2a75fa7ba4/src/services/render/index.tsx#L23-L28)
2. Hard coding a set of known local names which [should be ignored](https://github.com/Instawork/hyperview/blob/d1e0364a95f61bb378b7c4e830817a2a75fa7ba4/src/services/render/index.tsx#L37-L43)
The new `renderChildNodes` method allows passing in a `ChildNode[]` where the caller has control over which …
=> chore(render): add support for rendering a filtered list of children

demo/backend/navigation/behaviors/actions/new/index.xml.njk
Using the correct `loading-screen` id
=> fix(demo): correct loading screen id

docs/reference_behavior_attributes.md
=> fix(documentation): typo

src/core/components/hv-root/types.ts, src/core/components/hv-screen/types.ts
Props were updated in https://github.com/Instawork/hyperview/pull/791 to allow separating the props from `hv-root` and `hv-screen`. The `registerPreload` function ended up being exposed at the root level but provides no mapping and was unnecessary.
=> chore(hv-screen): migrate `registerPreload` to screen props

docs/example_advanced_form.md, docs/example_basic_form.md, docs/example_delayed_navigation.md, docs/example_event_dispatch.md, docs/example_infinite_scroll.md, docs/example_lazy_load.md, docs/example_photo_sharing.md, docs/example_pull_to_refresh.md, docs/example_tabs.md
When we migrated the backend code to a new directory, we forgot to update direct links to examples in docs.
Solves #998
=> fix(docs): links to code

demo/backend/ui/ui-elements/forms/text-field/_basic/index.xml.njk, demo/backend/ui/ui-elements/forms/text-field/_basic/styles.xml.njk, demo/backend/ui/ui-elements/forms/text-field/_multiline/index.xml.njk, demo/backend/ui/ui-elements/forms/text-field/_multiline/styles.xml.njk, demo/backend/ui/ui-elements/forms/text-field/index.xml.njk, docs/reference_textfield.md, schema/core.xsd, src/services/stylesheets/index.ts
Add missing attributes that apply to `text-field` element:
- `selectionColor` (https://reactnative.dev/docs/textinput#selectioncolor)
- `cursorColor` (Android only, [ref](https://reactnative.dev/docs/textinput#cursorcolor-android))
- `textAlignVertical` (style attribute, Android only, [ref](https://reactnative.dev/docs/text-style-props#textalignvertical-android))
Also add missing examples for text-input in the demo app, and update the docs.
| iOS | Android |
|----|----|
| <img width="500" alt="Screenshot 2024-11-22 at 3 22 31 PM" src="https://github.com/user-attachments/assets/57255e96-7004-4ebc-ae44-ad9b40ba7b3b"> | <img width="527" alt="Screenshot 2024-11-22 at 3 22 34 PM" src="https://github.com/user-attachments/assets/c9d7a88b-4c23-4d45-8560-5227ae19eb40"> |
=> fix(text-field): Missing style attributes and examples

demo/backend/ui/ui-elements/forms/text-field/_basic/index.xml.njk, demo/backend/ui/ui-elements/forms/text-field/_multiline/index.xml.njk, docs/reference_textfield.md, schema/core.xsd
Add `selectionHandleColor` attribute of text-field to documentation and schema.
Note: this attribute will only have effect with React Native 0.74+
=> chore(docs/schema): text-field's `selectionHandleColor` attribute (Android only)

demo/backend/_includes/templates/base.xml.njk, demo/backend/_includes/templates/root.xml.njk, demo/backend/index-reloaded.xml.njk, demo/backend/index.xml.njk, demo/backend/navigation/behaviors/actions/reload/index.xml.njk, src/core/components/hv-route/index.tsx
Resolving issue with `on-event` behaviors embedded in `<navigator>` elements no properly performing `reload` action.
- [fix: only reset flag when loading](https://github.com/Instawork/hyperview/pull/1005/commits/b665f2d721a58cf5df0b97066470231defaa009f): copied over from [`hv-screen` implementation](https://github.com/Instawork/hyperview/blob/42e1534c371b32fff97efaaf122f79165c06d7aa/src/core/components/hv-screen/index.js#L176-L180). The issue with having it outside the if/then is that it could be cleared when a parent component causes an update before this component has updated its own state.
- [fix: include state in url logic](https://github.com/Instawork/hyperview/pull/1005/commits/dac168c5e69e0de7e414f623cab4328848c4e71d): as with `hv-screen`, the update mechanism needs to inject data …
=> fix(navigation): action reload is not reading href

src/core/components/hv-screen/index.js
Resolving a bug where a delay in the behavior is applied to both the triggering of the behavior and the subsequent document injection.
Example:
```
<behavior action="new" delay="1000" href="/hyperview/public/navigation/behaviors/actions/modal/index.xml" show-during-load="loading-screen" />
```
| -- | -- |
| ![before](https://github.com/user-attachments/assets/2788818b-78d6-4c94-991e-b7aa7ec2b82e) | ![after](https://github.com/user-attachments/assets/574ae86b-c4a7-451c-b87c-c7a5a8219ddf)
[Asana](https://app.asana.com/0/1204008699308084/1209072402643062/f)
=> fix(hv-screen): delay should only be applied when loading document

src/contexts/navigator-map.tsx, src/core/components/hv-navigator/index.tsx, src/core/components/hv-root/index.tsx, src/core/components/hv-route/index.tsx, src/core/components/hv-route/types.ts, src/core/components/hv-screen/index.js, src/core/components/hv-screen/types.ts, src/core/components/loading/index.tsx, src/core/components/loading/types.ts, src/services/behaviors/index.ts, src/services/navigation/index.ts, src/types.ts
Includes:
- https://github.com/Instawork/hyperview/commit/9bcc97c96cd4c744b97b36b65127f1761337372a
- https://github.com/Instawork/hyperview/commit/a371b77db7fcc86239225152f40a1bf2600f8d25
QA performed in https://github.com/Instawork/mobile/pull/6944
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1209172221808002
=> chore(navigation): loading screen improvements

src/services/navigation/index.ts
Passing behavior element to loading screen should not be conditional on the presence of a `show-during-load` attribute.
=> fix(loadingscreen): always pass behavior element

src/core/components/hv-root/index.tsx, src/core/components/hv-root/types.ts, src/core/components/hv-screen/types.ts
Removing legacy support for external navigation
Step 1: hv-root is updated to remove the multiple hierarchies.
- https://github.com/Instawork/hyperview/pull/1029/commits/f18fd436eba3a073549a8bfaaf1acb4a998e50ed
[Asana](https://app.asana.com/0/1204008699308084/1209086306165666/f)
Step 2: update the exposed props for `hv-root` (public Hyperview)
- [chore: remove unneeded external props, move to internal](https://github.com/Instawork/hyperview/pull/1029/commits/962c7947cc83ef3217126c8ef249508e6197e2ee)
- [chore: limit to only required props](https://github.com/Instawork/hyperview/pull/1029/commits/7336dfdd5395835b430a47f474d99542a72fe539)
[Asana](https://app.asana.com/0/1204008699308084/1209086306165667/f)
=> chore(navigation): remove support for externally provided navigation

demo/backend/behaviors/basic/triggers/blur/_date-field/index.xml.njk, demo/backend/behaviors/basic/triggers/blur/_picker-field/index.xml.njk, demo/backend/behaviors/basic/triggers/change/_date-field/index.xml.njk, demo/backend/behaviors/basic/triggers/change/_picker-field/index.xml.njk, demo/backend/behaviors/basic/triggers/focus/_date-field/index.xml.njk, demo/backend/behaviors/basic/triggers/focus/_picker-field/index.xml.njk, demo/backend/behaviors/basic/triggers/refresh/index.xml.njk
Fix refresh trigger, and update UI that indicates a picker was blured/changed/focused to make it look less like a bug (we have two separate behaviors for each picker to showcase support at the root element level or as a child behavior).
https://app.asana.com/0/1205761271270033/1209182447962497/f
=> fix(demo): behavior triggers various issues

src/core/components/hv-route/index.tsx, src/core/components/hv-screen/index.js, src/core/components/hv-screen/types.ts, src/services/navigation/index.ts
The preload screen cache in `services/navigation` was redundant with the external context-provided cache. The service cache is removed and `hv-screen` is updated to receive the function from props.
`<screen>` based loading functionality tested in demo app.
[Asana](https://app.asana.com/0/1204008699308084/1209086306165670/f)
=> chore(loading screen): remove duplicate screen cache

src/core/components/hv-screen/index.js, src/services/navigation/index.ts, src/services/navigator/helpers.ts, src/types.ts
The route key and associated cache were a relic of external navigation and are not required for HV navigation.
[Asana](https://app.asana.com/0/1204008699308084/1209189437518181/f)
=> chore(navigation): remove unused route key

demo/backend/behaviors/advanced/set-value/_clear-delay/index.xml.njk, demo/backend/behaviors/advanced/set-value/_clear-indicator/index.xml.njk, demo/backend/behaviors/advanced/set-value/_clear/index.xml.njk, demo/backend/behaviors/advanced/set-value/_set-delay/index.xml.njk, demo/backend/behaviors/advanced/set-value/_set-indicator/index.xml.njk, demo/backend/behaviors/advanced/set-value/_set/index.xml.njk
The cleanup of "text area" missed removing the behaviors.
Relates to https://github.com/Instawork/hyperview/pull/1034
[Asana](https://app.asana.com/0/1205761271270033/1209017355656026/f)
=> fix(demo): `set-value` examples issues 

src/core/components/hv-root/index.tsx, src/services/navigation/index.ts
The url is already available in the state of each screen/route and doesn't need to be cached
[Asana](https://app.asana.com/0/1204008699308084/1209189437518188/f)
=> chore(navigation): remove unused url cache

src/core/components/hv-screen/errors.ts, src/core/components/hv-screen/index.js
Resolving an issue where Hyperview renders a white screen in certain cases. Instead of showing blank screen, show an error screen with options.
| -- | -- |
| ![before](https://github.com/user-attachments/assets/8358869e-4d10-4439-8e11-c9d412499845) | ![after](https://github.com/user-attachments/assets/f4bc91d9-f21c-4352-b325-566a8fee5b14) |
| ![before](https://github.com/user-attachments/assets/13df870c-4f95-4b6c-a9e0-029c08992dac) | ![after](https://github.com/user-attachments/assets/af57daf3-9a4f-4c01-9e9c-4201d1aecce6) |
> The cause of the empty content is under investigation. This change improves the user experience.
[Asana](https://app.asana.com/0/1204008699308084/1209252349679167/f)
=> fix(hvscreen): display error for missing content

demo/backend/advanced/case-studies/basic-forms/index.xml.njk, demo/backend/advanced/case-studies/basic-forms/next.xml.njk, demo/backend/advanced/case-studies/basic-forms/submit.xml, demo/backend/advanced/case-studies/basic-forms/submit2.xml
Add missing scroll attribute that causes layout to break.
https://app.asana.com/0/1205761271270033/1209017355656030/f
|---|---|
| ![before](https://github.com/user-attachments/assets/605032af-39e6-435b-9887-e70002a65ef8) | ![after](https://github.com/user-attachments/assets/e1fa79bf-b831-4f62-a48f-670772c76acd) |
=> fix(demo): Advanced > Basic Forms styles

schema/core.xsd
Adding an `autoCapitalize` attribute into `text-field`.
Tested locally against changes made in https://github.com/Instawork/instawork/pull/36726
Required for https://github.com/Instawork/instawork/pull/36726
=> chore(schema): update for `autoCapitalize` feature

demo/App.tsx, demo/backend/navigation/navigator/stack/index.xml.njk, demo/backend/ui/ui-elements/content.xml.njk, demo/backend/ui/ui-elements/loading-screen/index.xml.njk, demo/backend/ui/ui-elements/loading-screen/modal.xml.njk, demo/src/loading-screen/behavior-loading-screen.tsx, demo/src/loading-screen/index.tsx, demo/src/loading-screen/stack-loading-screen.tsx, demo/src/loading-screen/types.ts, docs/reference_loading_screen.md
Relates to https://github.com/Instawork/hyperview/pull/1007
The demo updates must wait until the [loading screen feature](https://github.com/Instawork/hyperview/pull/1016) is released as demo points to the release version of Hyperview.
A new "Loading Screen" subsection has been added to UI/UI Elements:
This section provides examples of
- using a custom loading screen which uses the `id` of the behavior to colorize the loader
- using a `<screen>` element from the document
- using the default loading screen
https://github.com/user-attachments/assets/2a893ed0-a71e-464d-89c8-67b3402bc469
The Navigation/Stack example has been updated to show how to customize the loading screen color based on the `id` of a `<nav-route>` element.
https://github.com/user-attachments/assets/7fcff03d-a747-4042-95c2- …
=> chore(navigation): demo for supporting alternate loading screens for behaviors and nav-routes

.circleci/config.yml
This helps getting the latest Hyperview changes into CI, before cutting a release. It is also helpful to have the changes from master deployed before a release.
=> fix(ci): sync Hyperview code into demo

demo/backend/behaviors/basic/triggers/back/index.xml.njk
The demo at `Behaviors > Triggers > Back` frequently re-triggers.
This same demo appears also at `Navigation > Behaviors > Triggers > Back`. This version includes a delay on the `back` action to ensure the `hide` has completed. This delay was ported to fix the issue.
| -- | -- |
| ![before](https://github.com/user-attachments/assets/80781a5f-0986-459d-9395-d9a72ae5acfa) | ![after](https://github.com/user-attachments/assets/7eeaafac-f452-4890-b76a-473924a726df) |
[Asana](https://app.asana.com/0/1204008699308084/1209227756307892)
=> fix(demo): back behavior triggers multiple times

demo/backend/_includes/templates/styles.xml.njk, demo/backend/behaviors/advanced/set-value/index.xml.njk, demo/backend/behaviors/basic/triggers/blur/index.xml.njk, demo/backend/behaviors/basic/triggers/change/index.xml.njk, demo/backend/behaviors/basic/triggers/focus/index.xml.njk, demo/backend/ui/ui-elements/forms/date-field/index.xml.njk, demo/backend/ui/ui-elements/forms/picker/index.xml.njk, src/components/hv-date-field/picker/index.ios.tsx, src/components/hv-date-field/picker/styles.ts
New version of datepicker no longer auto center - this fix forces it back in the center of the picker modal. This PR also cleans up duplication on the demo styles for the picker modal.
|--|--|
| ![Simulator Screenshot - iPhone 16 Pro - 2025-02-14 at 16 52 40](https://github.com/user-attachments/assets/31ee777f-47ef-47c8-92fa-db21e23d7745) | ![Simulator Screenshot - iPhone 16 Pro - 2025-02-14 at 16 41 59](https://github.com/user-attachments/assets/d1e0b053-559a-4a00-bc9c-7ac494ab1977) |
=> fix: date picker style

src/components/hv-date-field/picker/index.ios.tsx
Explicitly set an arbitrary maximum date to work around an iOS bug, where the date picker will not allow a selection after another date picker with a max date was rendered.
https://app.asana.com/0/1204008699308084/1209403666139698
|--|--|
| ![before](https://github.com/user-attachments/assets/a93fa321-9a5c-4f16-84fa-c371a6b72294) | ![after](https://github.com/user-attachments/assets/458fb835-1f88-47e5-8d80-f17426131d25) |
=> fix(ios): date picker max date bug

demo/App.tsx, demo/web/404.html, demo/web/index.html
- add missing route definition for tabs
- implement [SPA + GH pages hack](https://github.com/rafgraph/spa-github-pages#usage-instructions), to allow refreshing the page and preserve existing state
Refreshing the page on the tabs route is still not fixed, but every other "deep" pages are refreshing/persisting state correctly.
=> fix(demo): Web URL state bugs

src/services/dom/errors.ts
Reducing the amount of data in the message string. Improving context with `id` and `doc`.
Relates to https://github.com/Instawork/mobile/pull/7084
[Asana](https://app.asana.com/0/1204008699308084/1209425378622147)
=> chore(error): improve error message and context for DocumentGetElementByIdError

src/core/components/hv-root/index.tsx, src/services/dom/helpers.ts
In the original implementation, the original `element` was the fallback target. In cases where a `targetId` is specified but unfound, we can still fall back to the original element.
Relates to https://github.com/Instawork/hyperview/pull/1068
| -- | -- |
| ![before](https://github.com/user-attachments/assets/7310c5e1-ed69-46ed-a5f3-23dd5aace305) | ![after](https://github.com/user-attachments/assets/511d6155-7fdb-4f52-97c3-97cf44db580a) |
An error is being logged to notify developers
| | |
| -- | -- |
| ![error-closed](https://github.com/user-attachments/assets/35578e01-d656-4fa1-83be-9e227fdb340c) | ![error-open](https://github.com/user-attachments/assets/d7850c85-9ac8-4b9a-a38b-0daf5655925a) |
[Asana](https://app.asana.com/0/1204008699308084/1209438247623833)
=> fix(behavior): set fallback target

src/services/dom/errors.ts
The existing dom/errors were not extending `HvBaseError` so did [not log with context and improved fingerprinting](https://github.com/Instawork/mobile/blob/75f452fa06e72da720d57c4446ccfffcb2c4caae/core-mobile/src/services/error-reports/index.ts#L51-L57).
Before: https://instawork.sentry.io/issues/6233499416/?project=1549809&project=1549805&query=for%20tag%20%3Ca%3E&referrer=issue-stream&sort=date&statsPeriod=14d&stream_index=0
After: https://instawork.sentry.io/issues/6332099191/?project=1549805&query=&referrer=issue-stream&sort=date&statsPeriod=1h&stream_index=0#exception
[Asana](https://app.asana.com/0/1204008699308084/1209319270405176)
=> chore(errors): improve quality of dom errors

demo/backend/navigation/behaviors/actions/reload/index.xml.njk, demo/backend/navigation/behaviors/actions/reload/reloaded.xml.njk
Resolving issues in Navigation > Behaviors > Reload
1. "Reload different screen" had an invalid loading value and caused the whole app to reload without navigation. Resolved to show loading a new screen in place.
2. The "Reload hierarchy" was not directly related to "reload" functionality and will be moved to a more appropriate location in the future.
| -- | -- |
| ![before](https://github.com/user-attachments/assets/bb8099b9-5d98-4d8d-b66e-6894f9f464c1) | ![after](https://github.com/user-attachments/assets/4f50b0e5-f846-444b-9e6f-b42e6fc3f2e0) |
[Asana](https://app.asana.com/0/1204008699308084/1209182447962509)
=> chore(demo): reload example improvements

src/core/components/hv-route/index.tsx
Moving the `onRouteFocus` callbacks post-mutation to ensure listeners receive the correct state.
=> chore(navigation): focus callbacks trigger post-mutation

src/components/hv-web-view/index.tsx
Pass through shared cookies enabled prop for iOS.
=> fix(web-view): support shared cookies

demo/App.tsx
Resolving the navigation glitch seen in the demo app after updating `expo` and `react-native`.
Values below 2 showed the glitch always. Values between 2-5 showed the glitch often. So far a value of 10 has not exhibited the glitch.
| -- | -- |
| ![before](https://github.com/user-attachments/assets/a20b7aa0-785f-4874-8d7d-d5157de26cfc) | ![after](https://github.com/user-attachments/assets/b97e2b30-e150-4c59-b5f0-09c42543d38c) |
Relates to
- https://github.com/Instawork/hyperview/pull/1092
- https://github.com/Instawork/hyperview/pull/1096
[Asana](https://app.asana.com/0/1204008699308084/1209518863613015)
=> chore(navigation): resolve performance issue

docs/reference_header.md
`<header>` element might have been at some point a special element that could render as a sibling of `<body>`, but that is no longer the case: it is now just an alias of `<view>`. We might want to restore this original intent though in a future iteration.
=> fix(docs): `<header>` reference

demo/src/Components/BottomSheet/BottomSheet.tsx
https://app.asana.com/0/1204008699308084/1209403666139705
+ updated bottom sheet to include changes made in core-mobile component
=> fix(bottom-sheet): expo sdk update bug fix 

demo/backend/_includes/templates/base.xml.njk, demo/backend/advanced/community/elements/scroll-opacity/_styles.xml.njk, demo/backend/advanced/community/elements/scroll-opacity/index.xml.njk, demo/schema/hyperview.xsd, demo/schema/scroll-opacity.xsd, demo/src/Components/ScrollOpacity/ScrollOpacity.tsx, demo/src/Components/ScrollOpacity/index.ts, demo/src/Components/ScrollOpacity/utils.ts, demo/src/Components/index.ts, package.json, schema/scroll.xsd, src/components/hv-list/index.tsx, src/components/hv-section-list/index.tsx, src/components/hv-view/index.tsx, src/components/hv-view/types.ts, src/core/components/hv-screen/index.js, src/core/components/scroll/context.tsx, src/core/components/scroll/index.tsx, src/core/components/scroll/types.ts, src/core/hyper-ref/index.tsx, src/index.ts
Every scrollable components - `ScrollView`, `FlatList`, `SectionList` and `KeyboardAwareScrollView` - now optionally report their scroll position to a shared context. This scroll context can then be used by custom elements.
This PR adds to the demo app a new `scroll-opacity` element that syncs its opacity with the position of the scroll view. A practical example is added to make the title of a page fade in/out as it leaves/comes back into view.
Implementation details: see commits breakdown.
https://github.com/user-attachments/assets/f84ad40d-0b07-4b2a-a871-c9f4a9638eb6
=> feat: scroll context

demo/backend/advanced/community/elements/nav-back/_styles.xml.njk, demo/backend/advanced/community/elements/nav-back/index.xml.njk, demo/backend/advanced/community/elements/nav-back/screen.xml.njk, demo/schema/hyperview.xsd, demo/schema/navigation.xsd, demo/src/Components/Filter/Filter.tsx, demo/src/Components/NavBack/NavBack.tsx, demo/src/Components/NavBack/index.ts, demo/src/Components/index.ts, demo/src/Helpers/misc.ts
Add new element to render the back or close button conditionally, based on the screen's navigation context.
https://github.com/user-attachments/assets/c53d1c2b-16fe-4ac1-a515-85a030ec6e09
=> feat(demo): `nav:back` element

demo/backend/advanced/community/elements/scroll-opacity/_styles.xml.njk, demo/backend/advanced/community/elements/scroll-opacity/index.xml.njk, demo/schema/scroll-opacity.xsd, demo/src/Components/ScrollOpacity/ScrollOpacity.tsx, demo/src/Components/ScrollOpacity/utils.ts
To increase flexibiility of the component, read position (input) and opacity (output) ranges from XML attribute, and use these to calculate the expected opacity. Update the example to show-case two different use.
Also add the ability to pass styles to the wrapping view.
https://github.com/user-attachments/assets/11c12a96-55a9-46f9-bc2e-1e0968298d69
=> refactor(demo/scroll-opacity): use ranges to map position with opacity

src/components/hv-date-field/field-label/index.tsx, src/components/hv-date-field/field-label/types.ts, src/components/hv-date-field/field/index.tsx, src/components/hv-picker-field/field-label/index.tsx, src/components/hv-picker-field/field-label/types.ts, src/components/hv-picker-field/field/index.tsx, src/core/components/modal/index.tsx, src/core/components/modal/modal-button/index.tsx, src/core/components/modal/modal-button/types.ts
Refactor date-field / picker-field element to delegate to underlying components that render `Text` components the responsibility to extract their props and styles from the Hyperview props (element / options / stylesheets). This is a pre-requisite to make it easier for this other change (#1129) to apply font scale props to Text components.
=> refactor: bring `element` prop closer to `Text` instances

src/core/components/hv-doc/context.ts, src/core/components/hv-doc/errors.ts, src/core/components/hv-doc/index.tsx, src/core/components/hv-doc/types.ts, src/core/components/hv-route/index.tsx, src/core/components/hv-route/types.ts, src/core/components/hv-screen/index.js, src/core/components/hv-screen/types.ts
Implementing `fetch` in `hv-doc`, lifting `fetch` out of `hv-route` and `hv-screen`.
- Remove the parser and fetch functionality out of `hv-route` and `hv-screen` and ported the code into `hv-doc`
- Internally handle the state changes which result from the fetch/error
- Implemented the `initialDoc` functionality in `hv-doc` which was previously in use between `hv-route` and `hv-screen`
[Asana](https://app.asana.com/0/1204008699308084/1209771721803047/f)
=> chore(hv-doc): lift fetch

docs/reference_datefield.md, docs/reference_pickerfield.md, docs/reference_text.md, docs/reference_textfield.md, schema/core.xsd, src/components/hv-date-field/field-label/index.tsx, src/components/hv-picker-field/field-label/index.tsx, src/core/components/modal/modal-button/index.tsx, src/services/font-scale/index.ts, src/services/font-scale/types.ts, src/services/index.ts
Refactor date-field / picker-field element to delegate to underlying components that render `Text` components the responsibility to extract their props and styles from the Hyperview props (element / options / stylesheets).
This is a pre-requisite to make it easier for this other change (#37760) to apply font scale props to Text components.
No demo yet, as the feature is broken in Expo SDK 52. See https://github.com/expo/expo/issues/32900 and https://github.com/facebook/react-native/issues/47499.
=> feat: font scale props

src/core/components/hv-route/index.tsx
The cloned doc being passed from `hv-route` to `hv-screen` was being cloned every render. Memoizing the cloning reduces this and improves performance.
| --- | --- |
| ![before](https://github.com/user-attachments/assets/a7b560d8-6e19-410d-bf22-e8ac500132d3) | ![after](https://github.com/user-attachments/assets/92827918-d877-47f9-b014-2ae1b6d4dce2) |
[Asana](https://app.asana.com/0/1204008699308084/1209802590586966/f)
https://github.com/user-attachments/assets/a7b560d8-6e19-410d-bf22-e8ac500132d3
https://github.com/user-attachments/assets/92827918-d877-47f9-b014-2ae1b6d4dce2
=> chore(performance): memoize doc cloning

src/core/components/hv-route/index.tsx, src/core/components/hv-route/types.ts, src/services/navigator/index.ts, src/services/navigator/types.ts
Lifting the instantiation of the Navigator service from the class to the FC. This is in preparation for future migrations. It also allows cleaning up the implementation by removing the static context and the `setContext` method.
[Asana](https://app.asana.com/0/1205761271270033/1209828747042806/f)
=> chore: lift navigation service instance into FC

demo/App.tsx, demo/backend/_includes/macros/tabbar-bottom/index.xml.njk, demo/backend/_includes/macros/tabbar-bottom/styles.xml.njk, demo/backend/_includes/templates/base.xml.njk, demo/backend/_includes/templates/header.xml.njk, demo/backend/_includes/templates/styles.xml.njk, demo/schema/hyperview.xsd, demo/schema/safe-area.xsd, demo/src/Components/SafeAreaView/SafeAreaView.tsx, demo/src/Components/SafeAreaView/index.ts, demo/src/Components/SafeAreaView/types.ts, demo/src/Components/index.ts, docs/reference_body.md, docs/reference_header.md, docs/reference_view.md
Add a new element that acts as a safe area container, then update the demo app server code to make use of it.
See commits breakdown for details
| iOS | Android |
|--|--|
| ![iOS](https://github.com/user-attachments/assets/5ea721a5-8a55-48ed-b04c-4ac0244a1adc) | ![Android](https://github.com/user-attachments/assets/21a33fbb-dd03-45ac-ba4e-0f00f7350263) |
=> feat(demo): `safe-area` element

src/core/components/hv-doc/context.ts, src/core/components/hv-doc/index.tsx, src/core/components/hv-doc/types.ts, src/core/components/hv-route/index.tsx, src/core/components/hv-route/types.ts, src/core/components/hv-screen/index.js, src/core/components/hv-screen/types.ts
Since all implementations set the localDoc before setting the state's doc, the code can be centralized into the hv-doc state setter.
[Asana](https://app.asana.com/0/1204008699308084/1209864080706780/f)
=> chore(hv-doc): simplify state

src/core/components/hv-doc/context.ts, src/core/components/hv-doc/index.tsx, src/core/components/hv-doc/types.ts, src/core/components/hv-route/index.tsx, src/core/components/hv-route/types.ts, src/core/components/hv-screen/index.js, src/core/components/hv-screen/types.ts
Lifting the error component into `hv-doc`.
Also resolved an issue where the `retry` option was faulty. The retry was previously based on the url in state which was only set on success. This meant that a first request failure would have no url to try. It also meant that subsequent requests would end up retrying the previous url instead of the current.
[Asana](https://app.asana.com/0/1204008699308084/1209771721803061/f)
=> chore(hv-doc): lift error component into hv-doc

src/core/components/hv-doc/index.tsx
1. Having the `onUpdate` inside the `useMemo` was causing occasional infinite loops with external components which have `useEffect` hooks that depend on `onUpdate` (see [example](https://github.com/Instawork/mobile/blob/81b00f1974f373150580b9c76e113627eca312b4/core-mobile/src/components/hyperview-s3-file-upload/hooks/ui-state.ts#L38-L83)). By moving the `onUpdate` outside of the memo, it becomes a stable reference and does not trigger external hooks.
2. Also stabilized the `setScreenState` callback by depending on the presence of an element rather than the element itself.
3. Temporarily provide immediate access to the `url` value of state. Currently external components are still calling loadUrl which is occurring before the state has completed. Once the load hooks are internalized, this …
=> chore(hv-doc): improve state stability and data

src/core/components/hv-navigator/index.tsx, src/core/components/hv-route/index.tsx, src/types.ts
Using a navigation structure with a modal:
```
<navigator id="home" type="stack">
<nav-route id="test" href="foo" modal="true" />
</navigator>
```
The components will automatically inject a stack navigator into the modal, resulting in the following:
```
<navigator id="home" type="stack">
<nav-route id="test" href="foo" modal="true">    <--- modal=true
<navigator id="modal-stack" type="stack">
<nav-route id="modal-test" href="foo" modal="false" />   <--- modal=false
</navigator>
</nav-route>
</navigator>
```
Note in this case the inner route "modal-test" is the one which performs the load. In current Hyperview, the modal is set to false for this route.
The change will preserve all existing functionality but ensure the "isModal" param for both routes will be "true". The new `needsSubStack` …
=> chore(modal): update `isModal` param usage

.cursor/rules/demo-run.mdc
Create a rule to help developers demo their changes. This rule will automatically create three terminal windows and run the appropriate scripts to run the Hyperview demo on iOS or Android.
- Made a change to `demo/backend/index.xml.njk`
- Asked Cursor to "demo this change"
- Cursor created three terminal windows (in Cursor)
- I followed up with a request to "Run this in android"
[Asana](https://app.asana.com/1/47184964732898/project/1204008699308084/task/1209928413172898?focus=true)
=> chore(cursor): create rule to help with launching demo

src/core/components/hv-doc/context.ts, src/core/components/hv-doc/index.tsx, src/core/components/hv-doc/types.ts, src/core/components/hv-root/index.tsx, src/core/components/hv-route/index.tsx, src/core/components/hv-route/types.ts, src/core/components/hv-screen/index.js, src/core/components/hv-screen/types.ts, src/types.ts
Remove legacy load triggers from hv-route and hv-screen and internalize into hv-doc.
- Removed use of "needsLoad"
- Removed unnecessary lifecycle functions
- Verified current functionality including load, reload, append, modals, etc.
See commits for breakdown
[Asana](https://app.asana.com/1/47184964732898/project/1204008699308084/task/1209875001265866?focus=true)
=> chore(hv-doc): internalize loading logic

src/core/components/hv-doc/index.tsx, src/core/components/hv-doc/types.ts, src/core/components/hv-route/index.tsx, src/core/components/hv-route/types.ts
Merging the hv-doc implementation to use a single instance across both `hv-route` and `hv-screen`. This has the benefit of reducing individual state management, load tracking, and removes the need to pass a clone of the loaded doc into `hv-screen`. This also includes setting the initial state to use `null` values instead of `undefined` to reduce the effect of state updates causing re-renders.
This has been tested within HV Demo including features which force a screen to reload.
[Asana](https://app.asana.com/1/47184964732898/project/1205761271270033/task/1209875001265872?focus=true)
=> chore(hv-doc): consolidate hv-doc state

src/services/behaviors/index.ts
Removing behavior logging due to complications with determining whether the behavior was performed.
[Asana](https://app.asana.com/1/47184964732898/project/1204008699308084/task/1205585476216008?focus=true)
=> chore(behaviors): remove behavior logging

src/contexts/navigation.ts, src/core/components/hv-root/index.tsx, src/core/components/hv-root/types.ts, src/core/components/hv-route/index.tsx, src/core/components/hv-route/types.ts, src/core/components/hv-screen/types.ts
The `handleBack` component was a remnant of legacy navigation where we needed to handle back requests from Android's back button. Since navigation was internalized and the legacy external navigation has been removed, this property is no longer needed.
[Asana](https://app.asana.com/1/47184964732898/project/1205761271270033/task/1210238602307164?focus=true)
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1210238602307164
=> chore(handleBack): remove unused component

src/core/components/hv-route/index.tsx, src/core/components/hv-screen/index.js, src/core/components/hv-screen/types.ts
`hv-root` is [already a provider](https://github.com/Instawork/hyperview/blob/0a8ac8f5d264f4ba3fc3d4c87896cb9bf85460d7/src/core/components/hv-root/index.tsx#L567) of `<DateFormatContext>` it is redundant to consume within `hv-route` and provide within `hv-screen`.
[Asana](https://app.asana.com/1/47184964732898/project/1204008699308084/task/1210316546014477?focus=true)
=> chore(date-context): remove redundant contexts

src/components/hv-list/index.tsx, src/components/hv-section-list/index.tsx, src/core/components/hv-element/index.tsx, src/core/components/hv-route/index.tsx, src/core/components/hv-screen/index.js, src/core/hyper-ref/index.tsx
Improving performance by creating a new `hv-element` component as a replacement for Render.renderElement. This allows memoizing the options and props of the component to reduce unneeded re-renders.
[Asana](https://app.asana.com/1/47184964732898/project/1204008699308084/task/1210344460236268?focus=true)
=> chore(hv-element): create component for element rendering

demo/src/Components/NavBack/NavBack.tsx, src/core/components/hv-element/index.tsx, src/core/components/hv-root/index.tsx, src/core/utils.ts, src/services/render/index.tsx
Consolidate the logic between `src/services/render` and the new `hv-element` component.
- Created a new utility to abstract the `null` render logic and logging
- Update render service to use logic and then return the component
- Update `hv-element` to use utility for logic and logging
- Export `hv-element` for access outside Hyperview
- Confirmed external use of `Hyperview.renderElement` with new logic still working (using existing nav-back demo)
- Update `nav-back` demo to use component instead of function
[Asana](https://app.asana.com/1/47184964732898/project/1204008699308084/task/1210368849843731?focus=true)
=> chore(render): simplify render.renderElement

src/components/hv-option/index.tsx, src/components/hv-select-single/index.tsx, src/components/hv-text/index.tsx, src/components/hv-view/index.tsx, src/services/render/index.tsx
The updated code was causing an increase in "Each child in a list should have a unique key prop" warnings. It was determined that the legacy code used spreading over the child array which causes React to not issue the warning. [See documentation](https://react.dev/reference/react/createElement#:~:text=You%20should%20only,they%20never%20reorder.).
This code temporarily reverts the various components which were throwing the warnings in the Hyperview demo. They should be restored at a later time to restore the intended functionality.
- [Added a key to the \<HvElement\>](https://github.com/Instawork/hyperview/pull/1176/commits/a6406bc66411b55125102888987c6be44dc31a03)
- [Reverted use of declarative syntax where needed](https://github.com/Instawork/hyperview/pull/1176/commits/ec8e044dfb9bdf8054 …
=> chore(render): revert view changes

demo/backend/advanced/case-studies/basic-forms/index.xml.njk, src/core/components/hv-root/index.tsx
Performing an update action (append, prepend, replace, replace-inner) with a delay requires that the behavior element has an id. The `basic-forms` demo was missing an id so was non functional.
- Added an error to warn developers of this condition
- Fixed the demo by adding an id to the element
| Before | Error | After |
| -- | -- | -- |
| ![before](https://github.com/user-attachments/assets/dfa1fded-0d8d-47a7-846e-def4b7e573fe) | ![error](https://github.com/user-attachments/assets/66e2d97e-64cf-4bae-8c03-02ba9b2700bf) | ![after](https://github.com/user-attachments/assets/c349dacd-ac16-410b-8682-3d1b3e4c02a6) |
[Asana](https://app.asana.com/1/47184964732898/project/1204008699308084/task/1210535376481469?focus=true)
=> chore(behavior): warn for invalid update behavior

src/index.ts
Exposing the dependencies used by /demo and our mobile apps to avoid requiring reaching into modules.
Evaluated all uses of Hyperview from the demo app and the mobile codebase to check all imports and uses.
The `Events`, `Logging`, `Namespace` and `TestHelpers` are bulk exported to allow using their namespaces as before. Example: `Events.dispatch`. All others are individually exported. Example: ` Dom.getBehaviorElements()` would become `getBehaviorElements()`
[Asana](https://app.asana.com/1/47184964732898/project/1204008699308084/task/1210571640157700?focus=true)
=> chore: export required dependencies

src/index.ts
Exporting the `TestHelpers` from Hyperview causes an issue in the mobile codebase around the use of `import fs from 'fs';` in `test/helpers/file.ts`. The export is removed and the mobile app will continue to reach into Hyperview to access the `parse` function.
=> chore(test-helpers): remove export

src/elements/hv-picker-field/index.ios.tsx, src/elements/hv-picker-field/index.tsx
Convert `hv-picker-field` (iOS and Android) to Functional Component. Confirm no degradation in render count.
[Asana](https://app.asana.com/1/47184964732898/project/1204008699308084/task/1210601789543016?focus=true)
=> chore(picker-field): convert to Functional Component

src/contexts/index.ts, src/elements/hv-route/hv-route.tsx
Removing the unnecessary `OnUpdateContext`.
[Asana](https://app.asana.com/1/47184964732898/project/1204008699308084/task/1210620686213504?focus=true)
=> chore(onupdate): remove unused context

src/elements/hv-doc/hv-doc.tsx, src/elements/hv-route/hv-route.tsx, src/elements/hv-route/types.ts, src/elements/hv-screen/index.js, src/elements/hv-screen/types.ts
`hv-screen` is no longer responsible for performing loading and therefore does not need to handle the preloadScreen functionality or cache maintenance. These functions are performed by `hv-doc`. Removing all of these greatly simplifies the `hv-screen` implementation and reduces the number of props that need to be passed in.
[Asana](https://app.asana.com/1/47184964732898/project/1204008699308084/task/1209875001265863?focus=true)
=> chore(hv-screen): remove loading features

src/core/components/navigator-stack/helpers.ts, src/index.ts, src/services/navigator/index.ts, src/types.ts
To enable mobile code to remain unchanged, these exports are temporarily being restored. Once HV is released, these can be removed and the mobile apps can be updated to use the new signatures.
Revert [this commit](https://github.com/Instawork/hyperview/commit/161a595b1a2c7fb4c0952cd278b6e9b1fe7602f4) post-release.
=> chore(exports): provide legacy types

src/elements/hv-section-list/index.tsx, src/elements/hv-section-list/types.ts
While the section-list as Functional Component works well in the demo and in many places in the mobile apps, it is failing in the profile section. After spending some time trying to debug the problem, it seemed better to postpone this FC migration for now. The other optimizations including the new context hierarchy remain.
=> chore(section-list): revert FC conversion

demo/app.config.ts, demo/package.json, demo/src/Components/Map/index.web.tsx, demo/webpack.config.ts, demo/yarn.lock, scripts/update-demo.sh
The underlying 3rd party replacement for react-native-web is not compatible with React 19, and Expo currently does not provide an out of the box solution for maps. This functionality was added as part of Instawork hackathon, but the feature never ended up being used, so we wont be investing in supporting this for the time being.
=> chore(demo): remove support for maps on web

demo/backend/behaviors/basic/indicators/inline-indicator/index.xml.njk
The url was incorrect and was causing a failure to load. Also, without an id assigned to the view, it can't be found in the doc after the delay.
| -- | -- |
| ![before](https://github.com/user-attachments/assets/25f69aa0-c295-4229-96a1-e7354c3dda49) | ![after](https://github.com/user-attachments/assets/982432d5-99b4-428b-bace-b9a81d246022) |
[Asana](https://app.asana.com/1/47184964732898/project/1204008699308084/task/1210741698093693?focus=true)
=> chore(demo): resolve inline indicator issues

src/elements/hv-doc/hv-doc.tsx
HvDoc receives alternate versions of a url as either a full url or a partial which can cause unnecessary reloads. This change ensures the full url is compared in all cases to avoid reloads.
> A [separate task](https://app.asana.com/1/47184964732898/project/1205761271270033/task/1210316546014483?focus=true) exists to track the root cause of why the url is changing.
[Asana](https://app.asana.com/1/47184964732898/project/1204008699308084/task/1210778282863683?focus=true)
=> chore(hv-doc): use full url comparison

demo/src/Components/BottomSheet/BottomSheet.tsx, demo/src/Components/Filter/Filter.tsx, demo/src/Components/Map/Map.tsx, demo/src/Components/Map/MapMarker.tsx, demo/src/Components/NavBack/NavBack.tsx, demo/src/Components/ProgressBar/ProgressBar.tsx, demo/src/Components/SafeAreaView/SafeAreaView.tsx, demo/src/Components/ScrollOpacity/ScrollOpacity.tsx
Replace all static references (`Hyperview.renderChildren`, etc.) from demo.
[Asana](https://app.asana.com/1/47184964732898/project/1204008699308084/task/1211107142019307?focus=true)
=> chore(demo): replace static access

src/elements/hv-screen/index.js, src/hyperview.tsx
Removing the unneeded statics and exports from `hv-screen` and the root component.
[Asana](https://app.asana.com/1/47184964732898/project/1205761271270033/task/1210535381643187?focus=true)
=> chore: remove unneeded statics and exports
